#!/bin/sh

# ====================================
# Install packages
# ====================================

read -p 'Install virtualbox additions? (y/N): ' choice

if [ "$choice" = "y" ]; then
    sudo pacman -S xf86-video-vmware virtualbox-guest-utils virtualbox-guest-modules-arch --noconfirm --needed
fi

sudo pacman -S xorg xorg-xinit feh rofi ranger bspwm sxhkd dunst vim neofetch python3 zsh noto-fonts noto-fonts-emoji chromium ttf-font-awesome otf-font-awesome pulseaudio pulseaudio-alsa pamixer unzip firefox picom wget make --noconfirm --needed


if pacman -Qs yay > /dev/null ; then
    echo "Yay is already installed, moving on..."
else
    rm -rf yay
    git clone https://aur.archlinux.org/yay.git
    cd yay
    makepkg -si --noconfirm
fi


yay -S polybar rxvt-unicode-256xresources spicetify-cli nerd-fonts-iosevka python-ueberzug spotify betterlockscreen --needed --removemake --nocleanmenu --nodiffmenu --noeditmenu --noconfirm


# ====================================
# Download and set background
# ====================================

mkdir ~/Documents &> /dev/null
mkdir ~/Documents/Wallpapers &> /dev/null
curl https://i.imgur.com/XCaXGFB.png > ~/Documents/Wallpapers/gruvbox.png

# ====================================
# Polybar font
# ====================================

mkdir ~/.local &> /dev/null
mkdir ~/.local/share &> /dev/null
mkdir ~/.local/share/fonts &> /dev/null
curl https://raw.githubusercontent.com/adi1090x/polybar-themes/master/polybar-8/fonts/icomoon-feather.ttf > icomoon-feather.ttf
mv icomoon-feather.ttf ~/.local/share/fonts/
fc-cache -vf ~/.local/share/fonts/

# ====================================
# Powerline arrow fix
# ====================================

wget https://github.com/powerline/powerline/raw/develop/font/PowerlineSymbols.otf
wget https://github.com/powerline/powerline/raw/develop/font/10-powerline-symbols.conf
mv PowerlineSymbols.otf ~/.local/share/fonts/
fc-cache -vf ~/.local/share/fonts/
mkdir ~/.config/fontconfig
mkdir ~/.config/fontconfig/conf.d
mv 10-powerline-symbols.conf ~/.config/fontconfig/conf.d/


# Make pacman display colored output
sudo sed -i 's/#Color/Color/g' /etc/pacman.conf

# =========================================
# Install oh my zsh and zsh-autosuggestions
# =========================================

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh) --unattended --keep-zshrc"
git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
git clone https://github.com/MichaelAquilina/zsh-autoswitch-virtualenv.git ~/.oh-my-zsh/custom/plugins/autoswitch_virtualenv


echo "=============="
echo "==== DONE ===="
echo "=============="
echo "$ chsh -s /bin/zsh"
echo "$ startx"
echo "$ feh --bg-fill ~/Documents/Wallpapers/wallpaper.png"

# Change to zsh
zsh
