# afmtodit
# Autogenerated from man page /usr/share/man/man1/afmtodit.1.gz
complete -c afmtodit -s a --description 'Use  n as the slant parameter in the font file; this is used by groff in the …'
complete -c afmtodit -s c --description 'Include comments in the font file in order to identify the PS font.'
complete -c afmtodit -s d --description 'The device description file is  desc_file rather than the default  DESC .'
complete -c afmtodit -s e --description 'The PostScript font should be reencoded to use the encoding described in enc_…'
complete -c afmtodit -s f --description 'The internal name of the groff font is set to R name .'
complete -c afmtodit -s i --description 'Generate an italic correction for each character so that the character\'s widt…'
complete -c afmtodit -s o --description 'The output file is  out_file instead of R font .'
complete -c afmtodit -s k --description 'Omit any kerning data from the groff font.'
complete -c afmtodit -s m --description 'Prevent negative left italic correction values.'
complete -c afmtodit -s n --description 'Don\'t output a  ligatures command for this font.'
complete -c afmtodit -s s --description 'The font is special.'
complete -c afmtodit -s v --description 'Print version.'
complete -c afmtodit -o i50 --description 'for italic fonts.'
complete -c afmtodit -o i0 --description 'to improve spacing with eqn (1).'
complete -c afmtodit -s x --description 'Don\'t use the built-in Adobe Glyph List.  FILES /usr/share/groff/1. 22.'

