# apropos
# Autogenerated from man page /usr/share/man/man1/apropos.1.gz
complete -c apropos -s d -l debug --description 'Print debugging information.'
complete -c apropos -s v -l verbose --description 'Print verbose warning messages.'
complete -c apropos -s r -l regex --description 'Interpret each keyword as a regular expression.'
complete -c apropos -s w -l wildcard --description 'Interpret each keyword as a pattern containing shell style wildcards.'
complete -c apropos -s e -l exact --description 'Each keyword will be exactly matched against the page names and the descripti…'
complete -c apropos -s a -l and --description 'Only display items that match all the supplied keywords.'
complete -c apropos -s l -l long --description 'Do not trim output to the terminal width.'
complete -c apropos -s s -l sections -l section --description 'Search only the given manual sections.'
complete -c apropos -s M -l manpath --description 'Specify an alternate set of colon-delimited manual page hierarchies to search.'
complete -c apropos -s L -l locale --description 'apropos will normally determine your current locale by a call to the C functi…'
complete -c apropos -s C -l config-file --description 'Use this user configuration file rather than the default of R ~/. manpath .'
complete -c apropos -s '?' -l help --description 'Print a help message and exit.'
complete -c apropos -l usage --description 'Print a short usage message and exit.'
complete -c apropos -s m --description 'systemc  [,. ],.'
complete -c apropos -l systems --description '[,. ].'
complete -c apropos -s V -l version --description 'Display version information.  EXIT STATUS.'

