# arping
# Autogenerated from man page /usr/share/man/man8/arping.8.gz
complete -c arping -s A --description 'The same as -U, but ARP REPLY packets used instead of ARP REQUEST.'
complete -c arping -s b --description 'Send only MAC level broadcasts.'
complete -c arping -s c --description 'Stop after sending count ARP REQUEST packets.'
complete -c arping -s D --description 'Duplicate address detection mode (DAD).  See  RFC2131, 4. 4. 1.'
complete -c arping -s f --description 'Finish after the first reply confirming that target is alive.'
complete -c arping -s I --description 'Name of network device where to send ARP REQUEST packets.'
complete -c arping -s h --description 'Print help page and exit.'
complete -c arping -s q --description 'Quiet output.  Nothing is displayed.'
complete -c arping -s s --description 'IP source address to use in ARP packets.'
complete -c arping -s U --description 'Unsolicited ARP mode to update neighbours\' ARP caches.'
complete -c arping -s V --description 'Print version of the program and exit.'

