# asn1Decoding
# Autogenerated from man page /usr/share/man/man1/asn1Decoding.1.gz
complete -c asn1Decoding -s b -l benchmark --description 'perform a benchmark on decoding.'
complete -c asn1Decoding -s s -l strict --description 'use strict DER decoding.'
complete -c asn1Decoding -s t -l no-time-strict --description 'use strict DER decoding but not in time fields.'
complete -c asn1Decoding -s h -l help --description 'display this help and exit.'
complete -c asn1Decoding -s v -l version --description 'output version information and exit AUTHOR Written by Fabio Fiorina.'

