# asn1Parser
# Autogenerated from man page /usr/share/man/man1/asn1Parser.1.gz
complete -c asn1Parser -s c -l check --description 'checks the syntax only.'
complete -c asn1Parser -s o -l output --description 'output file.'
complete -c asn1Parser -s n -l name --description 'array name.'
complete -c asn1Parser -s h -l help --description 'display this help and exit.'
complete -c asn1Parser -s v -l version --description 'output version information and exit AUTHOR Written by Fabio Fiorina.'

