# avahi-publish
# Autogenerated from man page /usr/share/man/man1/avahi-publish.1.gz
complete -c avahi-publish -s s -l service --description 'Register a service.  avahi-publish-service is equivalent to avahi-publish -s.'
complete -c avahi-publish -s a -l address --description 'Register an address/host name mapping.'
complete -c avahi-publish -s v -l verbose --description 'Enable verbose mode.'
complete -c avahi-publish -s H -l host --description 'Specify a host name for this service, in case it doesn\'t reside on the local …'
complete -c avahi-publish -s d -l domain --description 'Publish the service in the specified domain.'
complete -c avahi-publish -l subtype --description 'Register the service with an additional subtype in addition to the main type.'
complete -c avahi-publish -s f -l no-fail --description 'Don\'t fail if the daemon is not found running.'
complete -c avahi-publish -s h -l help --description 'Show help.'
complete -c avahi-publish -s V -l version --description 'Show version information.'

