# avahi-resolve
# Autogenerated from man page /usr/share/man/man1/avahi-resolve.1.gz
complete -c avahi-resolve -s n -l name --description 'Translate one or more fully qualified host names into addresses.'
complete -c avahi-resolve -s a -l address --description 'Translate one or more addresses into fully qualified host names.'
complete -c avahi-resolve -s v -l verbose --description 'Enable verbose mode.'
complete -c avahi-resolve -s 6 --description 'When resolving a host name, look for IPv6 addresses exclusively.'
complete -c avahi-resolve -s 4 --description 'When resolving a host name, look for IPv4 addresses exclusively.'
complete -c avahi-resolve -s h -l help --description 'Show help.'
complete -c avahi-resolve -s V -l version --description 'Show version information.'

