# avahi-dnsconfd
# Autogenerated from man page /usr/share/man/man8/avahi-dnsconfd.8.gz
complete -c avahi-dnsconfd -s D -l daemonize --description 'Daemonize after startup and redirect log messages to syslog.'
complete -c avahi-dnsconfd -s s -l syslog --description 'Log to syslog instead of STDERR.  Implied by --daemonize.'
complete -c avahi-dnsconfd -s k -l kill --description 'Kill an already running avahi-dnsconfd.  (equivalent to sending a SIGTERM).'
complete -c avahi-dnsconfd -s r -l refresh --description 'Tell an already running avahi-dnsconfd to refresh the DNS server data.'
complete -c avahi-dnsconfd -s c -l check --description 'Return 0 as return code when avahi-dnsconfd is already running.'
complete -c avahi-dnsconfd -s h -l help --description 'Show help.'
complete -c avahi-dnsconfd -s v -l version --description 'Show version information  FILES /etc/avahi/avahi-dnsconfd.'

