# avahi-set-host-name
# Autogenerated from man page /usr/share/man/man1/avahi-set-host-name.1.gz
complete -c avahi-set-host-name -s v -l verbose --description 'Enable verbose mode.'
complete -c avahi-set-host-name -s h -l help --description 'Show help.'
complete -c avahi-set-host-name -s V -l version --description 'Show version information.'

