# avahi-browse
# Autogenerated from man page /usr/share/man/man1/avahi-browse.1.gz
complete -c avahi-browse -s a -l all --description 'Browse for all service types registered on the LAN, not just the one specifie…'
complete -c avahi-browse -s D -l browse-domains --description 'Browse for browsing domains instead for services.'
complete -c avahi-browse -s d -l domain --description 'Browse in the specified domain.'
complete -c avahi-browse -s v -l verbose --description 'Enable verbose mode.'
complete -c avahi-browse -s t -l terminate --description 'Terminate after dumping a more or less complete list.'
complete -c avahi-browse -s c -l cache --description 'Terminate after dumping all entries available in the cache.'
complete -c avahi-browse -s l -l ignore-local --description 'Ignore local services, show only remote services.'
complete -c avahi-browse -s r -l resolve --description 'Automatically resolve services found.'
complete -c avahi-browse -s f -l no-fail --description 'Don\'t fail if the daemon is not found running.'
complete -c avahi-browse -s p -l parsable --description 'Make output easily parsable for usage in scripts.'
complete -c avahi-browse -s k -l no-db-lookup --description 'Don\'t lookup services types in service type database.'
complete -c avahi-browse -s b -l dump-db --description 'Dump the service type database (may be combined with -k).'
complete -c avahi-browse -s h -l help --description 'Show help.'
complete -c avahi-browse -s V -l version --description 'Show version information.'

