# basename
# Autogenerated from man page /usr/share/man/man1/basename.1.gz
complete -c basename -s a -l multiple --description 'support multiple arguments and treat each as a NAME.'
complete -c basename -s s -l suffix --description 'remove a trailing SUFFIX; implies -a.'
complete -c basename -s z -l zero --description 'end each output line with NUL, not newline.'
complete -c basename -l help --description 'display this help and exit.'
complete -c basename -l version --description 'output version information and exit EXAMPLES.'
complete -c basename -s '>' --description '.'

