# batch
# Autogenerated from man page /usr/share/man/man1/batch.1p.gz
complete -c batch -s t --description 'time relative to the timezone specified by the TZ variable.'
complete -c batch -o qb --description 'A number of features were added to list and control batch work separately fro…'
complete -c batch -s m --description 'option was included on the equivalent at command because it is historical pra…'

