# bdftopcf
# Autogenerated from man page /usr/share/man/man1/bdftopcf.1.gz
complete -c bdftopcf -o pn --description 'Sets the font glyph padding.'
complete -c bdftopcf -o un --description 'Sets the font scanline unit.'
complete -c bdftopcf -s m --description 'Sets the font bit order to MSB (most significant bit) first.'
complete -c bdftopcf -s l --description 'Sets the font bit order to LSB (least significant bit) first.'
complete -c bdftopcf -s M --description 'Sets the font byte order to MSB first.'
complete -c bdftopcf -s L --description 'Sets the font byte order to LSB first.'
complete -c bdftopcf -s t --description 'When this option is specified,  bdftopcf will convert fonts into "terminal" f…'
complete -c bdftopcf -s i --description 'This option inhibits the normal computation of ink metrics.'
complete -c bdftopcf -s o --description 'By default  bdftopcf writes the pcf file to standard output; this option give…'
complete -c bdftopcf -s v --description 'Print version information and exit.'

