# blkdiscard
# Autogenerated from man page /usr/share/man/man8/blkdiscard.8.gz
complete -c blkdiscard -s o -l offset --description 'Byte offset into the device from which to start discarding.'
complete -c blkdiscard -s l -l length --description 'The number of bytes to discard (counting from the starting point).'
complete -c blkdiscard -s p -l step --description 'The number of bytes to discard within one iteration.'
complete -c blkdiscard -s s -l secure --description 'Perform a secure discard.'
complete -c blkdiscard -s z -l zeroout --description 'Zero-fill rather than discard.'
complete -c blkdiscard -s v -l verbose --description 'Display the aligned values of  offset and R length .'
complete -c blkdiscard -s V -l version --description 'Display version information and exit.'
complete -c blkdiscard -s h -l help --description 'Display help text and exit.  AUTHOR.'

