# blkzone
# Autogenerated from man page /usr/share/man/man8/blkzone.8.gz
complete -c blkzone -s o -l offset --description 'The starting zone specified as a sector offset.'
complete -c blkzone -s l -l length --description 'The maximum number of sectors the command should operate on.'
complete -c blkzone -s c -l count --description 'The maximum number of zones the command should operate on.'
complete -c blkzone -s v -l verbose --description 'Display the number of zones returned in the report or the range of sectors re…'
complete -c blkzone -s V -l version --description 'Display version information and exit.'
complete -c blkzone -s h -l help --description 'Display help text and exit.  AUTHORS.'

