# bootctl
# Autogenerated from man page /usr/share/man/man1/bootctl.1.gz
complete -c bootctl -s h -l help --description 'Print a short help text and exit.'
complete -c bootctl -l version --description 'Print a short version string and exit.'
complete -c bootctl -l path --description 'Path to the EFI System Partition (ESP).'
complete -c bootctl -s p -l print-path --description 'This option modifies the behaviour of status.'
complete -c bootctl -l no-variables --description 'Do not touch the EFI boot variables.'

