# bridge
# Autogenerated from man page /usr/share/man/man8/bridge.8.gz
complete -c bridge -s V -o Version --description 'print the version of the  bridge utility and exit.'
complete -c bridge -s s -o stats -o statistics --description 'output more information.'
complete -c bridge -s d -o details --description 'print detailed information about MDB router ports.'
complete -c bridge -s n -o net -o netns --description 'switches  bridge to the specified network namespace R NETNS .'
complete -c bridge -s b -o batch --description 'Read commands from provided file or standard input and invoke them.'
complete -c bridge -o force --description 'Don\'t terminate bridge command on errors in batch mode.'
complete -c bridge -s c -o color --description 'Use color output.'
complete -c bridge -s j -o json --description 'Output results in JavaScript Object Notation (JSON).'
complete -c bridge -s p --description '.'
complete -c bridge -o pretty --description 'When combined with -j generate a pretty JSON output.  BRIDGE - COMMAND SYNTAX.'
complete -c bridge -s t -o timestamp --description 'display current time when using monitor option.'

