# broadwayd
# Autogenerated from man page /usr/share/man/man1/broadwayd.1.gz
complete -c broadwayd -l port --description 'Use PORT as the HTTP port, instead of the default 8080 + (DISPLAY - 1).'
complete -c broadwayd -l address --description 'Use ADDRESS as the HTTP address, instead of the default http://127. 0. 0.'
complete -c broadwayd -l unixsocket --description 'Use ADDRESS as the unix domain socket address.'

