# bunzip2
# Autogenerated from man page /usr/share/man/man1/bunzip2.1.gz
complete -c bunzip2 -s c -l stdout --description 'Compress or decompress to standard output.'
complete -c bunzip2 -s d -l decompress --description 'Force decompression.'
complete -c bunzip2 -s z -l compress --description 'The complement to -d: forces compression, regardless of the invocation name.'
complete -c bunzip2 -s t -l test --description 'Check integrity of the specified file(s), but don\'t decompress them.'
complete -c bunzip2 -s f -l force --description 'Force overwrite of output files.'
complete -c bunzip2 -s k -l keep --description 'Keep (don\'t delete) input files during compression or decompression.'
complete -c bunzip2 -s s -l small --description 'Reduce memory usage, for compression, decompression and testing.'
complete -c bunzip2 -s q -l quiet --description 'Suppress non-essential warning messages.'
complete -c bunzip2 -s v -l verbose --description 'Verbose mode -- show the compression ratio for each file processed.'
complete -c bunzip2 -s L -l license -s V -l version --description 'Display the software version, license terms and conditions.'
complete -c bunzip2 -s 1 -l fast -s 9 -l best --description 'Set the block size to 100 k, 200 k .   900 k when compressing.'
complete -c bunzip2 -l repetitive-fast -l repetitive-best --description 'These flags are redundant in versions 0. 9. 5 and above.'
complete -c bunzip2 -o vvvv --description '.'

