# bvnc
# Autogenerated from man page /usr/share/man/man1/bvnc.1.gz
complete -c bvnc -s s -l ssh --description 'Browse for SSH servers (and only SSH servers) regardless under which name the…'
complete -c bvnc -s v -l vnc --description 'Browse for VNC servers (and only VNC servers) regardless under which name the…'
complete -c bvnc -s S -l shell --description 'Browse for both VNC and SSH servers regardless under which name the binary is…'
complete -c bvnc -s d -l domain --description 'Browse in the specified domain.'
complete -c bvnc -s h -l help --description 'Show help.'

