# CA
# Autogenerated from man page /usr/share/man/man1/CA.pl.1ssl.gz
complete -c CA -s h -o help --description 'prints a usage message.'
complete -c CA -o newcert --description 'creates a new self signed certificate.'
complete -c CA -o newreq --description 'creates a new certificate request.'
complete -c CA -o newreq-nodes --description 'is like -newreq except that the private key will not be encrypted.'
complete -c CA -o newca --description 'creates a new \\s-1CA\\s0 hierarchy for use with the ca program (or the -signce…'
complete -c CA -o pkcs12 --description 'create a PKCS#12 file containing the user certificate, private key and \\s-1CA…'
complete -c CA -o sign -o signcert -o xsign --description 'calls the ca program to sign a certificate request.'
complete -c CA -o signCA --description 'this option is the same as the -signreq option except it uses the configurati…'
complete -c CA -o crl --description 'generate a \\s-1CRL. \\s0 Executes openssl ca command.'
complete -c CA -o revoke --description 'revoke the certificate contained in the specified certfile.'
complete -c CA -o verify --description 'verifies certificates against the \\s-1CA\\s0 certificate for \\*(L"demoCA\\*(R".'

