# cache_dump
# Autogenerated from man page /usr/share/man/man8/cache_dump.8.gz
complete -c cache_dump -s h -l help --description 'Print help and exit.'
complete -c cache_dump -s V -l version --description 'Print version information and exit.'
complete -c cache_dump -s r -l repair --description 'Repair the metadata whilst dumping it.'
complete -c cache_dump -s o --description 'Specify an output file for the xml, rather than printing to stdout.'

