# cache_writeback
# Autogenerated from man page /usr/share/man/man8/cache_writeback.8.gz
complete -c cache_writeback -s h -l help --description 'Print help and exit.'
complete -c cache_writeback -s V -l version --description 'Print version information and exit.'
complete -c cache_writeback -l metadata-device --description 'Location of cache metadata.'
complete -c cache_writeback -l origin-device --description 'Slow device being cached.'
complete -c cache_writeback -l fast-device --description 'Fast device containing the data that needs to be written back.'
complete -c cache_writeback -l no-metadata-update --description 'Do not update the metadata to clear the dirty flags. PP . nf .'
complete -c cache_writeback -l buffer-size-meg --description 'Specify the size for the metadata cache. PP . nf .'
complete -c cache_writeback -l list-failed-blocks --description 'List any blocks that failed the writeback process.'

