# capsh
# Autogenerated from man page /usr/share/man/man1/capsh.1.gz
complete -c capsh -l print --description 'Display prevailing capability and related state.'
complete -c capsh -l caps --description 'Set the prevailing process capabilities to those specified by R cap-set .'
complete -c capsh -l drop --description 'Remove the listed capabilities from the prevailing bounding set.'
complete -c capsh -l inh --description 'Set the inheritable set of capabilities for the current process to equal thos…'
complete -c capsh -l user --description 'Assume the identity of the named user.'
complete -c capsh -l uid --description 'Force all  uid values to equal  id using the  setuid (2) system call.'
complete -c capsh -l gid --description 'Force all  gid values to equal  id using the  setgid (2) system call.'
complete -c capsh -l groups --description 'Set the supplementary groups to the numerical list provided.'
complete -c capsh -l keep --description 'In a non-pure capability mode, the kernel provides liberal privilege to the s…'
complete -c capsh -l secbits --description 'XXX - need to document this feature.'
complete -c capsh -l chroot --description 'Execute the  chroot (2) system call with the new root-directory (/) equal to …'
complete -c capsh -l decode --description 'This is a convenience feature.'
complete -c capsh -l supports --description 'As the kernel evolves, more capabilities are added.'
complete -c capsh -s c --description 'for specific commands.'
complete -c capsh -l forkfor --description '.'
complete -c capsh -l killit --description '.'

