# catman
# Autogenerated from man page /usr/share/man/man8/catman.8.gz
complete -c catman -s d -l debug --description 'Print debugging information.'
complete -c catman -s M -l manpath --description 'Specify an alternate colon-delimited manual page hierarchy search path.'
complete -c catman -s C -l config-file --description 'Use this user configuration file rather than the default of R ~/. manpath .'
complete -c catman -s '?' -l help --description 'Print a help message and exit.'
complete -c catman -l usage --description 'Print a short usage message and exit.'
complete -c catman -s V -l version --description 'Display version information.  ENVIRONMENT.'

