# cd-create-profile
# Autogenerated from man page /usr/share/man/man1/cd-create-profile.1.gz
complete -c cd-create-profile -l help --description 'Show summary of options.'
complete -c cd-create-profile -l description --description 'Sets the profile description.'
complete -c cd-create-profile -l copyright --description 'Sets the profile copyright.'
complete -c cd-create-profile -l model --description 'Sets the profile model.'
complete -c cd-create-profile -l manufacturer --description 'Sets the profile manufacturer.'
complete -c cd-create-profile -l srgb-palette --description 'Specifies a comma seporated values file that is used for the named color.'
complete -c cd-create-profile -l output --description 'Specifies the output ICC filename.'
complete -c cd-create-profile -l nc-prefix --description 'Specifies the named color palette prefix.'

