# certtool
# Autogenerated from man page /usr/share/man/man1/certtool.1.gz
complete -c certtool -l generate-privkey -l generate-dh-params --description '.'
complete -c certtool -l load-ca-certificate --description '$ certtool --load-ca-certificate ca. pem    --load-certificate cert.'

