# cfdisk
# Autogenerated from man page /usr/share/man/man8/cfdisk.8.gz
complete -c cfdisk -s h -l help --description 'Display help text and exit.'
complete -c cfdisk -s L -l color --description 'Colorize the output.'
complete -c cfdisk -s V -l version --description 'Display version information and exit.'
complete -c cfdisk -s z -l zero --description 'Start with an in-memory zeroed partition table.'

