# chacl
# Autogenerated from man page /usr/share/man/man1/chacl.1.gz
complete -c chacl -s b --description 'Indicates that there are two ACLs to change, the first is the file access ACL…'
complete -c chacl -s d --description 'Used to set only the default ACL of a directory.'
complete -c chacl -s R --description 'Removes the file access ACL only.'
complete -c chacl -s D --description 'Removes directory default ACL only.'
complete -c chacl -s B --description 'Remove all ACLs.'
complete -c chacl -s l --description 'Lists the access ACL and possibly the default ACL associated with the specifi…'
complete -c chacl -s r --description 'Set the access ACL recursively for each subtree rooted at pathname(s).'

