# chattr
# Autogenerated from man page /usr/share/man/man1/chattr.1.gz
complete -c chattr -s R --description 'Recursively change attributes of directories and their contents.'
complete -c chattr -s V --description 'Be verbose with chattr\'s output and print the program version.'
complete -c chattr -s f --description 'Suppress most error messages.'
complete -c chattr -s v --description 'Set the file\'s version/generation number.'
complete -c chattr -s p --description 'Set the file\'s project number.'

