# chcon
# Autogenerated from man page /usr/share/man/man1/chcon.1.gz
complete -c chcon -l dereference --description 'affect the referent of each symbolic link (this is the default), rather than …'
complete -c chcon -s h -l no-dereference --description 'affect symbolic links instead of any referenced file.'
complete -c chcon -s u -l user --description 'set user USER in the target security context.'
complete -c chcon -s r -l role --description 'set role ROLE in the target security context.'
complete -c chcon -s t -l type --description 'set type TYPE in the target security context.'
complete -c chcon -s l -l range --description 'set range RANGE in the target security context.'
complete -c chcon -l no-preserve-root --description 'do not treat \'/\' specially (the default).'
complete -c chcon -l preserve-root --description 'fail to operate recursively on \'/\'.'
complete -c chcon -l reference --description 'use RFILE\'s security context rather than specifying a CONTEXT value.'
complete -c chcon -s R -l recursive --description 'operate on files and directories recursively.'
complete -c chcon -s v -l verbose --description 'output a diagnostic for every file processed .'
complete -c chcon -s H --description 'if a command line argument is a symbolic link to a directory, traverse it.'
complete -c chcon -s L --description 'traverse every symbolic link to a directory encountered.'
complete -c chcon -s P --description 'do not traverse any symbolic links (default).'
complete -c chcon -l help --description 'display this help and exit.'
complete -c chcon -l version --description 'output version information and exit AUTHOR Written by Russell Coker and Jim M…'

