# chfn
# Autogenerated from man page /usr/share/man/man1/chfn.1.gz
complete -c chfn -s f -l full-name --description 'Specify your real name.'
complete -c chfn -s o -l office --description 'Specify your office room number.'
complete -c chfn -s p -l office-phone --description 'Specify your office phone number.'
complete -c chfn -s h -l home-phone --description 'Specify your home phone number.'
complete -c chfn -s u -l help --description 'Display help text and exit.'
complete -c chfn -s v -l version --description 'Display version information and exit.'

