# chgrp
# Autogenerated from man page /usr/share/man/man1/chgrp.1.gz
complete -c chgrp -s c -l changes --description 'like verbose but report only when a change is made.'
complete -c chgrp -s f -l silent -l quiet --description 'suppress most error messages.'
complete -c chgrp -s v -l verbose --description 'output a diagnostic for every file processed.'
complete -c chgrp -l dereference --description 'affect the referent of each symbolic link (this is the default), rather than …'
complete -c chgrp -s h -l no-dereference --description 'affect symbolic links instead of any referenced file (useful only on systems …'
complete -c chgrp -l no-preserve-root --description 'do not treat \'/\' specially (the default).'
complete -c chgrp -l preserve-root --description 'fail to operate recursively on \'/\'.'
complete -c chgrp -l reference --description 'use RFILE\'s group rather than specifying a GROUP value.'
complete -c chgrp -s R -l recursive --description 'operate on files and directories recursively .'
complete -c chgrp -s H --description 'if a command line argument is a symbolic link to a directory, traverse it.'
complete -c chgrp -s L --description 'traverse every symbolic link to a directory encountered.'
complete -c chgrp -s P --description 'do not traverse any symbolic links (default).'
complete -c chgrp -l help --description 'display this help and exit.'
complete -c chgrp -l version --description 'output version information and exit EXAMPLES.'

