# chmod
# Autogenerated from man page /usr/share/man/man1/chmod.1p.gz
complete -c chmod -s l --description 'file writes an s in the position indicating that the set-user-ID-on-execution…'
complete -c chmod -s g --description '(that is, set the ``other\'\' permissions to the permissions of ``owner\'\' minus…'

