# chpasswd
# Autogenerated from man page /usr/share/man/man8/chpasswd.8.gz
complete -c chpasswd -s c -l crypt-methodMETHOD --description 'Use the specified method to encrypt the passwords.'
complete -c chpasswd -s e -l encrypted --description 'Supplied passwords are in encrypted form.'
complete -c chpasswd -s h -l help --description 'Display help message and exit.'
complete -c chpasswd -s m -l md5 --description 'Use MD5 encryption instead of DES when the supplied passwords are not encrypt…'
complete -c chpasswd -s R -l rootCHROOT_DIR --description 'Apply changes in the CHROOT_DIR directory and use the configuration files fro…'
complete -c chpasswd -s s -l sha-roundsROUNDS --description 'Use the specified number of rounds to encrypt the passwords.'
complete -c chpasswd -l crypt-method --description '.'
complete -c chpasswd -l root --description '.'
complete -c chpasswd -l sha-rounds --description '.'

