# chroot
# Autogenerated from man page /usr/share/man/man1/chroot.1.gz
complete -c chroot -l groups --description 'specify supplementary groups as g1,g2,. ,gN.'
complete -c chroot -l userspec --description 'specify user and group (ID or name) to use.'
complete -c chroot -l skip-chdir --description 'do not change working directory to \'/\'.'
complete -c chroot -l help --description 'display this help and exit.'
complete -c chroot -l version --description 'output version information and exit.'

