# chromium
# Autogenerated from man page /usr/share/man/man1/chromium.1.gz
complete -c chromium -l user-data-dir --description 'Specifies the directory that user data (your "profile") is kept in.'
complete -c chromium -l app --description 'Runs  URL in "app mode": with no browser toolbars.'
complete -c chromium -l incognito --description 'Open in incognito mode.'
complete -c chromium -l new-window --description 'If PATH or URL is given, open it in a new window.'
complete -c chromium -l proxy-server --description 'Specify the HTTP/SOCKS4/SOCKS5 proxy server to use for requests.'
complete -c chromium -l no-proxy-server --description 'Disables the proxy server.'
complete -c chromium -l proxy-auto-detect --description 'Autodetect proxy configuration.'
complete -c chromium -l proxy-pac-url --description 'Specify proxy autoconfiguration URL.'
complete -c chromium -l password-store --description 'Set the password store to use.'
complete -c chromium -l version --description 'Show version information.'
complete -c chromium -l display --description 'See the GTK documentation for more: <http://library. gnome.'

