# ciphers
# Autogenerated from man page /usr/share/man/man1/ciphers.1ssl.gz
complete -c ciphers -o help --description 'Print a usage message.'
complete -c ciphers -s s --description 'Only list supported ciphers: those consistent with the security level, and mi…'
complete -c ciphers -o psk --description 'When combined with -s includes cipher suites which require \\s-1PSK. \\s0.'
complete -c ciphers -o srp --description 'When combined with -s includes cipher suites which require \\s-1SRP. \\s0.'
complete -c ciphers -s v --description 'Verbose output: For each ciphersuite, list details as provided by SSL_CIPHER_…'
complete -c ciphers -s V --description 'Like -v, but include the official cipher suite values in hex.'
complete -c ciphers -o tls1_2 --description 'In combination with the -s option, list the ciphers which would be used if TL…'
complete -c ciphers -o ssl3 --description 'In combination with the -s option, list the ciphers which would be used if SS…'
complete -c ciphers -o tls1 --description 'In combination with the -s option, list the ciphers which would be used if TL…'
complete -c ciphers -o tls1_1 --description 'In combination with the -s option, list the ciphers which would be used if TL…'
complete -c ciphers -o stdname --description 'precede each ciphersuite by its standard name: only available is OpenSSL is b…'

