# cksum
# Autogenerated from man page /usr/share/man/man1/cksum.1.gz
complete -c cksum -l help --description 'display this help and exit.'
complete -c cksum -l version --description 'output version information and exit AUTHOR Written by Q.  Frank Xia.'

