# compress
# Autogenerated from man page /usr/share/man/man1/compress.1p.gz
complete -c compress -s b --description 'Specify the maximum number of bits to use in a code.'
complete -c compress -s c --description 'Cause compress to write to the standard output; the input file is not changed…'
complete -c compress -s f --description 'Force compression of file , even if it does not actually reduce the size of t…'
complete -c compress -s v --description 'Write the percentage reduction of each file to standard error.'

