# config
# Autogenerated from man page /usr/share/man/man1/config.guess.1.gz
complete -c config -s h -l help --description 'print this help, then exit.'
complete -c config -s t -l time-stamp --description 'print date of last modification, then exit.'
complete -c config -s v -l version --description 'print version number, then exit ENVIRONMENT VARIABLES config.'

