# crontab
# Autogenerated from man page /usr/share/man/man1/crontab.1p.gz
complete -c crontab -s e --description 'is specified.'
complete -c crontab -s l --description '(The letter ell. ) List the invoking user\'s crontab entry.'
complete -c crontab -s r --description 'Remove the invoking user\'s crontab entry.'

