# cut
# Autogenerated from man page /usr/share/man/man1/cut.1p.gz
complete -c cut -s 5 --description 'Equivalent to 1,2,3,4,5,10.  3- 8 Equivalent to third to last, inclusive.'
complete -c cut -s o --description 'Preserve the selected field order.'

