# cxref
# Autogenerated from man page /usr/share/man/man1/cxref.1p.gz
complete -c cxref -s c --description 'option, in combination.'
complete -c cxref -s D --description '.'
complete -c cxref -s I --description 'and.'
complete -c cxref -s U --description 'options (which are identical to their interpretation by c99 ) is significant.'
complete -c cxref -s s --description 'Operate silently; do not print input filenames.'
complete -c cxref -s o --description 'Direct output to named file .'
complete -c cxref -s w --description 'Format output no wider than num (decimal) columns.'

