# dbus-launch
# Autogenerated from man page /usr/share/man/man1/dbus-launch.1.gz
complete -c dbus-launch -l auto-syntax --description 'Choose --csh-syntax or --sh-syntax based on the SHELL environment variable.'
complete -c dbus-launch -l binary-syntax --description 'Write to stdout a nul-terminated bus address, then the bus PID as a binary in…'
complete -c dbus-launch -l close-stderr --description 'Close the standard error output stream before starting the D-Bus daemon.'
complete -c dbus-launch -l config-file --description 'Pass --config-file=FILENAME to the bus daemon, instead of passing it the --se…'
complete -c dbus-launch -l csh-syntax --description 'Emit csh compatible code to set up environment variables.'
complete -c dbus-launch -l exit-with-x11 --description 'If this option is provided, a persistent "babysitter" process will be created…'
complete -c dbus-launch -l exit-with-session --description 'If this option is provided, a persistent "babysitter" process will be created…'
complete -c dbus-launch -l autolaunch --description 'This option implies that dbus-launch should scan for a previously-started ses…'
complete -c dbus-launch -l sh-syntax --description 'Emit Bourne-shell compatible code to set up environment variables.'
complete -c dbus-launch -l version --description 'Print the version of dbus-launch.'
complete -c dbus-launch -l help --description 'Print the help info of dbus-launch.'

