# dbus-run-session
# Autogenerated from man page /usr/share/man/man1/dbus-run-session.1.gz
complete -c dbus-run-session -l config-file -l config-file --description 'Pass --config-file=FILENAME to the bus daemon, instead of passing it the --se…'
complete -c dbus-run-session -l dbus-daemon -l dbus-daemon --description 'Run BINARY as dbus-daemon(1), instead of searching the PATH in the usual way …'
complete -c dbus-run-session -l help --description 'Print usage information and exit.'
complete -c dbus-run-session -l version --description 'Print the version of dbus-run-session and exit.'
complete -c dbus-run-session -l session --description 'argument.  See dbus-daemon(1).'

