# dbus-uuidgen
# Autogenerated from man page /usr/share/man/man1/dbus-uuidgen.1.gz
complete -c dbus-uuidgen -l get --description 'If a filename is not given, defaults to localstatedir/lib/dbus/machine-id (lo…'
complete -c dbus-uuidgen -l ensure --description 'If a filename is not given, defaults to localstatedir/lib/dbus/machine-id (lo…'
complete -c dbus-uuidgen -l version --description 'Print the version of dbus-uuidgen.'

