# dd
# Autogenerated from man page /usr/share/man/man1/dd.1.gz
complete -c dd -l help --description 'display this help and exit.'
complete -c dd -l version --description 'output version information and exit AUTHOR Written by Paul Rubin, David MacKe…'

