# debugfs
# Autogenerated from man page /usr/share/man/man8/debugfs.reiserfs.8.gz
complete -c debugfs -s j --description 'prints the contents of the journal.'
complete -c debugfs -s J --description 'prints the journal header.'
complete -c debugfs -s m --description 'prints the contents of the bitmap (slightly useful).'
complete -c debugfs -s B --description 'takes the list of bad blocks stored in the internal ReiserFS tree and transla…'
complete -c debugfs -s 1 --description 'prints the specified block of the filesystem.'
complete -c debugfs -s u --description 'builds the ReiserFS filesystem image with gunzip -c xxx.'
complete -c debugfs -s q --description 'When .'

