# depmod
# Autogenerated from man page /usr/share/man/man8/depmod.8.gz
complete -c depmod -s a -l all --description 'Probe all modules.'
complete -c depmod -s A -l quick --description 'This option scans to see if any modules are newer than the modules.'
complete -c depmod -s b -l basedir --description 'If your modules are not currently in the (normal) directory /lib/modules/vers…'
complete -c depmod -s C -l config --description 'This option overrides the default configuration directory at /etc/depmod. d/.'
complete -c depmod -s e -l errsyms --description 'When combined with the -F option, this reports any symbols which a module nee…'
complete -c depmod -s E -l symvers --description 'When combined with the -e option, this reports any symbol versions supplied b…'
complete -c depmod -s F -l filesyms --description 'Supplied with the System.'
complete -c depmod -s h -l help --description 'Print the help message and exit.'
complete -c depmod -s n -l show -l dry-run --description 'This sends the resulting modules.'
complete -c depmod -s P --description 'Some architectures prefix symbols with an extraneous character.'
complete -c depmod -s v -l verbose --description 'In verbose mode, depmod will print (to stdout) all the symbols each module de…'
complete -c depmod -s V -l version --description 'Show version of program and exit.'
complete -c depmod -s w --description 'Warn on duplicate dependencies, aliases, symbol versions, etc.'

