# desktop-file-validate
# Autogenerated from man page /usr/share/man/man1/desktop-file-validate.1.gz
complete -c desktop-file-validate -l no-hints --description 'Do not output hints about things that might be improved in the desktop file.'
complete -c desktop-file-validate -l no-warn-deprecated --description 'Do not warn about usage of deprecated items that were defined in previous ver…'
complete -c desktop-file-validate -l warn-kde --description 'Warn about usage of KDE extensions to the specification.'

