# devlink-dev
# Autogenerated from man page /usr/share/man/man8/devlink-dev.8.gz
complete -c devlink-dev -s V --description '.'
complete -c devlink-dev -s n --description 'devlink dev show [  DEV  ] devlink dev help devlink dev eswitch set DEV [  mo…'

