# devlink-port
# Autogenerated from man page /usr/share/man/man8/devlink-port.8.gz
complete -c devlink-port -s V --description '.'
complete -c devlink-port -s n --description 'devlink port set  DEV/PORT_INDEX [  type  {  eth  |  ib  |  auto  } ] devlink…'

