# devlink-resource
# Autogenerated from man page /usr/share/man/man8/devlink-resource.8.gz
complete -c devlink-resource -s v --description 'devlink resource show DEV devlink resource help devlink resource set DEV path…'

