# devlink
# Autogenerated from man page /usr/share/man/man8/devlink.8.gz
complete -c devlink -s V -l Version --description 'Print the version of the  devlink utility and exit.'
complete -c devlink -s b -o batch --description 'Read commands from provided file or standard input and invoke them.'
complete -c devlink -o force --description 'Don\'t terminate devlink on errors in batch mode.'
complete -c devlink -s n -l no-nice-names --description 'Turn off printing out nice names, for example netdevice ifnames instead of de…'
complete -c devlink -s j -l json --description 'Generate JSON output.'
complete -c devlink -s p -l pretty --description 'When combined with -j generate a pretty JSON output. SS  OBJECT.'

