# diff3
# Autogenerated from man page /usr/share/man/man1/diff3.1.gz
complete -c diff3 -s A -l show-all --description 'output all changes, bracketing conflicts.'
complete -c diff3 -s e -l ed --description 'output ed script incorporating changes from OLDFILE to YOURFILE into MYFILE.'
complete -c diff3 -s E -l show-overlap --description 'like -e, but bracket conflicts.'
complete -c diff3 -s 3 -l easy-only --description 'like -e, but incorporate only nonoverlapping changes.'
complete -c diff3 -s x -l overlap-only --description 'like -e, but incorporate only overlapping changes.'
complete -c diff3 -s X --description 'like -x, but bracket conflicts.'
complete -c diff3 -s i --description 'append \'w\' and \'q\' commands to ed scripts.'
complete -c diff3 -s m -l merge --description 'output actual merged file, according to -A if no other options are given.'
complete -c diff3 -s a -l text --description 'treat all files as text.'
complete -c diff3 -l strip-trailing-cr --description 'strip trailing carriage return on input.'
complete -c diff3 -s T -l initial-tab --description 'make tabs line up by prepending a tab.'
complete -c diff3 -l diff-program --description 'use PROGRAM to compare files.'
complete -c diff3 -s L -l label --description 'use LABEL instead of file name (can be repeated up to three times).'
complete -c diff3 -l help --description 'display this help and exit.'
complete -c diff3 -s v -l version --description 'output version information and exit.'

