# dsaparam
# Autogenerated from man page /usr/share/man/man1/dsaparam.1ssl.gz
complete -c dsaparam -o help --description 'Print out a usage message.'
complete -c dsaparam -o inform --description 'This specifies the input format.'
complete -c dsaparam -o outform --description 'This specifies the output format, the options have the same meaning as the -i…'
complete -c dsaparam -o in --description 'This specifies the input filename to read parameters from or standard input i…'
complete -c dsaparam -o out --description 'This specifies the output filename parameters to.'
complete -c dsaparam -o noout --description 'this option inhibits the output of the encoded version of the parameters.'
complete -c dsaparam -o text --description 'this option prints out the \\s-1DSA\\s0 parameters in human readable form.'
complete -c dsaparam -s C --description 'this option converts the parameters into C code.'
complete -c dsaparam -o genkey --description 'this option will generate a \\s-1DSA\\s0 either using the specified or generate…'
complete -c dsaparam -o rand --description 'a file or files containing random data used to seed the random number generat…'

