# dumpe2fs
# Autogenerated from man page /usr/share/man/man8/dumpe2fs.8.gz
complete -c dumpe2fs -s b --description 'print the blocks which are reserved as bad in the filesystem.'
complete -c dumpe2fs -s o --description 'use the block  superblock when examining the filesystem.'
complete -c dumpe2fs -s f --description 'force dumpe2fs to display a filesystem even though it may have some filesyste…'
complete -c dumpe2fs -s g --description 'display the group descriptor information in a machine readable colon-separate…'
complete -c dumpe2fs -s h --description 'only display the superblock information and not any of the block group descri…'
complete -c dumpe2fs -s i --description 'display the filesystem data from an image file created by  e2image , using  d…'
complete -c dumpe2fs -s x --description 'print the detailed group information block numbers in hexadecimal format.'
complete -c dumpe2fs -s V --description 'print the version number of dumpe2fs and exit.'

