# dumpiso
# Autogenerated from man page /usr/share/man/man1/dumpiso.1.gz
complete -c dumpiso -s c -l channels --description 'Sets the channels to listen on.'
complete -c dumpiso -s p -l port --description 'Choose port PORT for receiving.'
complete -c dumpiso -s h -l help --description 'Show help text and exit.'

