# dvb-fe-tool
# Autogenerated from man page /usr/share/man/man1/dvb-fe-tool.1.gz
complete -c dvb-fe-tool -s 3 -l dvbv3 --description 'Use DVBv3 only.'
complete -c dvb-fe-tool -s a -l adapter --description 'Digital TV adapter to use.  Default: 0.'
complete -c dvb-fe-tool -s A -l acoustical --description 'beeps if signal quality is good.  Also enables femon mode.'
complete -c dvb-fe-tool -s d -l set-delsys --description 'Sets delivery system to the one specified at PARAMS.'
complete -c dvb-fe-tool -s f -l frontend --description 'Digital TV frontend to use.  Default: 0.'
complete -c dvb-fe-tool -s g -l get --description 'Gets frontend parameters.'
complete -c dvb-fe-tool -s m -l femon --description 'Monitors the frontend locking status and the available statistics for a front…'
complete -c dvb-fe-tool -s v -l verbose --description 'Enables debug messages.'
complete -c dvb-fe-tool -s '?' -l help --description 'Outputs the usage help.'
complete -c dvb-fe-tool -l usage --description 'Gives a short usage message.'
complete -c dvb-fe-tool -s V -l version --description 'Prints program version.  EXIT STATUS On success, it returns 0.  EXAMPLES.'

