# dvb-format-convert
# Autogenerated from man page /usr/share/man/man1/dvb-format-convert.1.gz
complete -c dvb-format-convert -s I -l input-format --description 'Format of the input file.  Supported input formats: channel\\f, zap and dvbv5.'
complete -c dvb-format-convert -s O -l output-format --description 'Format of the output file.'
complete -c dvb-format-convert -s s -l delsys --description 'Delivery system type.  Needed if input or output format is ZAP.'
complete -c dvb-format-convert -s '?' -l help --description 'Outputs the usage help.'
complete -c dvb-format-convert -l usage --description 'Give a short usage message.'
complete -c dvb-format-convert -s V -l version --description 'Print program version.  EXAMPLES.'

