# e2freefrag
# Autogenerated from man page /usr/share/man/man8/e2freefrag.8.gz
complete -c e2freefrag -s c --description 'If a chunk size is specified, then  e2freefrag will print how many free chunk…'
complete -c e2freefrag -s h --description 'Print the usage of the program.  EXAMPLE # e2freefrag /dev/vgroot/lvhome.'

