# echo
# Autogenerated from man page /usr/share/man/man1/echo.1.gz
complete -c echo -s n --description 'do not output the trailing newline.'
complete -c echo -s e --description 'enable interpretation of backslash escapes.'
complete -c echo -s E --description 'disable interpretation of backslash escapes (default).'
complete -c echo -l help --description 'display this help and exit.'
complete -c echo -l version --description 'output version information and exit .'

