# ed
# Autogenerated from man page /usr/share/man/man1/ed.1p.gz
complete -c ed -s p --description 'Use string as the prompt string when in command mode.'
complete -c ed -s s --description 'Suppress the writing of byte counts by e , E , r , and w commands and of the …'
complete -c ed -s 2 --description 'Two lines before the current line.'

