# enchant-2
# Autogenerated from man page /usr/share/man/man1/enchant-2.1.gz
complete -c enchant-2 -s a --description 'List suggestions in ispell pipe mode format.'
complete -c enchant-2 -s d --description 'Use the given dictionary.'
complete -c enchant-2 -s h --description 'Show short help.'
complete -c enchant-2 -s l --description 'List only the misspellings.'
complete -c enchant-2 -s L --description 'Include the line number in the output.'
complete -c enchant-2 -s v --description 'Prints the program\'s version.'

