# era_restore
# Autogenerated from man page /usr/share/man/man8/era_restore.8.gz
complete -c era_restore -s h -l help --description 'Print help and exit.'
complete -c era_restore -s V -l version --description 'Print version information and exit.'
complete -c era_restore -s q -l quiet --description 'Don\'t print any output.   Check the exit code to test for success.'
complete -c era_restore -s i -l input --description 'Specify input file containing xml metadata.'
complete -c era_restore -s o -l output --description 'Output device or file for restored binary metadata.'

