# era_check
# Autogenerated from man page /usr/share/man/man8/era_check.8.gz
complete -c era_check -s h -l help --description 'Print help and exit.'
complete -c era_check -s V -l version --description 'Print version information and exit.'
complete -c era_check -s q -l quiet --description 'Suppress output messages, return only exit code.'
complete -c era_check -l super-block-only --description 'Only check the superblock is present.'

