# era_invalidate
# Autogenerated from man page /usr/share/man/man8/era_invalidate.8.gz
complete -c era_invalidate -s h -l help --description 'Print help and exit.'
complete -c era_invalidate -s V -l version --description 'Print version information and exit.'
complete -c era_invalidate -s o --description 'Write output to a file rather than stdout.'
complete -c era_invalidate -l metadata-snapshot --description 'Use the metadata snapshot rather than the current superblock.'
complete -c era_invalidate -l written-since --description 'Blocks written since the given era will be listed.'

