# ex
# Autogenerated from man page /usr/share/man/man1/ex.1p.gz
complete -c ex -s 1 --description 'addr1 ,c addr2 ,c addr2 + count.'
complete -c ex -s i --description '(interactive mode).  Editing shall be resumed when the program exits.'
complete -c ex -s m --description '.'
complete -c ex -s e --description 'option of sed .'
complete -c ex -s x --description 'option, which did encryption based on the algorithm found in the historical c…'
complete -c ex -s 2 --description 'Two lines before the current line.'

