# faillog
# Autogenerated from man page /usr/share/man/man8/faillog.8.gz
complete -c faillog -s a -l all --description 'Display (or act on) faillog records for all users having an entry in the fail…'
complete -c faillog -s h -l help --description 'Display help message and exit.'
complete -c faillog -s l -l lock-secsSEC --description 'Lock account for SEC seconds after failed login.'
complete -c faillog -s m -l maximumMAX --description 'Set the maximum number of login failures after the account is disabled to MAX.'
complete -c faillog -s r -l reset --description 'Reset the counters of login failures.'
complete -c faillog -s R -l rootCHROOT_DIR --description 'Apply changes in the CHROOT_DIR directory and use the configuration files fro…'
complete -c faillog -s t -l timeDAYS --description 'Display faillog records more recent than DAYS.'
complete -c faillog -s u -l userLOGIN --description 'Display faillog record or maintains failure counters and limits (if used with…'
complete -c faillog -l lock-secs --description '.'
complete -c faillog -l maximum --description '.'
complete -c faillog -l root --description '.'
complete -c faillog -l time --description '.'
complete -c faillog -l user --description '.'

