# faked
# Autogenerated from man page /usr/share/man/man1/faked.1.gz
complete -c faked -l debug --description 'Print debugging information on stderr.'
complete -c faked -l foreground --description 'Don\'t fork into the background.'
complete -c faked -l cleanup --description 'Cleanup the semaphores.'
complete -c faked -l key --description 'Don\'t allocate a new communication channel, but use channel specified by key.'
complete -c faked -l save-file --description 'Save the environment to save-file on exit.'
complete -c faked -l load --description 'Load a previously saved environment from the standard input.'
complete -c faked -l unknown-is-real --description 'Use real ownership of previously-unknown files instead of setting them to roo…'
complete -c faked -l port --description 'Use TCP port tcp-port.'

