# fallocate
# Autogenerated from man page /usr/share/man/man1/fallocate.1.gz
complete -c fallocate -s c -l collapse-range --description 'Removes a byte range from a file, without leaving a hole.'
complete -c fallocate -s d -l dig-holes --description 'Detect and dig holes.'
complete -c fallocate -s i -l insert-range --description 'Insert a hole of length bytes from offset, shifting existing data.'
complete -c fallocate -s l -l length --description 'Specifies the length of the range, in bytes.'
complete -c fallocate -s n -l keep-size --description 'Do not modify the apparent length of the file.'
complete -c fallocate -s o -l offset --description 'Specifies the beginning offset of the range, in bytes.'
complete -c fallocate -s p -l punch-hole --description 'Deallocates space (i. e.'
complete -c fallocate -s v -l verbose --description 'Enable verbose mode.'
complete -c fallocate -s x -l posix --description 'Enable POSIX operation mode.'
complete -c fallocate -s z -l zero-range --description 'Zeroes space in the byte range starting at offset and continuing for length b…'
complete -c fallocate -s V -l version --description 'Display version information and exit.'
complete -c fallocate -s h -l help --description 'Display help text and exit.  AUTHORS.'

