# fc-cat
# Autogenerated from man page /usr/share/man/man1/fc-cat.1.gz
complete -c fc-cat -s r -l recurse --description 'Recurse into subdirectories.'
complete -c fc-cat -s v -l verbose --description 'Be verbose.'
complete -c fc-cat -s h -l help --description 'Show summary of options.'

