# fc-list
# Autogenerated from man page /usr/share/man/man1/fc-list.1.gz
complete -c fc-list -s v -l verbose --description 'Print verbose output of the whole font pattern for each match, or elements if…'
complete -c fc-list -s f -l format --description 'Format output according to the format specifier format.'
complete -c fc-list -s q -l quiet --description 'Suppress all normal output.  returns 1 as the error code if no fonts matched.'
complete -c fc-list -s V -l version --description 'Show version of the program and exit.'
complete -c fc-list -s h -l help --description 'Show summary of options.'

