# fc
# Autogenerated from man page /usr/share/man/man1/fc.1p.gz
complete -c fc -s l --description 'option is not specified), the resulting lines shall be entered at the end of …'
complete -c fc -s e --description 'Use the editor named by editor to edit the commands.'
complete -c fc -s r --description 'with each command preceded by the command number.'
complete -c fc -s n --description 'Suppress command numbers when listing with.'
complete -c fc -s s --description '.'
complete -c fc -o number --description 'A negative decimal number representing the command that was executed number o…'

