# filecap
# Autogenerated from man page /usr/share/man/man8/filecap.8.gz
complete -c filecap -s a --description 'This tells the program to show all capabilities starting from the / directory.'
complete -c filecap -s d --description 'This dumps all capabilities for reference.'

