# filefrag
# Autogenerated from man page /usr/share/man/man8/filefrag.8.gz
complete -c filefrag -s B --description 'Force the use of the older FIBMAP ioctl instead of the FIEMAP ioctl for testi…'
complete -c filefrag -s b --description 'Use  blocksize in bytes for output instead of the filesystem blocksize.'
complete -c filefrag -s e --description 'Print output in extent format, even for block-mapped files.'
complete -c filefrag -s k --description 'Use 1024-byte blocksize for output (identical to \'-b 1024\').'
complete -c filefrag -s s --description 'Sync the file before requesting the mapping.'
complete -c filefrag -s v --description 'Be verbose when checking for file fragmentation.'
complete -c filefrag -s x --description 'Display mapping of extended attributes.'
complete -c filefrag -s X --description 'Display extent block numbers in hexadecimal format.'

