# fincore
# Autogenerated from man page /usr/share/man/man1/fincore.1.gz
complete -c fincore -s n -l noheadings --description 'Do not print a header line in status output.'
complete -c fincore -s b -l bytes --description 'Print the SIZE column in bytes rather than in a human-readable format.'
complete -c fincore -s o -l output --description 'Define output columns.'
complete -c fincore -s r -l raw --description 'Produce output in raw format.'
complete -c fincore -s J -l json --description 'Use JSON output format.'
complete -c fincore -s V -l version --description 'Display version information and exit.'
complete -c fincore -s h -l help --description 'Display help text and exit.  AUTHORS.'

