# find
# Autogenerated from man page /usr/share/man/man1/find.1p.gz
complete -c find -o nt --description 'extension to test : if [ -n "$(find file1 -prune -newer file2)" ]; then     p…'
complete -c find -s l --description 'option.  (In both System V and BSD, ls uses st_size for the.'
complete -c find -s s --description 'calculations.  This volume of POSIX. 1-2008 does not specify ls.'

