# fold
# Autogenerated from man page /usr/share/man/man1/fold.1.gz
complete -c fold -s b -l bytes --description 'count bytes rather than columns.'
complete -c fold -s s -l spaces --description 'break at spaces.'
complete -c fold -s w -l width --description 'use WIDTH columns instead of 80.'
complete -c fold -l help --description 'display this help and exit.'
complete -c fold -l version --description 'output version information and exit AUTHOR Written by David MacKenzie.'

