# fsadm
# Autogenerated from man page /usr/share/man/man8/fsadm.8.gz
complete -c fsadm -s e -l ext-offline --description '.'
complete -c fsadm -s f -l force --description '.'
complete -c fsadm -s h -l help --description '.'
complete -c fsadm -s n -l dry-run --description '.'
complete -c fsadm -s v -l verbose --description '.'
complete -c fsadm -s y -l yes --description '.'
complete -c fsadm -s c -l cryptresize --description '.'

