# gdbm_dump
# Autogenerated from man page /usr/share/man/man1/gdbm_dump.1.gz
complete -c gdbm_dump -s H -l format --description 'Select dump format.'
complete -c gdbm_dump -s h -l help --description 'Print a short usage summary.'
complete -c gdbm_dump -l usage --description 'Print a list of available options.'
complete -c gdbm_dump -s V -l version --description 'Print program version SEE ALSO gdbm_load (1), gdbmtool (1), gdbm (3).'

