# gdbus
# Autogenerated from man page /usr/share/man/man1/gdbus.1.gz
complete -c gdbus -l xml --description 'option is used, the returned introspection XML is printed, otherwise a parsed…'
complete -c gdbus -l recurse --description 'option can be used to introspect children (and their children and so on) and …'
complete -c gdbus -l only-properties --description 'option can be used to only print the interfaces with properties.  monitor.'
complete -c gdbus -l activate --description 'is specified, that bus name will be auto-started first.'
complete -c gdbus -l timeout --description 'to 0 to disable it: $ gdbus wait --session --timeout 30 org. bar. SomeName.'

