# gdiffmk
# Autogenerated from man page /usr/share/man/man1/gdiffmk.1.gz
complete -c gdiffmk -s a --description 'Use the  addmark for source lines not in  file1 but present in R file2 .'
complete -c gdiffmk -s B --description 'By default, the deleted texts marked by the  -D option end with an added trof…'
complete -c gdiffmk -s c --description 'Use the  changemark for changed source lines.  Default:  | .'
complete -c gdiffmk -s d --description 'Use the  deletemark for deleted source lines.  Default:  * .'
complete -c gdiffmk -s D --description 'Show the deleted portions from changed and deleted text.'
complete -c gdiffmk -s M --description 'Change the delimiting marks for the  -D option.'
complete -c gdiffmk -s x --description 'Use the  diffcmd command to perform the comparison of  file1 and R file2 .'
complete -c gdiffmk -l help --description 'Print a usage message on standard error output and exit.'

