# gdk-pixbuf-csource
# Autogenerated from man page /usr/share/man/man1/gdk-pixbuf-csource.1.gz
complete -c gdk-pixbuf-csource -l stream --description 'Generate pixbuf data stream (a single string containing a serialized GdkPixda…'
complete -c gdk-pixbuf-csource -l struct --description 'Generate GdkPixdata structure (needs the GdkPixdata structure definition from…'
complete -c gdk-pixbuf-csource -l macros --description 'Generate *_ROWSTRIDE, *_WIDTH, *_HEIGHT, *_BYTES_PER_PIXEL and *_RLE_PIXEL_DA…'
complete -c gdk-pixbuf-csource -l rle --description 'Enables run-length encoding for the generated pixel data (default).'
complete -c gdk-pixbuf-csource -l raw --description 'Disables run-length encoding for the generated pixel data.'
complete -c gdk-pixbuf-csource -l extern --description 'Generate extern symbols.'
complete -c gdk-pixbuf-csource -l static --description 'Generate static symbols (default).'
complete -c gdk-pixbuf-csource -l decoder --description 'Provide a *_RUN_LENGTH_DECODE(image_buf, rle_data, size, bpp) macro definitio…'
complete -c gdk-pixbuf-csource -l name --description 'Specifies the identifier name (prefix) for the generated variables or macros …'
complete -c gdk-pixbuf-csource -l build-list --description 'Enables (name, image) pair parsing mode.'
complete -c gdk-pixbuf-csource -s h -l help --description 'Print brief help and exit.'
complete -c gdk-pixbuf-csource -s v -l version --description 'Print version and exit.'
complete -c gdk-pixbuf-csource -l g-fatal-warnings --description 'Make warnings fatal (causes the program to abort).'

