# gencfu
# Autogenerated from man page /usr/share/man/man1/gencfu.1.gz
complete -c gencfu -s h -s '?' -l help --description 'Print help about usage and exit.'
complete -c gencfu -s V -l version --description 'Print the version of  gencfu and exit.'
complete -c gencfu -s c -l copyright --description 'Embeds the standard ICU copyright into the R output-file .'
complete -c gencfu -s v -l verbose --description 'Display extra informative messages during execution.'
complete -c gencfu -s d -l destdir --description 'Set the destination directory of the R output-file to R destination .'
complete -c gencfu -s i -l icudatadir --description 'Look for any necessary ICU data files in R directory .'
complete -c gencfu -s r -l rules --description 'The source file to read.'
complete -c gencfu -s w -l wsrules --description 'The whole script source file to read.'
complete -c gencfu -s o -l out --description 'The output data file to write.  VERSION 1.'

