# gendict
# Autogenerated from man page /usr/share/man/man1/gendict.1.gz
complete -c gendict -s h -s '?' -l help --description 'Print help about usage and exit.'
complete -c gendict -s V -l version --description 'Print the version of  gendict and exit.'
complete -c gendict -s c -l copyright --description 'Embeds the standard ICU copyright into the R output-file .'
complete -c gendict -s v -l verbose --description 'Display extra informative messages during execution.'
complete -c gendict -s i -l icudatadir --description 'Look for any necessary ICU data files in R directory .'
complete -c gendict -l uchars --description 'Set the output trie type to UChar.  Mutually exclusive with  --bytes.'
complete -c gendict -l bytes --description 'Set the output trie type to Bytes.  Mutually exclusive with   --uchars.'
complete -c gendict -l transform --description 'Set the transform type.  Should only be specified with  --bytes.'

