# genl
# Autogenerated from man page /usr/share/man/man8/genl.8.gz
complete -c genl -s h -o help --description 'Show summary of options.'
complete -c genl -s V -o Version --description 'Show version of program.'
complete -c genl -s s -o stats -o statistics --description 'Show object statistics.'
complete -c genl -s d -o details --description 'Show object details.'
complete -c genl -s r -o raw --description 'Dump raw output only.  SEE ALSO ip (8).'

