# genpkey
# Autogenerated from man page /usr/share/man/man1/genpkey.1ssl.gz
complete -c genpkey -o help --description 'Print out a usage message.'
complete -c genpkey -o out --description 'Output the key to the specified file.'
complete -c genpkey -o outform --description 'This specifies the output format \\s-1DER\\s0 or \\s-1PEM. \\s0.'
complete -c genpkey -o pass --description 'the output file password source.'
complete -c genpkey -o cipher --description 'This option encrypts the private key with the supplied cipher.'
complete -c genpkey -o engine --description 'specifying an engine (by its unique id string) will cause genpkey to attempt …'
complete -c genpkey -o algorithm --description 'public key algorithm to use such as \\s-1RSA, DSA\\s0 or \\s-1DH.'
complete -c genpkey -o pkeyopt --description 'set the public key algorithm option opt to value.'
complete -c genpkey -o genparam --description 'generate a set of parameters instead of a private key.'
complete -c genpkey -o paramfile --description 'Some public key algorithms generate a private key based on a set of parameter…'

