# genrsa
# Autogenerated from man page /usr/share/man/man1/genrsa.1ssl.gz
complete -c genrsa -o help --description 'Print out a usage message.'
complete -c genrsa -o out --description 'Output the key to the specified file.'
complete -c genrsa -o passout --description 'the output file password source.'
complete -c genrsa -o aes128 -o aes192 -o aes256 -o aria128 -o aria192 -o aria256 -o camellia128 -o camellia192 -o camellia256 -o des -o des3 -o idea --description 'These options encrypt the private key with specified cipher before outputting…'
complete -c genrsa -o F4 -s 3 --description 'the public exponent to use, either 65537 or 3.  The default is 65537.'
complete -c genrsa -o rand --description 'a file or files containing random data used to seed the random number generat…'
complete -c genrsa -o engine --description 'specifying an engine (by its unique id string) will cause genrsa to attempt t…'

