# gensprep
# Autogenerated from man page /usr/share/man/man8/gensprep.8.gz
complete -c gensprep -s h -s '?' -l help --description 'Print help about usage and exit.'
complete -c gensprep -s v -l verbose --description 'Display extra informative messages during execution.'
complete -c gensprep -s c -l copyright --description 'Include a copyright notice into the binary data.'
complete -c gensprep -s s -l sourcedir --description 'Set the source directory to R source .'
complete -c gensprep -s d -l destdir --description 'Set the destination directory to destination .'

