# get
# Autogenerated from man page /usr/share/man/man1/get.1p.gz
complete -c get -s r --description 'Indicate the SCCS Identification String (SID) of the version (delta) of an SC…'
complete -c get -s e --description 'option is also used), as a function of the SID specified.'
complete -c get -s c --description 'Indicate the cutoff date-time, in the form: YY[MM[DD[HH[MM[SS]]]]] For the YY…'
complete -c get -s k --description 'option in place of the.'
complete -c get -s b --description 'Use with the.'
complete -c get -s i --description 'Indicate a list of deltas to be included (forced to be applied) in the creati…'
complete -c get -s x --description 'Indicate a list of deltas to be excluded (forced not to be applied) in the cr…'
complete -c get -s l --description 'Write a delta summary into an l-file .'
complete -c get -s L --description 'Write a delta summary to standard output.'
complete -c get -s s --description 'option is used, in which case it shall be suppressed.'
complete -c get -s p --description 'Write the text retrieved from the SCCS file to the standard output.'
complete -c get -s m --description 'Precede each text line retrieved from the SCCS file by the SID of the delta t…'
complete -c get -s n --description 'Precede each generated text line with the %M% identification keyword value (s…'
complete -c get -s g --description 'Suppress the actual retrieval of text from the SCCS file.'
complete -c get -s t --description 'Use to access the most recently created (top) delta in a given release (for e…'

