# getcap
# Autogenerated from man page /usr/share/man/man8/getcap.8.gz
complete -c getcap -s r --description 'enables recursive search.'
complete -c getcap -s v --description 'enables to display all searched entries, even if it has no file-capabilities.'
complete -c getcap -s h --description 'prints quick usage.'

