# getent
# Autogenerated from man page /usr/share/man/man1/getent.1.gz
complete -c getent -o sservice -l serviceservice --description '\\" commit 9d0881aa76b399e6a025c5cf44bebe2ae0efa8af (glibc) Override all datab…'
complete -c getent -o sdatabase:service --description '--servicedatabase:service .'
complete -c getent -s i -l no-idn --description '\\" commit a160f8d808cf8020b13bd0ef4a9eaf3c11f964ad (glibc) Disables IDN encod…'
complete -c getent -s '?' -l help --description 'Print a usage summary and exit.'
complete -c getent -l usage --description 'Print a short usage summary and exit.'
complete -c getent -s s -l service --description '.'
complete -c getent -s V -l version --description 'Print the version number, license, and disclaimer of warranty for getent .'

