# getopt
# Autogenerated from man page /usr/share/man/man1/getopt.1.gz
complete -c getopt -s a -l alternative --description 'Allow long options to start with a single . RB \' - \'.'
complete -c getopt -s h -l help --description 'Display help text and exit.   No other output is generated.'
complete -c getopt -s l -l longoptions --description 'The long (multi-character) options to be recognized.'
complete -c getopt -s n -l name --description 'The name that will be used by the  getopt (3) routines when it reports errors.'
complete -c getopt -s o -l options --description 'The short (one-character) options to be recognized.'
complete -c getopt -s q -l quiet --description 'Disable error reporting by getopt(3).'
complete -c getopt -s Q -l quiet-output --description 'Do not generate normal output.'
complete -c getopt -s s -l shell --description 'Set quoting conventions to those of shell.'
complete -c getopt -s T -l test --description 'Test if your  getopt (1) is this enhanced version or an old version.'
complete -c getopt -s u -l unquoted --description 'Do not quote the output.'
complete -c getopt -s V -l version --description 'Display version information and exit.   No other output is generated.'

