# gettext
# Autogenerated from man page /usr/share/man/man1/gettext.1.gz
complete -c gettext -s d -l domain --description 'retrieve translated messages from TEXTDOMAIN.'
complete -c gettext -s e --description 'enable expansion of some escape sequences.'
complete -c gettext -s E --description '(ignored for compatibility).'
complete -c gettext -s h -l help --description 'display this help and exit.'
complete -c gettext -s n --description 'suppress trailing newline.'
complete -c gettext -s V -l version --description 'display version information and exit.'

