# gifinto
# Autogenerated from man page /usr/share/man/man1/gifinto.1.gz
complete -c gifinto -s v --description 'Verbose mode (show progress).  Enables printout of running scan lines.'
complete -c gifinto -s s --description 'If file is less than MinFileSize, it is deleted and not renamed to the given …'
complete -c gifinto -s h --description 'Print one line of command line help, similar to Usage above.'

