# giftext
# Autogenerated from man page /usr/share/man/man1/giftext.1.gz
complete -c giftext -s v --description 'Verbose mode (show progress).  Enables printout of running scan lines.'
complete -c giftext -s c --description 'Dumps the color maps.'
complete -c giftext -s e --description 'Dumps encoded bytes - the pixels after compressed using LZ algorithm and chai…'
complete -c giftext -s z --description 'Dumps the LZ codes of the image.'
complete -c giftext -s p --description 'Dumps the pixels of the image.  Dumps in hex - 2 digit per pixel (<=byte).'
complete -c giftext -s r --description 'Dumps raw pixels as one byte per pixel.'
complete -c giftext -s h --description 'Print one line of command line help, similar to Usage above.'

