# git-archive
# Autogenerated from man page /usr/share/man/man1/git-archive.1.gz
complete -c git-archive -l format --description 'Format of the resulting archive: tar or zip.'
complete -c git-archive -s l -l list --description 'Show all available formats.'
complete -c git-archive -s v -l verbose --description 'Report progress to stderr.'
complete -c git-archive -l prefix --description 'Prepend <prefix>/ to each filename in the archive.'
complete -c git-archive -s o -l output --description 'Write the archive to <file> instead of stdout.'
complete -c git-archive -l worktree-attributes --description 'Look for attributes in .'
complete -c git-archive -l remote --description 'Instead of making a tar archive from the local repository, retrieve a tar arc…'
complete -c git-archive -l exec --description 'Used with --remote to specify the path to the git-upload-archive on the remot…'
complete -c git-archive -s 0 --description '.'
complete -c git-archive -s 9 --description '.'

