# git-write-tree
# Autogenerated from man page /usr/share/man/man1/git-write-tree.1.gz
complete -c git-write-tree -l missing-ok --description 'Normally git write-tree ensures that the objects referenced by the directory …'
complete -c git-write-tree -l prefix --description 'Writes a tree object that represents a subdirectory <prefix>.'

