# git-check-mailmap
# Autogenerated from man page /usr/share/man/man1/git-check-mailmap.1.gz
complete -c git-check-mailmap -l stdin --description 'Read contacts, one per line, from the standard input after exhausting contact…'

