# git-stash
# Autogenerated from man page /usr/share/man/man1/git-stash.1.gz
complete -c git-stash -s p -l patch -s k -s u -l include-untracked -s a -l all -s q -l quiet -s m -l message --description 'Save your local modifications to a new stash entry and roll them back to HEAD…'
complete -c git-stash -l keep-index --description 'option is used, all changes already added to the index are left intact.'
complete -c git-stash -l no-keep-index --description 'to override this.'
complete -c git-stash -l index --description 'option is used, then tries to reinstate not only the working tree\'s changes, …'
complete -c git-stash -l ---H----I --description 'where H is the HEAD commit, I is a commit that records the state of the index…'

