# git-symbolic-ref
# Autogenerated from man page /usr/share/man/man1/git-symbolic-ref.1.gz
complete -c git-symbolic-ref -s d -l delete --description 'Delete the symbolic ref <name>.'
complete -c git-symbolic-ref -s q -l quiet --description 'Do not issue an error message if the <name> is not a symbolic ref but a detac…'
complete -c git-symbolic-ref -l short --description 'When showing the value of <name> as a symbolic ref, try to shorten the value,…'
complete -c git-symbolic-ref -s m --description 'Update the reflog for <name> with <reason>.'

