# git-checkout-index
# Autogenerated from man page /usr/share/man/man1/git-checkout-index.1.gz
complete -c git-checkout-index -s u -l index --description 'update stat information for the checked out entries in the index file.'
complete -c git-checkout-index -s q -l quiet --description 'be quiet if files exist or are not in the index.'
complete -c git-checkout-index -s f -l force --description 'forces overwrite of existing files.'
complete -c git-checkout-index -s a -l all --description 'checks out all files in the index.'
complete -c git-checkout-index -s n -l no-create --description 'Don\\(cqt checkout new files, only refresh files already checked out.'
complete -c git-checkout-index -l prefix --description 'When creating files, prepend <string> (usually a directory including a traili…'
complete -c git-checkout-index -l stage --description 'Instead of checking out unmerged entries, copy out the files from named stage.'
complete -c git-checkout-index -l temp --description 'Instead of copying the files to the working directory write the content to te…'
complete -c git-checkout-index -l stdin --description 'Instead of taking list of paths from the command line, read list of paths fro…'
complete -c git-checkout-index -s z --description 'Only meaningful with --stdin; paths are separated with NUL character instead …'
complete -c git-checkout-index -l 'stdin;' --description '.'

