# git-fast-export
# Autogenerated from man page /usr/share/man/man1/git-fast-export.1.gz
complete -c git-fast-export -l progress --description 'Insert progress statements every <n> objects, to be shown by git fast-import …'
complete -c git-fast-export -l signed-tags --description 'Specify how to handle signed tags.'
complete -c git-fast-export -l tag-of-filtered-object --description 'Specify how to handle tags whose tagged object is filtered out.'
complete -c git-fast-export -s M -s C --description 'Perform move and/or copy detection, as described in the git-diff(1) manual pa…'
complete -c git-fast-export -l export-marks --description 'Dumps the internal marks table to <file> when complete.'
complete -c git-fast-export -l import-marks --description 'Before processing any input, load the marks specified in <file>.'
complete -c git-fast-export -l fake-missing-tagger --description 'Some old repositories have tags without a tagger.'
complete -c git-fast-export -l use-done-feature --description 'Start the stream with a feature done stanza, and terminate it with a done com…'
complete -c git-fast-export -l no-data --description 'Skip output of blob objects and instead refer to blobs via their original SHA…'
complete -c git-fast-export -l full-tree --description 'This option will cause fast-export to issue a "deleteall" directive for each …'
complete -c git-fast-export -l anonymize --description 'Anonymize the contents of the repository while still retaining the shape of t…'
complete -c git-fast-export -l refspec --description 'Apply the specified refspec to each ref exported.'

