# git-credential-cache
# Autogenerated from man page /usr/share/man/man1/git-credential-cache.1.gz
complete -c git-credential-cache -l timeout --description 'Number of seconds to cache credentials (default: 900).'
complete -c git-credential-cache -l socket --description 'Use <path> to contact a running cache daemon (or start a new cache daemon if …'

