# git-check-ignore
# Autogenerated from man page /usr/share/man/man1/git-check-ignore.1.gz
complete -c git-check-ignore -s q -l quiet --description 'Don\\(cqt output anything, just set exit status.'
complete -c git-check-ignore -s v -l verbose --description 'Also output details about the matching pattern (if any) for each given pathna…'
complete -c git-check-ignore -l stdin --description 'Read pathnames from the standard input, one per line, instead of from the com…'
complete -c git-check-ignore -s z --description 'The output format is modified to be machine-parseable (see below).'
complete -c git-check-ignore -s n -l non-matching --description 'Show given paths which don\\(cqt match any pattern.'
complete -c git-check-ignore -l no-index --description 'Don\\(cqt look in the index when undertaking the checks.'

