# git-credential-store
# Autogenerated from man page /usr/share/man/man1/git-credential-store.1.gz
complete -c git-credential-store -l file --description 'Use <path> to lookup and store credentials.'

