# git-subtree
# Autogenerated from man page /usr/share/man/man1/git-subtree.1.gz
complete -c git-subtree -s q -l quiet --description 'Suppress unnecessary output messages on stderr.'
complete -c git-subtree -s d -l debug --description 'Produce even more unnecessary output messages on stderr.'
complete -c git-subtree -s P -l prefix --description 'Specify the path in the repository to the subtree you want to manipulate.'
complete -c git-subtree -s m -l message --description 'This option is only valid for add, merge and pull (unsure).'
complete -c git-subtree -l squash --description 'merge.'
complete -c git-subtree -l rejoin --description 'when you split.'
complete -c git-subtree -l annotate --description '.'
complete -c git-subtree -s b -l branch --description '.'
complete -c git-subtree -l ignore-joins --description '.'
complete -c git-subtree -l ignore-join --description 'disables this behaviour, forcing it to regenerate the entire history.'
complete -c git-subtree -l onto --description '.'

