# git-archimport
# Autogenerated from man page /usr/share/man/man1/git-archimport.1.gz
complete -c git-archimport -s h --description 'Display usage.'
complete -c git-archimport -s v --description 'Verbose output.'
complete -c git-archimport -s T --description 'Many tags.'
complete -c git-archimport -s f --description 'Use the fast patchset import strategy.'
complete -c git-archimport -s o --description 'Use this for compatibility with old-style branch names used by earlier versio…'
complete -c git-archimport -s D --description 'Follow merge ancestry and attempt to import trees that have been merged from.'
complete -c git-archimport -s a --description 'Attempt to auto-register archives at http://mirrors. sourcecontrol.'
complete -c git-archimport -s t --description 'Override the default tempdir.'

