# git-cvsserver
# Autogenerated from man page /usr/share/man/man1/git-cvsserver.1.gz
complete -c git-cvsserver -l base-path --description 'Prepend path to requested CVSROOT.'
complete -c git-cvsserver -l strict-paths --description 'Don\\(cqt allow recursing into subdirectories.'
complete -c git-cvsserver -l export-all --description 'Don\\(cqt check for gitcvs. enabled in config.'
complete -c git-cvsserver -s V -l version --description 'Print version information and exit.'
complete -c git-cvsserver -s h -s H -l help --description 'Print usage information and exit.'
complete -c git-cvsserver -s d --description 'master branch to the project-master directory:      cvs co -d project-master …'

