# git-describe
# Autogenerated from man page /usr/share/man/man1/git-describe.1.gz
complete -c git-describe -l dirty -l broken --description 'Describe the state of the working tree.'
complete -c git-describe -l all --description 'Instead of using only the annotated tags, use any ref found in refs/ namespac…'
complete -c git-describe -l tags --description 'Instead of using only the annotated tags, use any tag found in refs/tags name…'
complete -c git-describe -l contains --description 'Instead of finding the tag that predates the commit, find the tag that comes …'
complete -c git-describe -l abbrev --description 'Instead of using the default 7 hexadecimal digits as the abbreviated object n…'
complete -c git-describe -l candidates --description 'Instead of considering only the 10 most recent tags as candidates to describe…'
complete -c git-describe -l exact-match --description 'Only output exact matches (a tag directly references the supplied commit).'
complete -c git-describe -l debug --description 'Verbosely display information about the searching strategy being employed to …'
complete -c git-describe -l long --description 'Always output the long format (the tag, the number of commits and the abbrevi…'
complete -c git-describe -l match --description 'Only consider tags matching the given glob(7) pattern, excluding the "refs/ta…'
complete -c git-describe -l exclude --description 'Do not consider tags matching the given glob(7) pattern, excluding the "refs/…'
complete -c git-describe -l always --description 'Show uniquely abbreviated commit object as fallback.'
complete -c git-describe -l first-parent --description 'Follow only the first parent commit upon seeing a merge commit.'
complete -c git-describe -l no-match --description 'to clear and reset the list of patterns.'
complete -c git-describe -l no-exclude --description 'to clear and reset the list of patterns.'

