# git-column
# Autogenerated from man page /usr/share/man/man1/git-column.1.gz
complete -c git-column -l command --description 'Look up layout mode using configuration variable column. <name> and column.'
complete -c git-column -l mode --description 'Specify layout mode.  See configuration variable column. ui for option syntax.'
complete -c git-column -l raw-mode --description 'Same as --mode but take mode encoded as a number.'
complete -c git-column -l width --description 'Specify the terminal width.'
complete -c git-column -l indent --description 'String to be printed at the beginning of each line.'
complete -c git-column -l nl --description 'String to be printed at the end of each line, including newline character.'
complete -c git-column -l padding --description 'The number of spaces between columns.  One space by default.'

