# git-commit-graph
# Autogenerated from man page /usr/share/man/man1/git-commit-graph.1.gz
complete -c git-commit-graph -l object-dir --description 'Use given directory for the location of packfiles and commit graph file.'
complete -c git-commit-graph -l stdin-packs --description 'option, generate the new commit graph by walking objects only in the specifie…'
complete -c git-commit-graph -l stdin-commits --description 'option, generate the new commit graph by walking commits starting at the comm…'
complete -c git-commit-graph -l append --description 'option, include all commits that are present in the existing commit-graph fil…'

