# git-prune-packed
# Autogenerated from man page /usr/share/man/man1/git-prune-packed.1.gz
complete -c git-prune-packed -s n -l dry-run --description 'Don\\(cqt actually remove any objects, only show those that would have been re…'
complete -c git-prune-packed -s q -l quiet --description 'Squelch the progress indicator.'

