# git-ls-tree
# Autogenerated from man page /usr/share/man/man1/git-ls-tree.1.gz
complete -c git-ls-tree -s d --description 'Show only the named tree entry itself, not its children.'
complete -c git-ls-tree -s r --description 'Recurse into sub-trees.'
complete -c git-ls-tree -s t --description 'Show tree entries even when going to recurse them.'
complete -c git-ls-tree -s l -l long --description 'Show object size of blob (file) entries.'
complete -c git-ls-tree -s z --description '0 line termination on output and do not quote filenames.'
complete -c git-ls-tree -l name-only -l name-status --description 'List only filenames (instead of the "long" output), one per line.'
complete -c git-ls-tree -l abbrev --description 'Instead of showing the full 40-byte hexadecimal object lines, show only a par…'
complete -c git-ls-tree -l full-name --description 'Instead of showing the path names relative to the current working directory, …'
complete -c git-ls-tree -l full-tree --description 'Do not limit the listing to the current working directory.'

