# git-merge-file
# Autogenerated from man page /usr/share/man/man1/git-merge-file.1.gz
complete -c git-merge-file -s L --description 'This option may be given up to three times, and specifies labels to be used i…'
complete -c git-merge-file -s p --description 'Send results to standard output instead of overwriting <current-file>.'
complete -c git-merge-file -s q --description 'Quiet; do not warn about conflicts.'
complete -c git-merge-file -l diff3 --description 'Show conflicts in "diff3" style.'
complete -c git-merge-file -l ours -l theirs -l union --description 'Instead of leaving conflicts in the file, resolve conflicts favouring our (or…'

