# git-upload-pack
# Autogenerated from man page /usr/share/man/man1/git-upload-pack.1.gz
complete -c git-upload-pack -l strict --description '.'
complete -c git-upload-pack -l timeout --description '.'
complete -c git-upload-pack -l stateless-rpc --description '.'
complete -c git-upload-pack -l advertise-refs --description '.'

