# git-http-push
# Autogenerated from man page /usr/share/man/man1/git-http-push.1.gz
complete -c git-http-push -l all --description 'Do not assume that the remote repository is complete in its current state, an…'
complete -c git-http-push -l force --description 'Usually, the command refuses to update a remote ref that is not an ancestor o…'
complete -c git-http-push -l dry-run --description 'Do everything except actually send the updates.'
complete -c git-http-push -l verbose --description 'Report the list of objects being walked locally and the list of objects succe…'
complete -c git-http-push -s d -s D --description 'Remove <ref> from remote repository.'

