# git-update-server-info
# Autogenerated from man page /usr/share/man/man1/git-update-server-info.1.gz
complete -c git-update-server-info -s f -l force --description 'Update the info files from scratch.'

