# git-patch-id
# Autogenerated from man page /usr/share/man/man1/git-patch-id.1.gz
complete -c git-patch-id -l stable --description 'Use a "stable" sum of hashes as the patch ID.  With this option: . sp.'
complete -c git-patch-id -l unstable --description 'Use an "unstable" hash as the patch ID.'

