# git-fmt-merge-msg
# Autogenerated from man page /usr/share/man/man1/git-fmt-merge-msg.1.gz
complete -c git-fmt-merge-msg -l log --description 'In addition to branch names, populate the log message with one-line descripti…'
complete -c git-fmt-merge-msg -l no-log --description 'Do not list one-line descriptions from the actual commits being merged.'
complete -c git-fmt-merge-msg -l summary --description 'Synonyms to --log and --no-log; these are deprecated and will be removed in t…'
complete -c git-fmt-merge-msg -s m -l message --description 'Use <message> instead of the branch names for the first line of the log messa…'
complete -c git-fmt-merge-msg -s F -l file --description 'Take the list of merged objects from <file> instead of stdin.'

