# git-rm
# Autogenerated from man page /usr/share/man/man1/git-rm.1.gz
complete -c git-rm -s f -l force --description 'Override the up-to-date check.'
complete -c git-rm -s n -l dry-run --description 'Don\\(cqt actually remove any file(s).'
complete -c git-rm -s r --description 'Allow recursive removal when a leading directory name is given.'
complete -c git-rm -l cached --description 'Use this option to unstage and remove paths only from the index.'
complete -c git-rm -l ignore-unmatch --description 'Exit with a zero status even if no files matched.'
complete -c git-rm -s q -l quiet --description 'git rm normally outputs one line (in the form of an rm command) for each file…'

