# git-instaweb
# Autogenerated from man page /usr/share/man/man1/git-instaweb.1.gz
complete -c git-instaweb -s l -l local --description 'Only bind the web server to the local IP (127. 0. 0. 1).'
complete -c git-instaweb -s d -l httpd --description 'The HTTP daemon command-line that will be executed.'
complete -c git-instaweb -s m -l module-path --description 'The module path (only needed if httpd is Apache).'
complete -c git-instaweb -s p -l port --description 'The port number to bind the httpd to.  (Default: 1234).'
complete -c git-instaweb -s b -l browser --description 'The web browser that should be used to view the gitweb page.'
complete -c git-instaweb -l start --description 'Start the httpd instance and exit.'
complete -c git-instaweb -l stop --description 'Stop the httpd instance and exit.'
complete -c git-instaweb -l restart --description 'Restart the httpd instance and exit.'

