# git-check-ref-format
# Autogenerated from man page /usr/share/man/man1/git-check-ref-format.1.gz
complete -c git-check-ref-format -l allow-onelevel --description 'Controls whether one-level refnames are accepted (i. e.'
complete -c git-check-ref-format -l refspec-pattern --description 'Interpret <refname> as a reference name pattern for a refspec (as used with r…'
complete -c git-check-ref-format -l normalize --description 'Normalize refname by removing any leading slash (/) characters and collapsing…'
complete -c git-check-ref-format -l no-allow-onelevel --description '.'

