# git-bisect
# Autogenerated from man page /usr/share/man/man1/git-bisect.1.gz
complete -c git-bisect -l no-checkout --description 'Do not checkout the new working tree at each iteration of the bisection proce…'

