# git-imap-send
# Autogenerated from man page /usr/share/man/man1/git-imap-send.1.gz
complete -c git-imap-send -s v -l verbose --description 'Be verbose.'
complete -c git-imap-send -s q -l quiet --description 'Be quiet.'
complete -c git-imap-send -l curl --description 'Use libcurl to communicate with the IMAP server, unless tunneling into it.'
complete -c git-imap-send -l no-curl --description 'Talk to the IMAP server using git\\(cqs own IMAP routines instead of using lib…'

