# git-pack-refs
# Autogenerated from man page /usr/share/man/man1/git-pack-refs.1.gz
complete -c git-pack-refs -l all --description 'The command by default packs all tags and refs that are already packed, and l…'
complete -c git-pack-refs -l no-prune --description 'The command usually removes loose refs under $GIT_DIR/refs hierarchy after pa…'

