# git-gc
# Autogenerated from man page /usr/share/man/man1/git-gc.1.gz
complete -c git-gc -l aggressive --description 'Usually git gc runs very quickly while providing good disk space utilization …'
complete -c git-gc -l auto --description 'With this option, git gc checks whether any housekeeping is required; if not,…'
complete -c git-gc -l prune --description 'Prune loose objects older than date (default is 2 weeks ago, overridable by t…'
complete -c git-gc -l no-prune --description 'Do not prune any loose objects.'
complete -c git-gc -l quiet --description 'Suppress all progress reports.'
complete -c git-gc -l force --description 'Force git gc to run even if there may be another git gc instance running on t…'
complete -c git-gc -l keep-largest-pack --description 'All packs except the largest pack and those marked with a .'
complete -c git-gc -s A --description 'option of git repack.'
complete -c git-gc -l keep-base-pack --description 'gc. autoPackLimit to 0 disables automatic consolidation of packs.'

