# gitremote-helpers
# Autogenerated from man page /usr/share/man/man1/gitremote-helpers.1.gz
complete -c gitremote-helpers -l export-marks --description 'in git-fast-export(1).  import-marks <file>.'
complete -c gitremote-helpers -l import-marks --description 'in git-fast-export(1).  signed-tags.'
complete -c gitremote-helpers -l signed-tags --description 'to git-fast-export(1).  In the absence of this capability, Git will use.'

