# gitweb
# Autogenerated from man page /usr/share/man/man1/gitweb.1.gz
complete -c gitweb -l export-all --description 'option is used) allows pulling only for those repositories that have git-daem…'

