# glib-gettextize
# Autogenerated from man page /usr/share/man/man1/glib-gettextize.1.gz
complete -c glib-gettextize -l help --description 'print help and exit.'
complete -c glib-gettextize -l version --description 'print version information and exit.'
complete -c glib-gettextize -s c -l copy --description 'copy files instead of making symlinks.'
complete -c glib-gettextize -s f -l force --description 'force writing of new files even if old ones exist.'
complete -c glib-gettextize -l no-changelog --description 'option).  OPTIONS.'

