# glib-compile-resources
# Autogenerated from man page /usr/share/man/man1/glib-compile-resources.1.gz
complete -c glib-compile-resources -s h -l help --description 'Print help and exit.'
complete -c glib-compile-resources -l version --description 'Print program version and exit.'
complete -c glib-compile-resources -l target --description 'Store the compiled resources in the file TARGET.'
complete -c glib-compile-resources -l sourcedir --description 'The files referenced in FILE are loaded from this directory.'
complete -c glib-compile-resources -l generate-source --description 'Instead of a writing the resource bundle in binary form create a C source fil…'
complete -c glib-compile-resources -l generate-header --description 'Generate a header file for use with C code generated by --generate-source.'
complete -c glib-compile-resources -l generate-dependencies --description 'Prints the list of files that the resource bundle references to standard outp…'
complete -c glib-compile-resources -l c-name --description 'Specify the prefix used for the C identifiers in the code generated by --gene…'
complete -c glib-compile-resources -l manual-register --description 'By default code generated by --generate-source uses automatic initialization …'
complete -c glib-compile-resources -l internal --description 'By default code generated by --generate-source declares all initialization fu…'
complete -c glib-compile-resources -l dependency-file --description 'Write dependencies in the same style as gcc -M -MF to the given file.'
complete -c glib-compile-resources -l generate-phony-targets --description 'When creating a dependency file with --dependency-file include phony targets …'
complete -c glib-compile-resources -l generate --description '.'

