# gobject-query
# Autogenerated from man page /usr/share/man/man1/gobject-query.1.gz
complete -c gobject-query -s r --description 'specify the root type.'
complete -c gobject-query -s n --description 'don\\*(Aqt descend type tree.'
complete -c gobject-query -s b --description 'specify indent string.'
complete -c gobject-query -s i --description 'specify incremental indent string.'
complete -c gobject-query -s s --description 'specify line spacing.'
complete -c gobject-query -s h -l help --description 'Print brief help and exit.'
complete -c gobject-query -s v -l version --description 'Print version and exit.'

