# gpasswd
# Autogenerated from man page /usr/share/man/man1/gpasswd.1.gz
complete -c gpasswd -s a -l adduser --description 'Add the user to the named group.'
complete -c gpasswd -s d -l deleteuser --description 'Remove the user from the named group.'
complete -c gpasswd -s h -l help --description 'Display help message and exit.'
complete -c gpasswd -s Q -l rootCHROOT_DIR --description 'Apply changes in the CHROOT_DIR directory and use the configuration files fro…'
complete -c gpasswd -s r -l remove-password --description 'Remove the password from the named group.  The group password will be empty.'
complete -c gpasswd -s R -l restrict --description 'Restrict the access to the named group.  The group password is set to "!".'
complete -c gpasswd -s A -l administratorsuser --description 'Set the list of administrative users.'
complete -c gpasswd -s M -l membersuser --description 'Set the list of group members.'
complete -c gpasswd -l add --description '.'
complete -c gpasswd -l delete --description '.'
complete -c gpasswd -l root --description '.'
complete -c gpasswd -l administrators --description '.'
complete -c gpasswd -l members --description '.'

