# gpg-wks-client
# Autogenerated from man page /usr/share/man/man1/gpg-wks-client.1.gz
complete -c gpg-wks-client -l send --description 'Directly send created mails using the sendmail command.'
complete -c gpg-wks-client -l output --description 'TQ   -o Write the created mail to file instead of stdout.'
complete -c gpg-wks-client -l status-fd --description 'Write special status strings to the file descriptor n.'
complete -c gpg-wks-client -l verbose --description 'Enable extra informational output.'
complete -c gpg-wks-client -l quiet --description 'Disable almost all informational output.'
complete -c gpg-wks-client -l version --description 'Print version of the program and exit.'
complete -c gpg-wks-client -l create --description '.'
complete -c gpg-wks-client -s o --description 'Write the created mail to file instead of stdout.'
complete -c gpg-wks-client -l help --description 'Display a brief help page and exit.  SEE ALSO gpg-wks-server(1).'

