# gpgv
# Autogenerated from man page /usr/share/man/man1/gpgv.1.gz
complete -c gpgv -l verbose --description 'TQ   -v Gives more information during processing.'
complete -c gpgv -l quiet --description 'TQ   -q Try to be as quiet as possible.'
complete -c gpgv -l keyring --description 'Add file to the list of keyrings.'
complete -c gpgv -l output --description 'TQ   -o file Write output to file; to write to stdout use -.'
complete -c gpgv -l status-fd --description 'Write special status strings to the file descriptor n.'
complete -c gpgv -l logger-fd --description 'Write log output to file descriptor n and not to stderr.'
complete -c gpgv -l log-file --description 'Same as --logger-fd, except the logger data is written to file file.'
complete -c gpgv -l ignore-time-conflict --description 'GnuPG normally checks that the timestamps associated with keys and signatures…'
complete -c gpgv -l homedir --description 'Set the name of the home directory to dir.'
complete -c gpgv -l weak-digest --description 'Treat the specified digest algorithm as weak.'
complete -c gpgv -s v --description 'Gives more information during processing.'
complete -c gpgv -s q --description 'Try to be as quiet as possible.'
complete -c gpgv -s o --description 'Write output to file; to write to stdout use -.'
complete -c gpgv -l enable-special-filenames --description 'This option enables a mode in which filenames of the form `-&n\', where n is a…'

