# gresource
# Autogenerated from man page /usr/share/man/man1/gresource.1.gz
complete -c gresource -l section --description 'option.  Use the sections command to find available sections.  COMMANDS.'

