# grn
# Autogenerated from man page /usr/share/man/man1/grn.1.gz
complete -c grn -s T --description 'Prepare output for printer R dev .  The default device is  ps .'
complete -c grn -s M --description 'Prepend  dir to the default search path for  gremlin files.'
complete -c grn -s F --description 'Search  dir for subdirectories  dev name .'
complete -c grn -s C --description 'Recognize  . GS and  . GE (and  .'
complete -c grn -s s --description '\\"This switch causes the picture to be traversed twice: .'
complete -c grn -s v --description 'Print the version number.'
complete -c grn -o 1@@-1 --description 'Table 1.'
complete -c grn -o '1.0' --description '( AED version) or a single asterisk, [lq]*[rq] ( SUN / X11 version).'

