# grodvi
# Autogenerated from man page /usr/share/man/man1/grodvi.1.gz
complete -c grodvi -s d --description 'Do not use tpic specials to implement drawing commands.'
complete -c grodvi -s F --description 'Prepend directory B dir /dev name to the search path for font and device desc…'
complete -c grodvi -s l --description 'Specify landscape orientation.'
complete -c grodvi -s p --description 'Specify paper dimensions.'
complete -c grodvi -s v --description 'Print the version number.'
complete -c grodvi -o Tdvi --description 'loads pspic. tmac automatically, providing the PSPIC macro.'
complete -c grodvi -s w --description 'Set the default line thickness to n thousandths of an em.'
complete -c grodvi -o mec --description '(which loads the file ec. tmac ) provides the EC and TC fonts.'

