# grolj4
# Autogenerated from man page /usr/share/man/man1/grolj4.1.gz
complete -c grolj4 -s c --description 'Print  n copies of each page.'
complete -c grolj4 -s l --description 'Print the document with a landscape orientation.'
complete -c grolj4 -s d --description 'Use duplex mode R n : 1is long-side binding; 2is short-side binding; default …'
complete -c grolj4 -s p --description 'Set the paper size to R size , which must be one of letter, legal, executive,…'
complete -c grolj4 -s v --description 'Print the version number.'
complete -c grolj4 -s w --description 'Set the default line thickness to  n thousandths of an em.'
complete -c grolj4 -s F --description 'Prepend directory B dir /dev name to the search path for font and device desc…'

