# grops
# Autogenerated from man page /usr/share/man/man1/grops.1.gz
complete -c grops -s b --description 'Provide workarounds for older printers, broken spoolers, and previewers.'
complete -c grops -s c --description 'Print  n copies of each page.'
complete -c grops -s F --description 'Prepend directory B dir /dev name to the search path for prologue, font, and …'
complete -c grops -s g --description 'Guess the page length.'
complete -c grops -s I --description 'This option may be used to add a directory to the search path for files on th…'
complete -c grops -s l --description 'Print the document in landscape format.'
complete -c grops -s m --description 'Turn manual feed on for the document.'
complete -c grops -s p --description 'Set physical dimension of output medium.'
complete -c grops -s P --description 'Use the file  prologue-file (in the font path) as the prologue instead of the…'
complete -c grops -s w --description 'Lines should be drawn using a thickness of R n \\~\\c thousandths of an em.'
complete -c grops -o Tps --description 'option.  If no files are given, grops reads the standard input.'
complete -c grops -s v --description 'Print the version number.'
complete -c grops -o 'u\'\\c' --description 'Convert your font to something groff understands.'

