# grpck
# Autogenerated from man page /usr/share/man/man8/grpck.8.gz
complete -c grpck -s h -l help --description 'Display help message and exit.'
complete -c grpck -s r -l read-only --description 'Execute the grpck command in read-only mode.'
complete -c grpck -s R -l rootCHROOT_DIR --description 'Apply changes in the CHROOT_DIR directory and use the configuration files fro…'
complete -c grpck -s s -l sort --description 'Sort entries in /etc/group and /etc/gshadow by GID.'
complete -c grpck -l root --description '.'

