# gtester
# Autogenerated from man page /usr/share/man/man1/gtester.1.gz
complete -c gtester -s h -l help --description 'print help and exit.'
complete -c gtester -s v -l version --description 'print version information and exit.'
complete -c gtester -l g-fatal-warnings --description 'make warnings fatal.'
complete -c gtester -s k -l keep-going --description 'continue running after tests failed.'
complete -c gtester -s l --description 'list paths of available test cases.'
complete -c gtester -s p --description 'only run test cases matching TESTPATH.'
complete -c gtester -s s --description 'skip test cases matching TESTPATH.'
complete -c gtester -l seed --description 'run all test cases with random number seed SEEDSTRING.'
complete -c gtester -s o --description 'write the test log to LOGFILE.'
complete -c gtester -s q -l quiet --description 'suppress per test binary output.'
complete -c gtester -l verbose --description 'report success per testcase.'
complete -c gtester -s m --description '.'

