# gtester-report
# Autogenerated from man page /usr/share/man/man1/gtester-report.1.gz
complete -c gtester-report -s h -l help --description 'print help and exit.'
complete -c gtester-report -s v -l version --description 'print version information and exit.'
complete -c gtester-report -s s -l subunit --description 'Output subunit.  Needs python-subunit.'

