# gtf
# Autogenerated from man page /usr/share/man/man1/gtf.1.gz
complete -c gtf -s v -l verbose --description 'Enable verbose printouts  This shows a trace for each step of the computation.'
complete -c gtf -s x -l xorgmode --description 'Print the mode parameters as Xorg-style mode lines.'
complete -c gtf -s f -l fbset --description 'Print the mode parameters in a format suitable for fbset(8) .  SEE ALSO xorg.'

