# gtk-query-immodules-3
# Autogenerated from man page /usr/share/man/man1/gtk-query-immodules-3.0.1.gz
complete -c gtk-query-immodules-3 -l update-cache --description 'Write the output to the default cache location instead of stdout.'

