# gtk-encode-symbolic-svg
# Autogenerated from man page /usr/share/man/man1/gtk-encode-symbolic-svg.1.gz
complete -c gtk-encode-symbolic-svg -s o -l output --description 'Write png files to DIRECTORY instead of the current working directory.'

