# gtk-builder-tool
# Autogenerated from man page /usr/share/man/man1/gtk-builder-tool.1.gz
complete -c gtk-builder-tool -l replace --description '.'
complete -c gtk-builder-tool -l id --description '.'
complete -c gtk-builder-tool -l css --description '.'

