# h2ph
# Autogenerated from man page /usr/share/man/man1/h2ph.1perl.gz
complete -c h2ph -s d --description 'Put the resulting .'
complete -c h2ph -s r --description 'Run recursively; if any of headerfiles are directories, then run h2ph on all …'
complete -c h2ph -s a --description 'Run automagically; convert headerfiles, as well as any .'
complete -c h2ph -s l --description 'Symbolic links will be replicated in the destination directory.'
complete -c h2ph -s h --description 'Put \'hints\' in the . ph files which will help in locating problems with h2ph.'
complete -c h2ph -s e --description 'If an error is encountered during conversion, output file will be removed and…'
complete -c h2ph -s D --description 'Include the code from the . h file as a comment in the . ph file.'

