# hash
# Autogenerated from man page /usr/share/man/man1/hash.1p.gz
complete -c hash -s r --description 'Forget all previously remembered utility locations.'
complete -c hash -s t --description 'in which case utilities found through normal command search are not listed by…'

