# hostname
# Autogenerated from man page /usr/share/man/man1/hostname.1.gz
complete -c hostname -s a -l aliases --description 'alias names.'
complete -c hostname -s d -l domain --description 'DNS domain name.'
complete -c hostname -s f -l fqdn -l long --description 'DNS host name or FQDN.'
complete -c hostname -s F -l file --description 'set host name or NIS domain name from FILE.'
complete -c hostname -s i -l ip-addresses --description 'addresses for the host name.'
complete -c hostname -s s -l short --description 'short host name.'
complete -c hostname -s y -l yp -l nis --description 'NIS/YP domain name.'
complete -c hostname -s '?' -l help --description 'give this help list.'
complete -c hostname -l usage --description 'give a short usage message.'
complete -c hostname -s V -l version --description 'print program version.'

