# hostnamectl
# Autogenerated from man page /usr/share/man/man1/hostnamectl.1.gz
complete -c hostnamectl -l no-ask-password --description 'Do not query the user for authentication for privileged operations.'
complete -c hostnamectl -l static -l transient -l pretty --description 'If status is invoked (or no explicit command is given) and one of these switc…'
complete -c hostnamectl -s H -l host --description 'Execute the operation remotely.'
complete -c hostnamectl -s M -l machine --description 'Execute operation on a local container.'
complete -c hostnamectl -s h -l help --description 'Print a short help text and exit.'
complete -c hostnamectl -l version --description 'Print a short version string and exit.'

