# hspell
# Autogenerated from man page /usr/share/man/man1/hspell.1.gz
complete -c hspell -s v --description 'If the  -v option is given,  hspell prints emacs-oriented version information…'
complete -c hspell -o vv --description 'Repetition of the  -v option causes  hspell to also show some information on …'
complete -c hspell -s V --description 'With the  -V option,  hspell prints true and human-oriented version informati…'
complete -c hspell -s c --description 'If the  -c option is given,  hspell will suggest corrections for misspelled w…'
complete -c hspell -s n --description 'The  -n option will give some longer "notes" about certain spelling errors, e…'
complete -c hspell -s l --description 'The  -l (linguistic information) option will explain for each  correct word w…'
complete -c hspell -s s --description 'Normally, the words deemed spelling mistakes are shown in alphabetical order.'
complete -c hspell -s a --description 'With the  -a option,  hspell tries to emulate (as little as possible of)  isp…'
complete -c hspell -s i --description 'This option only has any effect when used together with the  -a option.'
complete -c hspell -s H --description 'By default, Hspell does not allow the He Ha-sh\'ela prefix.'
complete -c hspell -s D --description 'Load the word lists from the given base pathname, rather than from the compil…'
complete -c hspell -o cn --description 'for maximal correction help from hspell .'
complete -c hspell -s d -s B -s m -s T -s C -s S -s P -s p -s w -s W --description 'These options are passed to hspell by lyx or other applications, thinking the…'

