# hzip
# Autogenerated from man page /usr/share/man/man1/hzip.1.gz
complete -c hzip -s h --description 'Display short help description.'
complete -c hzip -s P --description 'Encrypted compression by an arbitrary length password.'

