# i3-msg
# Autogenerated from man page /usr/share/man/man1/i3-msg.1.gz
complete -c i3-msg -s q -l quiet --description 'Only send ipc message and suppress the output of the response.'
complete -c i3-msg -s v -l version --description 'Display version number and exit.'
complete -c i3-msg -s h -l help --description 'Display a short help-message and exit.'
complete -c i3-msg -s s -l socket --description 'i3-msg will use the environment variable I3SOCK or the socket path given here.'
complete -c i3-msg -s t --description 'Send ipc message, see below.  This option defaults to "command".'

