# i3
# Autogenerated from man page /usr/share/man/man1/i3.1.gz
complete -c i3 -s a --description 'Disables autostart.'
complete -c i3 -s c --description 'Specifies an alternate configuration file path.'
complete -c i3 -s C --description 'Check the configuration file for validity and exit.'
complete -c i3 -s d --description 'Enables debug logging.  The all parameter is present for historical reasons.'
complete -c i3 -s v --description 'Display version number (and date of the last commit).'
complete -c i3 -s V --description 'Be verbose.'
complete -c i3 -l force-xinerama --description 'Use Xinerama instead of RandR.'
complete -c i3 -l get-socketpath --description 'Retrieve the i3 IPC socket path from X11, print it, then exit.'
complete -c i3 -l shmlog-size --description 'Limits the size of the i3 SHM log to <limit> bytes.'

