# iconvconfig
# Autogenerated from man page /usr/share/man/man8/iconvconfig.8.gz
complete -c iconvconfig -l nostdlib --description 'Do not search the system default gconv directory, only the directories provid…'
complete -c iconvconfig -s o -l output --description 'Use  outputfile for output instead of the system default cache location.'
complete -c iconvconfig -l prefix --description 'Set the prefix to be prepended to the system pathnames.  See FILES, below.'
complete -c iconvconfig -s '?' -l help --description 'Print a usage summary and exit.'
complete -c iconvconfig -l usage --description 'Print a short usage summary and exit.'
complete -c iconvconfig -s V -l version --description 'Print the version number, license, and disclaimer of warranty for iconv .'

