# iconv
# Autogenerated from man page /usr/share/man/man1/iconv.1.gz
complete -c iconv -s f -l from-code --description 'Use  from-encoding for input characters.'
complete -c iconv -s t -l to-code --description 'Use  to-encoding for output characters.'
complete -c iconv -s l -l list --description 'List all known character set encodings.'
complete -c iconv -s c --description 'Silently discard characters that cannot be converted instead of terminating w…'
complete -c iconv -s o -l output --description 'Use  outputfile for output.'
complete -c iconv -s s -l silent --description 'This option is ignored; it is provided only for compatibility.'
complete -c iconv -l verbose --description 'Print progress information on standard error when processing multiple files.'
complete -c iconv -s '?' -l help --description 'Print a usage summary and exit.'
complete -c iconv -l usage --description 'Print a short usage summary and exit.'
complete -c iconv -s V -l version --description 'Print the version number, license, and disclaimer of warranty for iconv .'

