# idn2
# Autogenerated from man page /usr/share/man/man1/idn2.1.gz
complete -c idn2 -s h -l help --description 'Prints help and exits.'
complete -c idn2 -s V -l version --description 'Prints version and exits.'
complete -c idn2 -s d -l decode --description 'Decode an ACE name according to IDNA2008.'
complete -c idn2 -s l -l lookup --description 'Encode to ACE according to IDNA2008 (the default).'
complete -c idn2 -s r -l register --description 'Registers a label.'
complete -c idn2 -s T -l tr46t --description 'Enable TR#46 transitional processing.'
complete -c idn2 -s N -l tr46nt --description 'Enable TR#46 non-transitional processing (default).'
complete -c idn2 -l no-tr46 --description 'Disable TR#46 processing.'
complete -c idn2 -l usestd3asciirules --description 'Enable STD3 ASCII rules.'
complete -c idn2 -l debug --description 'Prints debugging information.'
complete -c idn2 -l quiet --description 'Silent operation.'

