# ifrename
# Autogenerated from man page /usr/share/man/man8/ifrename.8.gz
complete -c ifrename -s c --description 'Set the configuration file to be used (by default  /etc/iftab ).'
complete -c ifrename -s p --description 'Probe (load) kernel modules before renaming interfaces.'
complete -c ifrename -s d --description 'Enable various Debian specific hacks.  Combined with.'
complete -c ifrename -s i --description 'Only rename the specified interface  as opposed to all interfaces on the syst…'
complete -c ifrename -s n --description 'When used with.'
complete -c ifrename -s t --description 'Enable name takeover support.'
complete -c ifrename -s u --description 'Enable udev output mode.'
complete -c ifrename -s D --description 'Dry-run mode.'
complete -c ifrename -s V --description 'Verbose mode.'
complete -c ifrename -s C --description 'Count matching interfaces.'

