# ifstat
# Autogenerated from man page /usr/share/man/man8/ifstat.8.gz
complete -c ifstat -s h -l help --description 'Show summary of options.'
complete -c ifstat -s V -l version --description 'Show version of program.'
complete -c ifstat -s a -l ignore --description 'Ignore the history file.'
complete -c ifstat -s d -l scan --description 'Sample statistics every SECS second.'
complete -c ifstat -s e -l errors --description 'Show errors.'
complete -c ifstat -s n -l nooutput --description 'Don\'t display any output.   Update the history file only.'
complete -c ifstat -s r -l reset --description 'Reset history.'
complete -c ifstat -s s -l noupdate --description 'Don\'t update the history file.'
complete -c ifstat -s t -l interval --description 'Report average over the last SECS seconds.'
complete -c ifstat -s z -l zeros --description 'Show entries with zero activity.'
complete -c ifstat -s x -l extended --description 'Show extended stats of TYPE.  Supported types are: cpu_hits.'

