# indxbib
# Autogenerated from man page /usr/share/man/man1/indxbib.1.gz
complete -c indxbib -s v --description 'Print the version number.'
complete -c indxbib -s w --description 'Index whole files.  Each file is a separate record.'
complete -c indxbib -s c --description 'Read the list of common words from  file instead of  /usr/share/groff/1. 22.'
complete -c indxbib -s d --description 'Use  dir as the pathname of the current working directory to store in the ind…'
complete -c indxbib -s f --description 'Read the files to be indexed from R file .'
complete -c indxbib -s i --description 'Don\\[aq]t index the contents of fields whose names are in R string .'
complete -c indxbib -s h --description 'Use the first prime greater than or equal to  n for the size of the hash tabl…'
complete -c indxbib -s k --description 'Use at most  n keys per input record.  Initially  n is 100.'
complete -c indxbib -s l --description 'Discard keys that are shorter than R n .  Initially  n is 3.'
complete -c indxbib -s n --description 'Discard the  n most common words.  Initially  n is 100.'
complete -c indxbib -s o --description 'The index should be named B basename . i.'
complete -c indxbib -s t --description 'options are stored in the index; when the index is searched, keys will be dis…'

