# info
# Autogenerated from man page /usr/share/man/man1/info.1.gz
complete -c info -s a -l all --description 'use all matching manuals.'
complete -c info -s k -l apropos --description 'look up STRING in all indices of all manuals.'
complete -c info -s d -l directory --description 'add DIR to INFOPATH.'
complete -c info -s f -l file --description 'specify Info manual to visit.'
complete -c info -s h -l help --description 'display this help and exit.'
complete -c info -l index-search --description 'go to node pointed by index entry STRING.'
complete -c info -s n -l node --description 'specify nodes in first visited Info file.'
complete -c info -s o -l output --description 'output selected nodes to FILE.'
complete -c info -s O -l show-options -l usage --description 'go to command-line options node.'
complete -c info -l subnodes --description 'recursively output menu items.'
complete -c info -s v -l variable --description 'assign VALUE to Info variable VAR.'
complete -c info -l version --description 'display version information and exit.'
complete -c info -s w -l where -l location --description 'print physical location of Info file.'

