# intro
# Autogenerated from man page /usr/share/man/man1/intro.1.gz
complete -c intro -o rw-rw-r-- --description '$  cat tel maja    0501-1136285 peter   0136-7399214 $  cp tel tel2 $  ls -l …'
complete -c intro -o rw-r--r-- --description '.'
complete -c intro -s l --description 'option it gives a long listing, that includes the owner and size and date of …'

