# ionice
# Autogenerated from man page /usr/share/man/man1/ionice.1.gz
complete -c ionice -s c -l class --description 'Specify the name or number of the scheduling class to use; 0 for none, 1 for …'
complete -c ionice -s n -l classdata --description 'Specify the scheduling class data.'
complete -c ionice -s p -l pid --description 'Specify the process IDs of running processes for which to get or set the sche…'
complete -c ionice -s P -l pgid --description 'Specify the process group IDs of running processes for which to get or set th…'
complete -c ionice -s t -l ignore --description 'Ignore failure to set the requested priority.'
complete -c ionice -s h -l help --description 'Display help text and exit.'
complete -c ionice -s u -l uid --description 'Specify the user IDs of running processes for which to get or set the schedul…'
complete -c ionice -s V -l version --description 'Display version information and exit.  EXAMPLES # ionice -c 3 -p 89.'

