# ip-address
# Autogenerated from man page /usr/share/man/man8/ip-address.8.gz
complete -c ip-address -o tentative --description '(IPv6 only) only list addresses which are not in the process of duplicate add…'
complete -c ip-address -o deprecated --description '(IPv6 only) only list addresses not being deprecated.'
complete -c ip-address -o dadfailed --description '(IPv6 only) only list addresses which have not failed duplicate address detec…'
complete -c ip-address -o statistics --description 'option, the command becomes verbose.'

