# ip-monitor
# Autogenerated from man page /usr/share/man/man8/ip-monitor.8.gz
complete -c ip-monitor -s t -o timestamp --description 'Prints timestamp before the event message on the separated line in format:   …'
complete -c ip-monitor -o ts -o tshort --description 'Prints short timestamp before the event message on the same line in format:  …'

