# iptables-xml
# Autogenerated from man page /usr/share/man/man1/iptables-xml.1.gz
complete -c iptables-xml -s c -l combine --description 'combine consecutive rules with the same matches but different targets.'
complete -c iptables-xml -s v -l verbose --description 'Output xml comments containing the iptables line from which the XML is derive…'

