# ir-keytable
# Autogenerated from man page /usr/share/man/man1/ir-keytable.1.gz
complete -c ir-keytable -s a -l auto-load --description 'Auto-load a table, based on a configuration file.  Only works with sysdev.'
complete -c ir-keytable -s c -l clear --description 'clears the old table.'
complete -c ir-keytable -s d -l device --description 'ir device to control.'
complete -c ir-keytable -s D -l delay --description 'Sets the delay before repeating a keystroke.'
complete -c ir-keytable -s k -l set-key --description 'Change scan/key pairs.'
complete -c ir-keytable -s p -l protocol --description 'Protocol to enable (the other ones will be disabled).'
complete -c ir-keytable -s P -l 'period\\' --description 'Sets the period to repeat a keystroke.'
complete -c ir-keytable -s r -l read --description 'reads the current scancode/keycode table.'
complete -c ir-keytable -s s -l sysdev --description 'ir class device to control.'
complete -c ir-keytable -s t -l test --description 'test if IR is generating events.'
complete -c ir-keytable -s v -l verbose --description 'enables debug messages.'
complete -c ir-keytable -s w -l write --description 'write (adds) the scancodes to the device scancode/keycode table from the spec…'
complete -c ir-keytable -s '?' -l help --description 'Prints the help message.'
complete -c ir-keytable -l usage --description 'Give a short usage message.'
complete -c ir-keytable -s V -l version --description 'print the v4l2-utils version .'
complete -c ir-keytable -l period --description 'Sets the period to repeat a keystroke.'

