# iwlist
# Autogenerated from man page /usr/share/man/man8/iwlist.8.gz
complete -c iwlist -l version --description 'Display the version of the tools, as well as the recommended and current Wire…'
complete -c iwlist -l help --description 'Display short help message.'

