# jfs_logdump
# Autogenerated from man page /usr/share/man/man8/jfs_logdump.8.gz
complete -c jfs_logdump -s a --description 'Dump the entire contents of the journal log instead of just the committed tra…'
complete -c jfs_logdump -s v --description 'option on the JFS device.'

