# jfs_debugfs
# Autogenerated from man page /usr/share/man/man8/jfs_debugfs.8.gz
complete -c jfs_debugfs -s v --description 'and.'
complete -c jfs_debugfs -s n --description 'options on the JFS device.'

