# jobs
# Autogenerated from man page /usr/share/man/man1/jobs.1p.gz
complete -c jobs -s l --description '(The letter ell. ) Provide more information about each job listed.'
complete -c jobs -s p --description 'Display only the process IDs for the process group leaders of the selected jo…'
complete -c jobs -s n --description 'option was included to ``Display the status of jobs that have changed, exited…'

