# json-glib-format
# Autogenerated from man page /usr/share/man/man1/json-glib-format.1.gz
complete -c json-glib-format -s h -l help --description '.'
complete -c json-glib-format -s p -l prettify --description '.'
complete -c json-glib-format -l indent-spaces --description '.'

