# kbdrate
# Autogenerated from man page /usr/share/man/man8/kbdrate.8.gz
complete -c kbdrate -s s --description 'Silent.   No messages are printed.'
complete -c kbdrate -s r --description 'Change the keyboard repeat rate to  rate cps.'
complete -c kbdrate -s d --description 'Change the delay to  delay milliseconds.'
complete -c kbdrate -s V -l version --description 'Display a version number and exit.'

