# kdestroy
# Autogenerated from man page /usr/share/man/man1/kdestroy.1.gz
complete -c kdestroy -s A --description 'Destroys all caches in the collection, if a cache collection is available.'
complete -c kdestroy -s q --description 'Run quietly.'
complete -c kdestroy -s c --description 'Use cache_name as the credentials (ticket) cache name and location; if this o…'

