# klist
# Autogenerated from man page /usr/share/man/man1/klist.1.gz
complete -c klist -s e --description 'Displays the encryption types of the session key and the ticket for each cred…'
complete -c klist -s l --description 'If a cache collection is available, displays a table summarizing the caches p…'
complete -c klist -s A --description 'If a cache collection is available, displays the contents of all of the cache…'
complete -c klist -s c --description 'List tickets held in a credentials cache.'
complete -c klist -s f --description 'Shows the flags present in the credentials, using the following abbreviations…'
complete -c klist -s s --description 'Causes klist to run silently (produce no output).'
complete -c klist -s a --description 'Display list of addresses in credentials.'
complete -c klist -s n --description 'Show numeric addresses instead of reverse-resolving addresses.'
complete -c klist -s C --description 'List configuration data that has been stored in the credentials cache when kl…'
complete -c klist -s k --description 'List keys held in a keytab file.'
complete -c klist -s i --description 'In combination with -k, defaults to using the default client keytab instead o…'
complete -c klist -s t --description 'Display the time entry timestamps for each keytab entry in the keytab file.'
complete -c klist -s K --description 'Display the value of the encryption key in each keytab entry in the keytab fi…'
complete -c klist -s V --description 'Display the Kerberos version number and exit.'

