# kmod
# Autogenerated from man page /usr/share/man/man8/kmod.8.gz
complete -c kmod -s V -l version --description 'Show the program version and exit.'
complete -c kmod -s h -l help --description 'Show the help message.'

