# kpropd
# Autogenerated from man page /usr/share/man/man8/kpropd.8.gz
complete -c kpropd -s r --description 'Specifies the realm of the master server.'
complete -c kpropd -s A --description 'Specifies the server to be contacted for incremental updates; by default, the…'
complete -c kpropd -s f --description 'Specifies the filename where the dumped principal database file is to be stor…'
complete -c kpropd -s p --description 'Allows the user to specify the pathname to the kdb5_util(8) program; by defau…'
complete -c kpropd -s d --description 'Turn on debug mode.'
complete -c kpropd -s t --description 'In standalone mode without incremental propagation, exit after one dump file …'
complete -c kpropd -s P --description 'Allow for an alternate port number for kpropd to listen on.'
complete -c kpropd -s a --description 'Allows the user to specify the path to the kpropd.'
complete -c kpropd -l pid-file --description 'In standalone mode, write the process ID of the daemon into pid_file.'

