# kprop
# Autogenerated from man page /usr/share/man/man8/kprop.8.gz
complete -c kprop -s r --description 'Specifies the realm of the master server.'
complete -c kprop -s f --description 'Specifies the filename where the dumped principal database file is to be foun…'
complete -c kprop -s P --description 'Specifies the port to use to contact the kpropd(8) server on the remote host.'
complete -c kprop -s d --description 'Prints debugging information.'
complete -c kprop -s s --description 'Specifies the location of the keytab file.'

