# ksu
# Autogenerated from man page /usr/share/man/man1/ksu.1.gz
complete -c ksu -s n --description 'Specify a Kerberos target principal name.'
complete -c ksu -s k --description 'Do not delete the target cache upon termination of the target shell or a comm…'
complete -c ksu -s z --description 'Restrict the copy of tickets from the source cache to the target cache to onl…'
complete -c ksu -s Z --description 'Don\\(aqt copy any tickets from the source cache to the target cache.'
complete -c ksu -s q --description 'Suppress the printing of status messages.'
complete -c ksu -s l -s r -o pf --description 'The ticket granting ticket options only apply to the case where there are no …'
complete -c ksu -s p --description 'specifies that the proxiable option should be requested for the ticket.'
complete -c ksu -s f --description 'option specifies that the forwardable option should be requested for the tick…'
complete -c ksu -s e --description 'ksu proceeds exactly the same as if it was invoked without the -e option, exc…'
complete -c ksu -s a --description 'Specify arguments to be passed to the target shell.'
complete -c ksu -s c --description 'Specify source cache name (e. g. , -c FILE:/tmp/my_cache).   If.'

