# libinput-measure-trackpoint-range
# Autogenerated from man page /usr/share/man/man1/libinput-measure-trackpoint-range.1.gz
complete -c libinput-measure-trackpoint-range -l help --description 'Print help LIBINPUT Part of the libinput(1) suite.'

