# libtoolize
# Autogenerated from man page /usr/share/man/man1/libtoolize.1.gz
complete -c libtoolize -s c -l copy --description 'copy files rather than symlinking them.'
complete -c libtoolize -l debug --description 'enable verbose shell tracing.'
complete -c libtoolize -s n -l dry-run --description 'print commands rather than running them.'
complete -c libtoolize -s f -l force --description 'replace existing files.'
complete -c libtoolize -s i -l install --description 'copy missing auxiliary files.'
complete -c libtoolize -l ltdl --description 'install libltdl sources [default: libltdl].'
complete -c libtoolize -l no-warnings --description 'equivalent to \'-Wnone\'.'
complete -c libtoolize -l nonrecursive --description 'prepare ltdl for non-recursive make.'
complete -c libtoolize -s q -l quiet --description 'work silently.'
complete -c libtoolize -l recursive --description 'prepare ltdl for recursive make.'
complete -c libtoolize -l subproject --description 'prepare ltdl to configure and build independently.'
complete -c libtoolize -s v -l verbose --description 'verbosely report processing.'
complete -c libtoolize -l version --description 'print version information and exit.'
complete -c libtoolize -s W -l warnings --description 'report the warnings falling in CATEGORY [all].'
complete -c libtoolize -s h -l help --description 'print short or long help message . SS "Warning categories include:".'

