# ln
# Autogenerated from man page /usr/share/man/man1/ln.1.gz
complete -c ln -l backup --description 'make a backup of each existing destination file.'
complete -c ln -s b --description 'like --backup but does not accept an argument.'
complete -c ln -s d -s F -l directory --description 'allow the superuser to attempt to hard link directories (note: will probably …'
complete -c ln -s f -l force --description 'remove existing destination files.'
complete -c ln -s i -l interactive --description 'prompt whether to remove destinations.'
complete -c ln -s L -l logical --description 'dereference TARGETs that are symbolic links.'
complete -c ln -s n -l no-dereference --description 'treat LINK_NAME as a normal file if it is a symbolic link to a directory.'
complete -c ln -s P -l physical --description 'make hard links directly to symbolic links.'
complete -c ln -s r -l relative --description 'create symbolic links relative to link location.'
complete -c ln -s s -l symbolic --description 'make symbolic links instead of hard links.'
complete -c ln -s S -l suffix --description 'override the usual backup suffix.'
complete -c ln -s t -l target-directory --description 'specify the DIRECTORY in which to create the links.'
complete -c ln -s T -l no-target-directory --description 'treat LINK_NAME as a normal file always.'
complete -c ln -s v -l verbose --description 'print name of each linked file.'
complete -c ln -l help --description 'display this help and exit.'
complete -c ln -l version --description 'output version information and exit .'

