# loadunimap
# Autogenerated from man page /usr/share/man/man8/loadunimap.8.gz
complete -c loadunimap -s o --description 'oldmap option is given, the old map is saved in the file specified.'
complete -c loadunimap -s C --description 'option.'

