# login
# Autogenerated from man page /usr/share/man/man1/login.1.gz
complete -c login -s p --description 'Used by  getty (8) to tell  login not to destroy the environment.'
complete -c login -s f --description 'Used to skip a second login authentication.'
complete -c login -s h --description 'Used by other servers (i. e.'
complete -c login -s H --description 'Used by other servers (i. e.'
complete -c login -l help --description 'Display help text and exit.'
complete -c login -s V -l version --description 'Display version information and exit.'

