# logrotate
# Autogenerated from man page /usr/share/man/man8/logrotate.8.gz
complete -c logrotate -s '?' -l help --description 'Prints help message.'
complete -c logrotate -s d -l debug --description 'Turn on debug mode, which means that no changes are made to the logs and the …'
complete -c logrotate -s f -l force --description 'Tells logrotate to force the rotation, even if it doesn\'t think this is neces…'
complete -c logrotate -s l -l log --description 'Tells logrotate to log verbose output into the log_file.'
complete -c logrotate -s m -l mail --description 'Tells logrotate which command to use when mailing logs.'
complete -c logrotate -s s -l state --description 'Tells logrotate to use an alternate state file.'
complete -c logrotate -l usage --description 'Prints a short usage message.'
complete -c logrotate -s v --description '.'
complete -c logrotate -l verbose --description 'Turns on verbose mode, for example to display messages during rotation.'

