# look
# Autogenerated from man page /usr/share/man/man1/look.1.gz
complete -c look -s a -l alternative --description 'Use the alternative dictionary file.'
complete -c look -s d -l alphanum --description 'Use normal dictionary character set and order, i. e.'
complete -c look -s f -l ignore-case --description 'Ignore the case of alphabetic characters.'
complete -c look -s t -l terminate --description 'Specify a string termination character, i. e.'
complete -c look -s V -l version --description 'Display version information and exit.'
complete -c look -s h -l help --description 'Display help text and exit.'

