# lookbib
# Autogenerated from man page /usr/share/man/man1/lookbib.1.gz
complete -c lookbib -s v --description 'Print the version number.'
complete -c lookbib -s i --description 'When searching files for which no index exists, ignore the contents of fields…'
complete -c lookbib -s t --description 'Only require the first n characters of keys to be given.  Initially n is 6.'

