# lp
# Autogenerated from man page /usr/share/man/man1/lp.1p.gz
complete -c lp -s o --description 'option values.'
complete -c lp -s c --description 'Exit only after further access to any of the input files is no longer require…'
complete -c lp -s d --description 'Specify a string that names the destination (c dest ).'
complete -c lp -s m --description 'Send mail (see mailx) after the files have been printed.'
complete -c lp -s n --description 'Write copies number of copies of the files, where copies is a positive decima…'
complete -c lp -s s --description 'Suppress messages from lp .'
complete -c lp -s t --description 'Write title on the banner page of the output.'
complete -c lp -s w --description 'Write a message on the user\'s terminal after the files have been printed.'

