# ls
# Autogenerated from man page /usr/share/man/man1/ls.1p.gz
complete -c ls -o laRF --description 'in the POSIX locale: total 11 drwxr-xr-x   3 fox      prog          64 Jul  4…'
complete -c ls -o rwxr--r-- --description '.'
complete -c ls -o rw-r--r-- --description 'RATIONALE Some historical implementations of the ls utility show all entries …'

