# lsattr
# Autogenerated from man page /usr/share/man/man1/lsattr.1.gz
complete -c lsattr -s R --description 'Recursively list attributes of directories and their contents.'
complete -c lsattr -s V --description 'Display the program version.'
complete -c lsattr -s a --description 'List all files in directories, including files that start with `. \'.'
complete -c lsattr -s d --description 'List directories like other files, rather than listing their contents.'
complete -c lsattr -s l --description 'Print the options using long names instead of single character abbreviations.'
complete -c lsattr -s p --description 'List the file\'s project number.'
complete -c lsattr -s v --description 'List the file\'s version/generation number.'

