# lsinitcpio
# Autogenerated from man page /usr/share/man/man1/lsinitcpio.1.gz
complete -c lsinitcpio -s h -l help --description 'Output a short overview of available command-line switches.'
complete -c lsinitcpio -s n -l nocolor --description 'Disable color output.'
complete -c lsinitcpio -s V -l version --description 'Display version information.'
complete -c lsinitcpio -s v -l verbose --description 'Be more verbose.'
complete -c lsinitcpio -s a -l analyze --description '.'
complete -c lsinitcpio -s c -l config --description '.'
complete -c lsinitcpio -s l -l list --description '.'
complete -c lsinitcpio -s x -l extract --description '.'

