# lslocks
# Autogenerated from man page /usr/share/man/man8/lslocks.8.gz
complete -c lslocks -s i -l noinaccessible --description 'Ignore lock files which are inaccessible for the current user.'
complete -c lslocks -s J -l json --description 'Use JSON output format.'
complete -c lslocks -s n -l noheadings --description 'Do not print a header line.'
complete -c lslocks -s o -l output --description 'Specify which output columns to print.'
complete -c lslocks -s p -l pid --description 'Display only the locks held by the process with this pid.'
complete -c lslocks -s r -l raw --description 'Use the raw output format.'
complete -c lslocks -s u -l notruncate --description 'Do not truncate text in columns.'
complete -c lslocks -s V -l version --description 'Display version information and exit.'
complete -c lslocks -l help --description 'to get a list of all supported columns.'
complete -c lslocks -s h --description 'Display help text and exit.'

