# lsmem
# Autogenerated from man page /usr/share/man/man1/lsmem.1.gz
complete -c lsmem -s a -l all --description 'List each individual memory block, instead of combining memory blocks with si…'
complete -c lsmem -s b -l bytes --description 'Print the SIZE column in bytes rather than in a human-readable format.'
complete -c lsmem -s h -l help --description 'Display help text and exit.'
complete -c lsmem -s J -l json --description 'Use JSON output format.'
complete -c lsmem -s n -l noheadings --description 'Do not print a header line.'
complete -c lsmem -s o -l output --description 'Specify which output columns to print.'
complete -c lsmem -s P -l pairs --description 'Produce output in the form of key="value" pairs.'
complete -c lsmem -s r -l raw --description 'Produce output in raw format.'
complete -c lsmem -s S -l split --description 'Specify which columns (attributes) use to split memory blocks to ranges.'
complete -c lsmem -s s -l sysroot --description 'Gather memory data for a Linux instance other than the instance from which th…'
complete -c lsmem -s V -l version --description 'Display version information and exit.'
complete -c lsmem -l summary --description 'This option controls summary lines output.'

