# lsns
# Autogenerated from man page /usr/share/man/man8/lsns.8.gz
complete -c lsns -s J -l json --description 'Use JSON output format.'
complete -c lsns -s l -l list --description 'Use list output format.'
complete -c lsns -s n -l noheadings --description 'Do not print a header line.'
complete -c lsns -s o -l output --description 'Specify which output columns to print.'
complete -c lsns -s p -l task --description 'Display only the namespaces held by the process with this pid.'
complete -c lsns -s r -l raw --description 'Use the raw output format.'
complete -c lsns -s t -l type --description 'Display the specified type of namespaces only.'
complete -c lsns -s u -l notruncate --description 'Do not truncate text in columns.'
complete -c lsns -s W -l nowrap --description 'Do not use multi-line text in columns.'
complete -c lsns -s V -l version --description 'Display version information and exit.'
complete -c lsns -s h -l help --description 'Display help text and exit.'

