# lsusb
# Autogenerated from man page /usr/share/man/man8/lsusb.8.gz
complete -c lsusb -s v -l verbose --description 'Tells  lsusb to be verbose and display detailed information about the devices…'
complete -c lsusb -s s --description 'Show only devices in specified  bus and/or  devnum.'
complete -c lsusb -s d --description 'Show only devices with the specified vendor and product ID.'
complete -c lsusb -s D --description 'Do not scan the /dev/bus/usb directory, instead display only information abou…'
complete -c lsusb -s t --description 'Tells  lsusb to dump the physical USB device hierarchy as a tree.'
complete -c lsusb -s V -l version --description 'Print  version information on standard output, then exit successfully.'

