# lua
# Autogenerated from man page /usr/share/man/man1/lua.1.gz
complete -c lua -s e --description 'execute statement R stat .'
complete -c lua -s i --description 'enter interactive mode after executing R script .'
complete -c lua -s l --description 'execute the equivalent of B name =require(\' name \') before executing R script…'
complete -c lua -s v --description 'show version information.'
complete -c lua -s E --description 'ignore environment variables.'

