# lvmetad
# Autogenerated from man page /usr/share/man/man8/lvmetad.8.gz
complete -c lvmetad -s f --description 'Don\'t fork, but run in the foreground.'
complete -c lvmetad -s h -s '?' --description 'Show help information.'
complete -c lvmetad -s l --description 'Specify the levels of log messages to generate as a comma separated list.'
complete -c lvmetad -s p --description 'Path to the pidfile.  This overrides both the built-in default (/run/lvmetad.'
complete -c lvmetad -s s --description 'Path to the socket file.'
complete -c lvmetad -s t --description 'The daemon may shutdown after being idle for the given time (in seconds).'
complete -c lvmetad -s V --description 'Display the version of lvmetad daemon.  ENVIRONMENT VARIABLES.'

