# Magick++-config
# Autogenerated from man page /usr/share/man/man1/Magick++-config.1.gz
complete -c Magick++-config -l cppflags --description 'Print the preprocessor flags that are needed to find the  ImageMagick C and C…'
complete -c Magick++-config -l cxxflags --description 'Print the compiler flags that were used to compile   libMagick++ .'
complete -c Magick++-config -l exec-prefix --description 'Print the directory under which target specific binaries and executables are …'
complete -c Magick++-config -l ldflags --description 'Print the linker flags that are needed to link with the  libMagick++ library.'
complete -c Magick++-config -l libs --description 'Print the linker flags that are needed to link a program with  libMagick++ .'
complete -c Magick++-config -l prefix --description 'Print the directory under which the package is installed.'
complete -c Magick++-config -l version --description 'Print the version of the ImageMagick distribution to standard output.'

