# makeconv
# Autogenerated from man page /usr/share/man/man1/makeconv.1.gz
complete -c makeconv -s h -s '?' -l help --description 'Print help about usage and exit.'
complete -c makeconv -s c -l copyright --description 'Include a copyright notice in the binary data.'
complete -c makeconv -s v -l verbose --description 'Display extra informative messages during execution.'
complete -c makeconv -s d -l destdir --description 'Set the destination directory to destination .'

