# mandb
# Autogenerated from man page /usr/share/man/man8/mandb.8.gz
complete -c mandb -s d -l debug --description 'Print debugging information.'
complete -c mandb -s q -l quiet --description 'Produce no warnings.'
complete -c mandb -s s -l no-straycats --description 'Do not spend time looking for or adding information to the databases regardin…'
complete -c mandb -s p -l no-purge --description 'Do not spend time checking for deleted manual pages and purging them from the…'
complete -c mandb -s c -l create --description 'By default,   mandb will try to update any previously created databases.'
complete -c mandb -s u -l user-db --description 'Create user databases only, even with write permissions necessary to create s…'
complete -c mandb -s t -l test --description 'Perform correctness checks on manual pages in the hierarchy search path.'
complete -c mandb -s f -l filename --description 'Update only the entries for the given filename.'
complete -c mandb -s C -l config-file --description 'Use this user configuration file rather than the default of R ~/. manpath .'
complete -c mandb -s '?' -l help --description 'Show the usage message, then exit.'
complete -c mandb -l usage --description 'Print a short usage message and exit.'
complete -c mandb -s V -l version --description 'Show the version, then exit.  EXIT STATUS.'

