# mcookie
# Autogenerated from man page /usr/share/man/man1/mcookie.1.gz
complete -c mcookie -s f -l file --description 'Use this file as an additional source of randomness (for example /dev/urandom…'
complete -c mcookie -s m -l max-size --description 'Read from file only this number of bytes.'
complete -c mcookie -s v -l verbose --description 'Inform where randomness originated, with amount of entropy read from each sou…'
complete -c mcookie -s V -l version --description 'Display version information and exit.'
complete -c mcookie -s h -l help --description 'Display help text and exit.'

