# md5sum
# Autogenerated from man page /usr/share/man/man1/md5sum.1.gz
complete -c md5sum -s b -l binary --description 'read in binary mode.'
complete -c md5sum -s c -l check --description 'read MD5 sums from the FILEs and check them.'
complete -c md5sum -l tag --description 'create a BSD-style checksum.'
complete -c md5sum -s t -l text --description 'read in text mode (default) .'
complete -c md5sum -l ignore-missing --description 'don\'t fail or report status for missing files.'
complete -c md5sum -l quiet --description 'don\'t print OK for each successfully verified file.'
complete -c md5sum -l status --description 'don\'t output anything, status code shows success.'
complete -c md5sum -l strict --description 'exit non-zero for improperly formatted checksum lines.'
complete -c md5sum -s w -l warn --description 'warn about improperly formatted checksum lines.'
complete -c md5sum -l help --description 'display this help and exit.'
complete -c md5sum -l version --description 'output version information and exit.'

