# memusagestat
# Autogenerated from man page /usr/share/man/man1/memusagestat.1.gz
complete -c memusagestat -s o -l output --description 'Name of the output file.'
complete -c memusagestat -s s -l string --description 'Use  string as the title inside the output graph.'
complete -c memusagestat -s t -l time --description 'Use time (rather than number of function calls) as the scale for the X axis.'
complete -c memusagestat -s T -l total --description 'Also draw a graph of total memory consumption.'
complete -c memusagestat -s x -l x-size --description 'Make the output graph  size pixels wide.'
complete -c memusagestat -s y -l y-size --description 'Make the output graph  size pixels high.'
complete -c memusagestat -s '?' -l help --description 'Print a help message and exit.'
complete -c memusagestat -l usage --description 'Print a short usage message and exit.'
complete -c memusagestat -s d --description '(or.'
complete -c memusagestat -l data --description 'option of memusage (1).'
complete -c memusagestat -s V -l version --description 'Print version information and exit.'

