# mesg
# Autogenerated from man page /usr/share/man/man1/mesg.1.gz
complete -c mesg -s v -l verbose --description 'Explain what is being done.'
complete -c mesg -s V -l version --description 'Display version information and exit.'
complete -c mesg -s h -l help --description 'Display help text and exit.'

