# mkdir
# Autogenerated from man page /usr/share/man/man1/mkdir.1.gz
complete -c mkdir -s m -l mode --description 'set file mode (as in chmod), not a=rwx - umask.'
complete -c mkdir -s p -l parents --description 'no error if existing, make parent directories as needed.'
complete -c mkdir -s v -l verbose --description 'print a message for each created directory.'
complete -c mkdir -s Z --description 'set SELinux security context of each created directory to the default type.'
complete -c mkdir -l context --description 'like -Z, or if CTX is specified then set the SELinux or SMACK security contex…'
complete -c mkdir -l help --description 'display this help and exit.'
complete -c mkdir -l version --description 'output version information and exit AUTHOR Written by David MacKenzie.'

