# mkfs
# Autogenerated from man page /usr/share/man/man8/mkfs.xfs.8.gz
complete -c mkfs -s K --description 'Do not attempt to discard blocks at mkfs time.'
complete -c mkfs -o bcdpl --description 'A file may be a regular file, a block special file, a character special file,…'

