# mkswap
# Autogenerated from man page /usr/share/man/man8/mkswap.8.gz
complete -c mkswap -s c -l check --description 'Check the device (if it is a block device) for bad blocks before creating the…'
complete -c mkswap -s f -l force --description 'Go ahead even if the command is stupid.'
complete -c mkswap -s L -l label --description 'Specify a label for the device, to allow  swapon by label.'
complete -c mkswap -s p -l pagesize --description 'Specify the page size (in bytes) to use.'
complete -c mkswap -s U -l uuid --description 'Specify the UUID to use.   The default is to generate a UUID.'
complete -c mkswap -s v -l swapversion --description 'Specify the swap-space version.'
complete -c mkswap -s h -l help --description 'Display help text and exit.'
complete -c mkswap -s V -l version --description 'Display version information and exit.'

