# mmroff
# Autogenerated from man page /usr/share/man/man1/mmroff.1.gz
complete -c mmroff -s z --description 'and.'
complete -c mmroff -o rRef --description 'to collect all cross references and then to do the real processing when the c…'
complete -c mmroff -s x --description 'Just create the cross reference file.'

