# msgcmp
# Autogenerated from man page /usr/share/man/man1/msgcmp.1.gz
complete -c msgcmp -s D -l directory --description 'add DIRECTORY to list for input files search . SS "Operation modifiers:".'
complete -c msgcmp -s m -l multi-domain --description 'apply ref. pot to each of the domains in def. po.'
complete -c msgcmp -s N -l no-fuzzy-matching --description 'do not use fuzzy matching.'
complete -c msgcmp -l use-fuzzy --description 'consider fuzzy entries.'
complete -c msgcmp -l use-untranslated --description 'consider untranslated entries . SS "Input file syntax:".'
complete -c msgcmp -s P -l properties-input --description 'input files are in Java . properties syntax.'
complete -c msgcmp -l stringtable-input --description 'input files are in NeXTstep/GNUstep . strings syntax .'
complete -c msgcmp -s h -l help --description 'display this help and exit.'
complete -c msgcmp -s V -l version --description 'output version information and exit AUTHOR Written by Peter Miller.'

