# ncursesw6-config
# Autogenerated from man page /usr/share/man/man1/ncursesw6-config.1.gz
complete -c ncursesw6-config -l prefix --description 'echos the package-prefix of ncurses.'
complete -c ncursesw6-config -l exec-prefix --description 'echos the executable-prefix of ncurses.'
complete -c ncursesw6-config -l cflags --description 'echos the C compiler flags needed to compile with ncurses.'
complete -c ncursesw6-config -l libs --description 'echos the libraries needed to link with ncurses.'
complete -c ncursesw6-config -l version --description 'echos the release+patchdate version of ncurses.'
complete -c ncursesw6-config -l abi-version --description 'echos the ABI version of ncurses.'
complete -c ncursesw6-config -l mouse-version --description 'echos the mouse-interface version of ncurses.'
complete -c ncursesw6-config -l bindir --description 'echos the directory containing ncurses programs.'
complete -c ncursesw6-config -l datadir --description 'echos the directory containing ncurses data.'
complete -c ncursesw6-config -l includedir --description 'echos the directory containing ncurses header files.'
complete -c ncursesw6-config -l libdir --description 'echos the directory containing ncurses libraries.'
complete -c ncursesw6-config -l mandir --description 'echos the directory containing ncurses manpages.'
complete -c ncursesw6-config -l terminfo --description 'echos the $TERMINFO terminfo database path, e. g. , . RS /usr/share/terminfo .'
complete -c ncursesw6-config -l terminfo-dirs --description 'echos the $TERMINFO_DIRS directory list, e. g. , . RS /usr/share/terminfo .'
complete -c ncursesw6-config -l termpath --description 'echos the $TERMPATH termcap list, if support for termcap is configured.'
complete -c ncursesw6-config -l help --description 'prints this message SEE ALSO curses(3X).'

