# ngettext
# Autogenerated from man page /usr/share/man/man1/ngettext.1.gz
complete -c ngettext -s d -l domain --description 'retrieve translated message from TEXTDOMAIN.'
complete -c ngettext -s e --description 'enable expansion of some escape sequences.'
complete -c ngettext -s E --description '(ignored for compatibility).'
complete -c ngettext -s h -l help --description 'display this help and exit.'
complete -c ngettext -s V -l version --description 'display version information and exit.'

