# nice
# Autogenerated from man page /usr/share/man/man1/nice.1p.gz
complete -c nice -s x --description 'utility , for example, would be treated the same as the command nice.'
complete -c nice -l 1 --description 'utility .'
complete -c nice -s 0 --description 'utility , while 4.'

