# nl-pktloc-lookup
# Autogenerated from man page /usr/share/man/man8/nl-pktloc-lookup.8.gz
complete -c nl-pktloc-lookup -s h -l help --description 'Print help text to console and exit.'
complete -c nl-pktloc-lookup -s v -l version --description 'Print versioning information to console and exit.'
complete -c nl-pktloc-lookup -s l -l list --description 'List all packet location definitions.'
complete -c nl-pktloc-lookup -l u32 --description 'Prints the packet location definition in a special format that is understood …'

