# nm
# Autogenerated from man page /usr/share/man/man1/nm.1p.gz
complete -c nm -s A --description 'Write the full pathname or library name of an object on each line.'
complete -c nm -s e --description 'Write only external (global) and static symbol information.'
complete -c nm -s f --description 'Produce full output.  Write redundant symbols (c . text , . data , and .'
complete -c nm -s g --description 'Write only external (global) symbol information.'
complete -c nm -s o --description 'Write numeric values in octal (equivalent to.'
complete -c nm -s t --description '.'
complete -c nm -s P --description 'Write information in a portable output format, as specified in the STDOUT sec…'
complete -c nm -s u --description 'Write only undefined symbols.'
complete -c nm -s v --description 'Sort output by value instead of by symbol name.'
complete -c nm -s x --description 'Write numeric values in hexadecimal (equivalent to.'
complete -c nm -s d --description '.'

