# nohup
# Autogenerated from man page /usr/share/man/man1/nohup.1.gz
complete -c nohup -l help --description 'display this help and exit.'
complete -c nohup -l version --description 'output version information and exit.'

