# nologin
# Autogenerated from man page /usr/share/man/man8/nologin.8.gz
complete -c nologin -s h -l help --description 'Display help text and exit.'
complete -c nologin -s V -l version --description 'Display version information and exit.'

