# nseq
# Autogenerated from man page /usr/share/man/man1/nseq.1ssl.gz
complete -c nseq -o help --description 'Print out a usage message.'
complete -c nseq -o in --description 'This specifies the input filename to read or standard input if this option is…'
complete -c nseq -o out --description 'specifies the output filename or standard output by default.'

