# ocsptool
# Autogenerated from man page /usr/share/man/man1/ocsptool.1.gz
complete -c ocsptool -s i -l request-info --description 'The -Q parameter specify the name of the file containing the OCSP request, an…'
complete -c ocsptool -l no-nonce --description 'Verify signature in OCSP response To verify the signature in an OCSP response…'
complete -c ocsptool -l verify-response --description 'OCSP response in DER format from standard input, or from the file specified b…'
complete -c ocsptool -l load-trust --description 'in PEM format.'
complete -c ocsptool -l load-signer --description 'one certificate and it will be used to verify the signature in the OCSP respo…'

