# od
# Autogenerated from man page /usr/share/man/man1/od.1p.gz
complete -c od -o bcdosx --description 'options is significant.'
complete -c od -o bcdostx --description 'options.'
complete -c od -s n --description 'respectively, for the.'

