# openssl-passwd
# Autogenerated from man page /usr/share/man/man1/openssl-passwd.1ssl.gz
complete -c openssl-passwd -o help --description 'Print out a usage message.'
complete -c openssl-passwd -o crypt --description 'Use the crypt algorithm (default).'
complete -c openssl-passwd -s 1 --description 'Use the \\s-1MD5\\s0 based \\s-1BSD\\s0 password algorithm 1.'
complete -c openssl-passwd -o apr1 --description 'Use the apr1 algorithm (Apache variant of the \\s-1BSD\\s0 algorithm).'
complete -c openssl-passwd -o salt --description 'Use the specified salt.'
complete -c openssl-passwd -o in --description 'Read passwords from file.'
complete -c openssl-passwd -o stdin --description 'Read passwords from stdin.'
complete -c openssl-passwd -o noverify --description 'Don\'t verify when reading a password from the terminal.'
complete -c openssl-passwd -o quiet --description 'Don\'t output warnings when passwords given at the command line are truncated.'

