# openssl-pkcs7
# Autogenerated from man page /usr/share/man/man1/openssl-pkcs7.1ssl.gz
complete -c openssl-pkcs7 -o help --description 'Print out a usage message.'
complete -c openssl-pkcs7 -o inform --description 'This specifies the input format.'
complete -c openssl-pkcs7 -o outform --description 'This specifies the output format, the options have the same meaning as the -i…'
complete -c openssl-pkcs7 -o in --description 'This specifies the input filename to read from or standard input if this opti…'
complete -c openssl-pkcs7 -o out --description 'specifies the output filename to write to or standard output by default.'
complete -c openssl-pkcs7 -o print_certs --description 'prints out any certificates or CRLs contained in the file.'
complete -c openssl-pkcs7 -o text --description 'prints out certificates details in full rather than just subject and issuer n…'
complete -c openssl-pkcs7 -o noout --description 'don\'t output the encoded version of the PKCS#7 structure (or certificates is …'

