# openssl-nseq
# Autogenerated from man page /usr/share/man/man1/openssl-nseq.1ssl.gz
complete -c openssl-nseq -o help --description 'Print out a usage message.'
complete -c openssl-nseq -o in --description 'This specifies the input filename to read or standard input if this option is…'
complete -c openssl-nseq -o out --description 'specifies the output filename or standard output by default.'

