# openssl-pkey
# Autogenerated from man page /usr/share/man/man1/openssl-pkey.1ssl.gz
complete -c openssl-pkey -o help --description 'Print out a usage message.'
complete -c openssl-pkey -o inform --description 'This specifies the input format \\s-1DER\\s0 or \\s-1PEM. \\s0.'
complete -c openssl-pkey -o outform --description 'This specifies the output format, the options have the same meaning as the -i…'
complete -c openssl-pkey -o in --description 'This specifies the input filename to read a key from or standard input if thi…'
complete -c openssl-pkey -o passin --description 'the input file password source.'
complete -c openssl-pkey -o out --description 'This specifies the output filename to write a key to or standard output if th…'
complete -c openssl-pkey -o passout --description 'the output file password source.'
complete -c openssl-pkey -o traditional --description 'normally a private key is written using standard format: this is PKCS#8 form …'
complete -c openssl-pkey -o cipher --description 'These options encrypt the private key with the supplied cipher.'
complete -c openssl-pkey -o text --description 'prints out the various public or private key components in plain text in addi…'
complete -c openssl-pkey -o text_pub --description 'print out only public key components even if a private key is being processed.'
complete -c openssl-pkey -o noout --description 'do not output the encoded version of the key.'
complete -c openssl-pkey -o pubin --description 'by default a private key is read from the input file: with this option a publ…'
complete -c openssl-pkey -o pubout --description 'by default a private key is output: with this option a public key will be out…'

