# openssl-ecparam
# Autogenerated from man page /usr/share/man/man1/openssl-ecparam.1ssl.gz
complete -c openssl-ecparam -o help --description 'Print out a usage message.'
complete -c openssl-ecparam -o inform --description 'This specifies the input format.  The \\s-1DER\\s0 option uses an \\s-1ASN.'
complete -c openssl-ecparam -o outform --description 'This specifies the output format, the options have the same meaning as the -i…'
complete -c openssl-ecparam -o in --description 'This specifies the input filename to read parameters from or standard input i…'
complete -c openssl-ecparam -o out --description 'This specifies the output filename parameters to.'
complete -c openssl-ecparam -o noout --description 'This option inhibits the output of the encoded version of the parameters.'
complete -c openssl-ecparam -o text --description 'This option prints out the \\s-1EC\\s0 parameters in human readable form.'
complete -c openssl-ecparam -s C --description 'This option converts the \\s-1EC\\s0 parameters into C code.'
complete -c openssl-ecparam -o check --description 'Validate the elliptic curve parameters.'
complete -c openssl-ecparam -o name --description 'Use the \\s-1EC\\s0 parameters with the specified \'short\' name.'
complete -c openssl-ecparam -o list_curves --description 'If this options is specified ecparam will print out a list of all currently i…'
complete -c openssl-ecparam -o conv_form --description 'This specifies how the points on the elliptic curve are converted into octet …'
complete -c openssl-ecparam -o param_enc --description 'This specifies how the elliptic curve parameters are encoded.'
complete -c openssl-ecparam -o no_seed --description 'This option inhibits that the \'seed\' for the parameter generation is included…'
complete -c openssl-ecparam -o genkey --description 'This option will generate an \\s-1EC\\s0 private key using the specified parame…'
complete -c openssl-ecparam -o rand --description 'a file or files containing random data used to seed the random number generat…'

