# openssl-dsa
# Autogenerated from man page /usr/share/man/man1/openssl-dsa.1ssl.gz
complete -c openssl-dsa -o help --description 'Print out a usage message.'
complete -c openssl-dsa -o inform --description 'This specifies the input format.'
complete -c openssl-dsa -o outform --description 'This specifies the output format, the options have the same meaning as the -i…'
complete -c openssl-dsa -o in --description 'This specifies the input filename to read a key from or standard input if thi…'
complete -c openssl-dsa -o passin --description 'the input file password source.'
complete -c openssl-dsa -o out --description 'This specifies the output filename to write a key to or standard output by is…'
complete -c openssl-dsa -o passout --description 'the output file password source.'
complete -c openssl-dsa -o aes128 -o aes192 -o aes256 -o camellia128 -o camellia192 -o camellia256 -o des -o des3 -o idea --description 'These options encrypt the private key with the specified cipher before output…'
complete -c openssl-dsa -o text --description 'prints out the public, private key components and parameters.'
complete -c openssl-dsa -o noout --description 'this option prevents output of the encoded version of the key.'
complete -c openssl-dsa -o modulus --description 'this option prints out the value of the public key component of the key.'
complete -c openssl-dsa -o pubin --description 'by default a private key is read from the input file: with this option a publ…'
complete -c openssl-dsa -o pubout --description 'by default a private key is output.'

