# openssl-tsget
# Autogenerated from man page /usr/share/man/man1/openssl-tsget.1ssl.gz
complete -c openssl-tsget -s h --description 'The \\s-1URL\\s0 of the \\s-1HTTP/HTTPS\\s0 server listening for time stamp reque…'
complete -c openssl-tsget -s e --description 'If the -o option is not given this argument specifies the extension of the ou…'
complete -c openssl-tsget -s o --description 'This option can be specified only when just one request is sent to the server.'
complete -c openssl-tsget -s v --description 'The name of the currently processed request is printed on standard error.'
complete -c openssl-tsget -s d --description 'Switches on verbose mode for the underlying curl library.'
complete -c openssl-tsget -s k --description '(\\s-1HTTPS\\s0) In case of certificate-based client authentication over \\s-1HT…'
complete -c openssl-tsget -s p --description '(\\s-1HTTPS\\s0) Specifies the passphrase for the private key specified by the …'
complete -c openssl-tsget -s c --description '(\\s-1HTTPS\\s0) In case of certificate-based client authentication over \\s-1HT…'
complete -c openssl-tsget -s C --description '(\\s-1HTTPS\\s0) The trusted \\s-1CA\\s0 certificate store.'
complete -c openssl-tsget -s P --description '(\\s-1HTTPS\\s0) The path containing the trusted \\s-1CA\\s0 certificates to veri…'
complete -c openssl-tsget -o rand --description 'The files containing random data for seeding the random number generator.'
complete -c openssl-tsget -s g --description 'The name of an \\s-1EGD\\s0 socket to get random data from.  (Optional).'

