# openssl-speed
# Autogenerated from man page /usr/share/man/man1/openssl-speed.1ssl.gz
complete -c openssl-speed -o help --description 'Print out a usage message.'
complete -c openssl-speed -o engine --description 'specifying an engine (by its unique id string) will cause speed to attempt to…'
complete -c openssl-speed -o elapsed --description 'Measure time in real time instead of \\s-1CPU\\s0 time.'
complete -c openssl-speed -o evp --description 'Use the specified cipher or message digest algorithm via the \\s-1EVP\\s0 inter…'
complete -c openssl-speed -o decrypt --description 'Time the decryption instead of encryption.'

