# opj_decompress
# Autogenerated from man page /usr/share/man/man1/opj_decompress.1.gz
complete -c opj_decompress -s i --description '(jpeg2000 input file name).'
complete -c opj_decompress -s l --description 'n is the maximum number of quality layers to decode.  See LAYERS below).'
complete -c opj_decompress -s o --description '(output file name with extension).'
complete -c opj_decompress -s r --description '(n is the highest resolution level to be discarded.  See REDUCTION below).'
complete -c opj_decompress -s x --description '(use name as index file and fill it).'
complete -c opj_decompress -o ImgDir --description '(directory containing input files).'
complete -c opj_decompress -o OutFor --description '(extension for output files).'
complete -c opj_decompress -o jpip --description 'Embed index table box into the output JP2 file (compulsory for JPIP).'
complete -c opj_decompress -o TP --description 'Partition a tile into tile parts of different resolution levels (compulsory f…'
complete -c opj_decompress -s W --description '.'

