# opj_dump
# Autogenerated from man page /usr/share/man/man1/opj_dump.1.gz
complete -c opj_dump -s i --description '(jpeg2000 input file name).'
complete -c opj_dump -o ImgDir --description '(directory containing jpeg2000 input files) AUTHORS Copyright (c) 2010, Mathi…'

