# pactl
# Autogenerated from man page /usr/share/man/man1/pactl.1.gz
complete -c pactl -s h -l help --description 'Show help.'
complete -c pactl -l version --description 'Show version information.'
complete -c pactl -s s -l server --description 'Choose the server to connect to.'
complete -c pactl -s n -l client-name --description 'Specify the client name pactl shall pass to the server when connecting.'

