# pal2rgb
# Autogenerated from man page /usr/share/man/man1/pal2rgb.1.gz
complete -c pal2rgb -s C --description 'This option overrides the default behavior of  pal2rgb in determining whether…'
complete -c pal2rgb -s p --description 'Explicitly select the planar configuration used in organizing data samples in…'
complete -c pal2rgb -s c --description 'Use the specific compression algorithm to encoded image data in the output fi…'
complete -c pal2rgb -s r --description 'Explicitly specify the number of rows in each strip of the output file.'

