# pam_timestamp_check
# Autogenerated from man page /usr/share/man/man8/pam_timestamp_check.8.gz
complete -c pam_timestamp_check -s k --description 'Instead of checking the validity of a timestamp, remove it.'
complete -c pam_timestamp_check -s d --description 'Instead of returning validity using an exit status, loop indefinitely, pollin…'

