# panelctl
# Autogenerated from man page /usr/share/man/man1/panelctl.1.gz
complete -c panelctl -s c -l commands --description 'Print command list (requires a dummy argument).'
complete -c panelctl -s d -l debug --description 'Debug mode.'
complete -c panelctl -s g -l guid --description 'Specify GUID for the STB to control .'
complete -c panelctl -s s -l specid --description 'Specify spec_id of STB to control.'
complete -c panelctl -s v -l verbose --description 'Produce verbose output.'
complete -c panelctl -s '?' -l help --description 'Give this help list.'
complete -c panelctl -l usage --description 'Give a short usage message.'
complete -c panelctl -s n -l swversion --description '.'
complete -c panelctl -s V -l version --description 'Print program version.'

