# passwd
# Autogenerated from man page /usr/share/man/man1/passwd.1ssl.gz
complete -c passwd -o help --description 'Print out a usage message.'
complete -c passwd -o crypt --description 'Use the crypt algorithm (default).'
complete -c passwd -s 1 --description 'Use the \\s-1MD5\\s0 based \\s-1BSD\\s0 password algorithm 1.'
complete -c passwd -o apr1 --description 'Use the apr1 algorithm (Apache variant of the \\s-1BSD\\s0 algorithm).'
complete -c passwd -o salt --description 'Use the specified salt.'
complete -c passwd -o in --description 'Read passwords from file.'
complete -c passwd -o stdin --description 'Read passwords from stdin.'
complete -c passwd -o noverify --description 'Don\'t verify when reading a password from the terminal.'
complete -c passwd -o quiet --description 'Don\'t output warnings when passwords given at the command line are truncated.'

