# pax11publish
# Autogenerated from man page /usr/share/man/man1/pax11publish.1.gz
complete -c pax11publish -s h --description 'Show help.'
complete -c pax11publish -s d --description 'Read the PulseAudio server credentials currently set on the X11 root window a…'
complete -c pax11publish -s i --description 'Similar to -d, however dumps them in a Bourne shell compatible format so they…'
complete -c pax11publish -s e --description 'Export the currently locally used sound server, sink, source configuration to…'
complete -c pax11publish -s r --description 'Removes the configured PulseAudio configuration from the X11 root window.'
complete -c pax11publish -s D --description 'Connect to the specified X11 display, instead of the default one configured i…'
complete -c pax11publish -s S --description 'Only valid for -e: export the specified PulseAudio server as default to the X…'
complete -c pax11publish -s O --description 'Only valid for -e: export the specified sink as default sink to the X11 displ…'
complete -c pax11publish -s I --description 'Only valid for -e: export the specified source as default to the X11 display …'
complete -c pax11publish -s c --description 'Only valid for -e: export the PulseAudio authentication cookie stored in the …'

