# pcap-config
# Autogenerated from man page /usr/share/man/man1/pcap-config.1.gz
complete -c pcap-config -l cflags --description 'option, pcap-config writes to the standard output the.'
complete -c pcap-config -s I --description 'compiler flags required to include libpcap\'s header files.  When run with the.'
complete -c pcap-config -l libs --description 'option, pcap-config writes to the standard output the.'
complete -c pcap-config -s L --description 'and.'
complete -c pcap-config -s l --description 'linker flags required to link with libpcap, including.'
complete -c pcap-config -l additional-libs --description 'option, pcap-config writes to the standard output the.'
complete -c pcap-config -o lpcap --description 'flag to link with libpcap itself.'
complete -c pcap-config -l static --description 'flag causes it to write flags appropriate for compiling with a statically-lin…'

