# pcre-config
# Autogenerated from man page /usr/share/man/man1/pcre-config.1.gz
complete -c pcre-config -l prefix --description 'Writes the directory prefix used in the PCRE installation for architecture in…'
complete -c pcre-config -l exec-prefix --description 'Writes the directory prefix used in the PCRE installation for architecture de…'
complete -c pcre-config -l version --description 'Writes the version number of the installed PCRE libraries to the standard out…'
complete -c pcre-config -l libs --description 'Writes to the standard output the command line options required to link with …'
complete -c pcre-config -l libs16 --description 'Writes to the standard output the command line options required to link with …'
complete -c pcre-config -l libs32 --description 'Writes to the standard output the command line options required to link with …'
complete -c pcre-config -l libs-cpp --description 'Writes to the standard output the command line options required to link with …'
complete -c pcre-config -l libs-posix --description 'Writes to the standard output the command line options required to link with …'
complete -c pcre-config -l cflags --description 'Writes to the standard output the command line options required to compile fi…'
complete -c pcre-config -l cflags-posix --description 'Writes to the standard output the command line options required to compile fi…'

