# pdffonts
# Autogenerated from man page /usr/share/man/man1/pdffonts.1.gz
complete -c pdffonts -s f --description 'Specifies the first page to analyze.'
complete -c pdffonts -s l --description 'Specifies the last page to analyze.'
complete -c pdffonts -o subst --description 'List the substitute fonts that poppler will use for non embedded fonts.'
complete -c pdffonts -o opw --description 'Specify the owner password for the PDF file.'
complete -c pdffonts -o upw --description 'Specify the user password for the PDF file.'
complete -c pdffonts -s v --description 'Print copyright and version information.'
complete -c pdffonts -s h --description 'Print usage information.  ( -help and.'
complete -c pdffonts -l help --description 'are equivalent. ) EXIT CODES The Xpdf tools use the following exit codes:.'

