# pdfmom
# Autogenerated from man page /usr/share/man/man1/pdfmom.1.gz
complete -c pdfmom -o Tpdf --description 'option (which is the default), pdfmom processes files using groff[aq]s native…'
complete -c pdfmom -o Tps --description 'is given, processing is passed over to pdfroff , which uses groff [aq]s PostS…'
complete -c pdfmom -o mpdfmark -o mom -l no-toc --description 'options are implied and should not be given on the command line.'
complete -c pdfmom -s m --description 'options when.'

