# pdfroff
# Autogenerated from man page /usr/share/man/man1/pdfroff.1.gz
complete -c pdfroff -s h --description 'Same as  --help ; see below.'
complete -c pdfroff -s i --description 'Process standard input, after all other specified input files.'
complete -c pdfroff -s T --description 'Only  -Tps is supported by  pdfroff .'
complete -c pdfroff -s v --description 'Same as  --version ; see below.'
complete -c pdfroff -l help --description 'Causes  pdfroff to display a summary of the its usage syntax, and supported o…'
complete -c pdfroff -l emit-ps --description 'Suppresses the final output conversion step, causing  pdfroff to emit PostScr…'
complete -c pdfroff -l keep-temporary-files --description 'Suppresses the deletion of temporary files, which normally occurs after  pdfr…'
complete -c pdfroff -l no-pdf-output --description 'May be used with the  \\%--reference-dictionary= name option (described below)…'
complete -c pdfroff -l no-reference-dictionary --description 'May be used to eliminate the overhead of creating a reference dictionary, whe…'
complete -c pdfroff -l no-toc-relocation --description 'May be used to eliminate the extra  groff processing pass, which is required …'
complete -c pdfroff -l no-kill-null-pages --description 'While preparing for simulation of the manual collation step, which is traditi…'
complete -c pdfroff -l pdf-output --description 'Specifies the name to be used for the resultant PDF document; if unspecified,…'
complete -c pdfroff -l reference-dictionary --description 'Specifies the name to be used for the generated reference dictionary file; if…'
complete -c pdfroff -l report-progress --description 'Causes  pdfroff to display an informational message on standard error, at the…'
complete -c pdfroff -l stylesheet --description 'Specifies the name of an R "input file" , to be used as a style sheet for for…'
complete -c pdfroff -l version --description 'see below.'

