# pdfseparate
# Autogenerated from man page /usr/share/man/man1/pdfseparate.1.gz
complete -c pdfseparate -s f --description 'Specifies the first page to extract.'
complete -c pdfseparate -s l --description 'Specifies the last page to extract.'
complete -c pdfseparate -s v --description 'Print copyright and version information.'
complete -c pdfseparate -s h --description 'Print usage information.  ( -help and.'
complete -c pdfseparate -l help --description 'are equivalent. ) EXAMPLE pdfseparate sample. pdf sample-%d. pdf.'

