# pdfsig
# Autogenerated from man page /usr/share/man/man1/pdfsig.1.gz
complete -c pdfsig -o nocert --description 'Do not validate the certificate.'
complete -c pdfsig -o dump --description 'Dump all signatures into current directory.'
complete -c pdfsig -s v --description 'Print copyright and version information.'
complete -c pdfsig -s h --description 'Print usage information.  ( -help and.'
complete -c pdfsig -l help --description 'are equivalent.'

