# pdfunite
# Autogenerated from man page /usr/share/man/man1/pdfunite.1.gz
complete -c pdfunite -s v --description 'Print copyright and version information.'
complete -c pdfunite -s h --description 'Print usage information.  ( -help and.'
complete -c pdfunite -l help --description 'are equivalent. ) EXAMPLE pdfunite sample1. pdf sample2. pdf sample. pdf.'

