# peekfd
# Autogenerated from man page /usr/share/man/man1/peekfd.1.gz
complete -c peekfd -s 8 --description 'Do no post-processing on the bytes being read or written.'
complete -c peekfd -s n --description 'Do not display headers indicating the source of the bytes dumped.'
complete -c peekfd -s c --description 'Also dump the requested file descriptor activity in any new child processes t…'
complete -c peekfd -s d --description 'Remove duplicate read/writes from the output.'
complete -c peekfd -s v --description 'Display a version string.'
complete -c peekfd -s h --description 'Display a help message.  FILES /proc/*/fd.'

