# pinky
# Autogenerated from man page /usr/share/man/man1/pinky.1.gz
complete -c pinky -s l --description 'produce long format output for the specified USERs.'
complete -c pinky -s b --description 'omit the user\'s home directory and shell in long format.'
complete -c pinky -s h --description 'omit the user\'s project file in long format.'
complete -c pinky -s p --description 'omit the user\'s plan file in long format.'
complete -c pinky -s s --description 'do short format output, this is the default.'
complete -c pinky -s f --description 'omit the line of column headings in short format.'
complete -c pinky -s w --description 'omit the user\'s full name in short format.'
complete -c pinky -s i --description 'omit the user\'s full name and remote host in short format.'
complete -c pinky -s q --description 'omit the user\'s full name, remote host and idle time in short format.'
complete -c pinky -l help --description 'display this help and exit.'
complete -c pinky -l version --description 'output version information and exit.'

