# pip-freeze
# Autogenerated from man page /usr/share/man/man1/pip-freeze.1.gz
complete -c pip-freeze -s r -l requirement --description 'Use the order in the given requirements file and its comments when generating…'
complete -c pip-freeze -s f -l find-links --description 'URL for finding packages, which will be added to the output.'
complete -c pip-freeze -s l -l local --description 'If in a virtualenv that has global access, do not output globally-installed p…'
complete -c pip-freeze -l user --description 'Only output packages installed in user-site.'
complete -c pip-freeze -l all --description 'Do not skip these packages in the output: pip, setuptools, distribute, wheel.'
complete -c pip-freeze -l exclude-editable --description 'Exclude editable package from output.'

