# pip-config
# Autogenerated from man page /usr/share/man/man1/pip-config.1.gz
complete -c pip-config -l editor --description 'Editor to use to edit the file.'
complete -c pip-config -l global --description 'Use the system-wide configuration file only.'
complete -c pip-config -l user --description 'Use the user configuration file only.'
complete -c pip-config -l venv --description 'Use the virtualenv configuration file only.'

