# pkcheck
# Autogenerated from man page /usr/share/man/man1/pkcheck.1.gz
complete -c pkcheck -l process --description '(see below) or.'
complete -c pkcheck -l system-bus-name --description 'action.  The.'
complete -c pkcheck -l detail --description 'option can be used zero or more times to pass details about action.  If.'
complete -c pkcheck -l allow-user-interaction --description 'is passed, pkcheck blocks while waiting for authentication.'
complete -c pkcheck -l enable-internal-agent --description 'is passed.  AUTHOR.'

