# pkeyparam
# Autogenerated from man page /usr/share/man/man1/pkeyparam.1ssl.gz
complete -c pkeyparam -o help --description 'Print out a usage message.'
complete -c pkeyparam -o in --description 'This specifies the input filename to read parameters from or standard input i…'
complete -c pkeyparam -o out --description 'This specifies the output filename to write parameters to or standard output …'
complete -c pkeyparam -o text --description 'prints out the parameters in plain text in addition to the encoded version.'
complete -c pkeyparam -o noout --description 'do not output the encoded version of the parameters.'

