# pldd
# Autogenerated from man page /usr/share/man/man1/pldd.1.gz
complete -c pldd -s '?' -l help --description 'Display program help message.'
complete -c pldd -l usage --description 'Display a short usage message.'
complete -c pldd -s V -l version --description 'Display the program version.'

