# pluginviewer
# Autogenerated from man page /usr/share/man/man8/pluginviewer.8.gz
complete -c pluginviewer -s a --description 'List auxprop plugins.'
complete -c pluginviewer -s s --description 'List server authentication (SASL) plugins.'
complete -c pluginviewer -s c --description 'List client authentication (SASL) plugins.'
complete -c pluginviewer -s b --description 'List client authentication (SASL) plugins.'
complete -c pluginviewer -s e --description 'Assume that an external security layer (e. g.'
complete -c pluginviewer -s m --description 'Limit listed SASL plugins to the ones included in the MECHS (space separated)…'
complete -c pluginviewer -s x --description 'Limit listed auxprop plugins to the one listed in the AUXPROP_MECHS (space se…'
complete -c pluginviewer -s f --description 'Set security flags.'
complete -c pluginviewer -s p --description 'Specifies a colon-separated search path for plugins.  SEE ALSO.'

