# pmap
# Autogenerated from man page /usr/share/man/man1/pmap.1.gz
complete -c pmap -s x -l extended --description 'Show the extended format.'
complete -c pmap -s d -l device --description 'Show the device format.'
complete -c pmap -s q -l quiet --description 'Do not display some header or footer lines.'
complete -c pmap -s A -l range --description 'Limit results to the given range to  low and  high address range.'
complete -c pmap -s X --description 'Show even more details than the -x option.'
complete -c pmap -o XX --description 'Show everything the kernel provides.'
complete -c pmap -s p -l show-path --description 'Show full path to files in the mapping column.'
complete -c pmap -s c -l read-rc --description 'Read the default configuration.'
complete -c pmap -s C -l read-rc-from --description 'Read the configuration from file.'
complete -c pmap -s n -l create-rc --description 'Create new default configuration.'
complete -c pmap -s N -l create-rc-to --description 'Create new configuration to file.'
complete -c pmap -s h -l help --description 'Display help text and exit.'
complete -c pmap -s V -l version --description 'Display version information and exit.  EXIT STATUS 0 Success.'

