# polybar
# Autogenerated from man page /usr/share/man/man1/polybar.1.gz
complete -c polybar -s h -l help --description 'Display help text and exit.'
complete -c polybar -s v -l version --description 'Display build details and exit.'
complete -c polybar -s l -l log --description 'Set the logging verbosity (default: WARNING) .'
complete -c polybar -s q -l quiet --description 'Be quiet (will override -l).'
complete -c polybar -s c -l config --description 'Specify the path to the configuration file.'
complete -c polybar -s r -l reload --description 'Reload the application when the config file has been modified.'
complete -c polybar -s d -l dump --description 'Print the value of the specified parameter PARAM in bar section and exit.'
complete -c polybar -s m -l list-monitors --description 'Print list of available monitors and exit.'
complete -c polybar -s w -l print-wmname --description 'Print the generated WM_NAME and exit.'
complete -c polybar -s s -l stdout --description 'Output the data to stdout instead of drawing it to the X window.'
complete -c polybar -s p -l png --description 'Save png snapshot to FILE after running for 3 seconds.'

