# powertop
# Autogenerated from man page /usr/share/man/man8/powertop.8.gz
complete -c powertop -l auto-tune --description 'Set all tunable options to their good setting without interaction.'
complete -c powertop -s c -l calibrate --description 'Runs powertop in calibration mode.'
complete -c powertop -s C -l csv --description 'Generate a CSV report.'
complete -c powertop -l debug --description 'Run in debug mode.'
complete -c powertop -l extech --description 'Use the Extech Power Analyzer for measurements.'
complete -c powertop -s r -l html --description 'Generate an HTML report.'
complete -c powertop -s i -l iteration --description 'Number of times to run each test.'
complete -c powertop -s q -l quiet --description 'Suppress stderr output.'
complete -c powertop -s t -l time --description 'Generate a report for a specified number of R seconds .'
complete -c powertop -s w -l workload --description 'Execute  workload file as a part of calibration before making a report.'
complete -c powertop -s V -l version --description 'Print version information and exit.'
complete -c powertop -s h -l help --description 'Show the help message and exit.'

