# pr
# Autogenerated from man page /usr/share/man/man1/pr.1p.gz
complete -c pr -o column --description 'Produce multi-column output that is arranged in column columns (the default s…'
complete -c pr -s p --description 'Pause before beginning each page if the standard output is directed to a term…'
complete -c pr -s 2 --description 'a problem when a full page with headers and trailers is produced, it would be…'

