# preconv
# Autogenerated from man page /usr/share/man/man1/preconv.1.gz
complete -c preconv -s d --description 'Emit debugging messages to standard error (mainly the used encoding).'
complete -c preconv -s D --description 'Specify default encoding if everything fails (see below).'
complete -c preconv -s e --description 'Specify input encoding explicitly, overriding all other methods.'
complete -c preconv -l help --description 'TQ  -h Print help message.'
complete -c preconv -s r --description 'Do not add . lf requests.'
complete -c preconv -s k --description 'and.'
complete -c preconv -s K --description 'options of groff .  OPTIONS.'
complete -c preconv -s h --description 'Print help message.'
complete -c preconv -l version --description '.'
complete -c preconv -s v --description 'Print version number.'
complete -c preconv -o '*-' --description 'tag1 : value1 ; tag2 : value2 ; .'

