# printf
# Autogenerated from man page /usr/share/man/man1/printf.1p.gz
complete -c printf -o 9999999999@-2147483648@printf -o 9999999999 --description 'ABC@0@printf: "ABC" expected numeric value The diagnostic message format is n…'
complete -c printf -s 3 --description 'Numeric value of constant -3 51 6 Numeric value of the character \'3\'  in the …'

