# prs
# Autogenerated from man page /usr/share/man/man1/prs.1p.gz
complete -c prs -s r --description 'option has an optional option-argument.'
complete -c prs -s d --description 'Specify the output data specification.'
complete -c prs -s e --description 'Request information for all deltas created earlier than and including the del…'
complete -c prs -s c --description 'option.'
complete -c prs -s l --description 'Request information for all deltas created later than and including the delta…'
complete -c prs -s a --description 'Request writing of information for both removed--that is, delta type =c R (se…'

