# prtstat
# Autogenerated from man page /usr/share/man/man1/prtstat.1.gz
complete -c prtstat -s r -l raw --description 'Print the information in raw format.'
complete -c prtstat -s V -l version --description 'Show the version information for prtstat .  FILES.'

