# psl
# Autogenerated from man page /usr/share/man/man1/psl.1.gz
complete -c psl -l is-public-suffix --description 'check if domains are public suffixes.  [default].'
complete -c psl -l is-cookie-domain-acceptable --description 'check if cookie-domain is acceptable for domains.'
complete -c psl -l print-unreg-domain --description 'Returned data: the longest public suffix part for each domain.'
complete -c psl -l print-reg-domain --description 'Returned data: the shortest private suffix part for each domain.'
complete -c psl -l version --description 'show library version information.'
complete -c psl -l print-info --description 'print info about library builtin data PUBLIC SUFFIX DATA By default, `psl\' wi…'
complete -c psl -l use-latest-data --description 'use the latest available PSL data [default].'
complete -c psl -l use-builtin-data --description 'use the builtin PSL data.'
complete -c psl -l load-psl-file --description 'load PSL data from file SEE ALSO https://publicsuffix. org/ https://github.'

