# pvck
# Autogenerated from man page /usr/share/man/man8/pvck.8.gz
complete -c pvck -l commandprofile --description '.'
complete -c pvck -l config --description '.'
complete -c pvck -s d -l debug --description '.'
complete -c pvck -l driverloaded --description '.'
complete -c pvck -s h -l help --description '.'
complete -c pvck -l labelsector --description '.'
complete -c pvck -l longhelp --description '.'
complete -c pvck -l profile --description '.'
complete -c pvck -s q -l quiet --description '.'
complete -c pvck -s t -l test --description '.'
complete -c pvck -s v -l verbose --description '.'
complete -c pvck -l version --description '.'
complete -c pvck -s y -l yes --description '.'

