# pvresize
# Autogenerated from man page /usr/share/man/man8/pvresize.8.gz
complete -c pvresize -l commandprofile --description '.'
complete -c pvresize -l config --description '.'
complete -c pvresize -s d -l debug --description '.'
complete -c pvresize -l driverloaded --description '.'
complete -c pvresize -s h -l help --description '.'
complete -c pvresize -l longhelp --description '.'
complete -c pvresize -l profile --description '.'
complete -c pvresize -s q -l quiet --description '.'
complete -c pvresize -l reportformat --description '.'
complete -c pvresize -l setphysicalvolumesize --description '.'
complete -c pvresize -s t -l test --description '.'
complete -c pvresize -s v -l verbose --description '.'
complete -c pvresize -l version --description '.'
complete -c pvresize -s y -l yes --description '.'

