# pwconv
# Autogenerated from man page /usr/share/man/man8/pwconv.8.gz
complete -c pwconv -s h -l help --description 'Display help message and exit.'
complete -c pwconv -s R -l rootCHROOT_DIR --description 'Apply changes in the CHROOT_DIR directory and use the configuration files fro…'
complete -c pwconv -l root --description '.'

