# pwdx
# Autogenerated from man page /usr/share/man/man1/pwdx.1.gz
complete -c pwdx -s V -l version --description 'Output version information and exit.'
complete -c pwdx -s h -l help --description 'Output help screen and exit.'

