# qmsg
# Autogenerated from man page /usr/share/man/man1/qmsg.1p.gz
complete -c qmsg -s E --description 'Specify that the message is written to the standard error of each batch job.'
complete -c qmsg -s O --description 'Specify that the message is written to the standard output of each batch job.'

