# qselect
# Autogenerated from man page /usr/share/man/man1/qselect.1p.gz
complete -c qselect -s a --description '.'
complete -c qselect -s A --description '.'
complete -c qselect -s c --description '.'
complete -c qselect -s h --description 'Restrict selection to batch jobs that have a specific type of hold.'
complete -c qselect -s l --description '.'
complete -c qselect -s N --description 'Restrict selection to batch jobs with a specified name.'
complete -c qselect -s p --description '.'
complete -c qselect -s q --description '.'
complete -c qselect -s r --description 'Restrict selection to batch jobs with the specified rerunability status.'
complete -c qselect -s s --description 'Restrict selection to batch jobs in the specified states.'
complete -c qselect -s u --description 'Restrict selection to batch jobs owned by the specified user names.'

