# qstat
# Autogenerated from man page /usr/share/man/man1/qstat.1p.gz
complete -c qstat -s f --description 'Specify that a full display is produced.'
complete -c qstat -s Q --description 'Specify that the operand is a destination.'
complete -c qstat -s B --description 'Specify that the operand is a server name.'

