# rand
# Autogenerated from man page /usr/share/man/man1/rand.1ssl.gz
complete -c rand -o help --description 'Print out a usage message.'
complete -c rand -o out --description 'Write to file instead of standard output.'
complete -c rand -o rand --description 'Use specified file or files or \\s-1EGD\\s0 socket (see RAND_egd\\|(3)) for seed…'
complete -c rand -o base64 --description 'Perform base64 encoding on the output.'

