# ranger
# Autogenerated from man page /usr/share/man/man1/ranger.1.gz
complete -c ranger -s d -l debug --description 'Activate the debug mode: Whenever an error occurs, ranger will exit and print…'
complete -c ranger -s c -l clean --description 'Activate the clean mode:  ranger will not access or create any configuration …'
complete -c ranger -l cachedir --description 'Change the cache directory of ranger from \\f(CW$XDG_CACHE_HOME or ~/.'
complete -c ranger -s r -l confdir --description 'Change the configuration directory of ranger from \\f(CW$XDG_CONFIG_HOME or ~/.'
complete -c ranger -l datadir --description 'Change the data directory of ranger from \\f(CW$XDG_DATA_HOME or ~/.'
complete -c ranger -l copy-config --description 'Create copies of the default configuration files in your local configuration …'
complete -c ranger -l choosefile --description 'Allows you to pick a file with ranger.'
complete -c ranger -l choosefiles --description 'Allows you to pick multiple files with ranger.'
complete -c ranger -l choosedir --description 'Allows you to pick a directory with ranger.'
complete -c ranger -l selectfile --description 'Open ranger with targetfile selected.'
complete -c ranger -l show-only-dirs --description 'Display only the directories.'
complete -c ranger -l list-unused-keys --description 'List common keys which are not bound to any action in the \\*(L"browser\\*(R" c…'
complete -c ranger -l list-tagged-files --description 'List all files which are tagged with the given tag.'
complete -c ranger -l profile --description 'Print statistics of \\s-1CPU\\s0 usage on exit.'
complete -c ranger -l cmd --description 'Execute the command after the configuration has been read.'
complete -c ranger -l version --description 'Print the version and exit.'

