# rarpd
# Autogenerated from man page /usr/share/man/man8/rarpd.8.gz
complete -c rarpd -s a --description 'Listen on all the interfaces.'
complete -c rarpd -s A --description 'Listen not only RARP but also ARP messages, some rare clients use ARP by some…'
complete -c rarpd -s v --description 'Be verbose.'
complete -c rarpd -s d --description 'Debug mode.  Do not go to background.'
complete -c rarpd -s e --description 'Do not check for presence of a boot image, reply if MAC address resolves to a…'

