# raw2tiff
# Autogenerated from man page /usr/share/man/man1/raw2tiff.1.gz
complete -c raw2tiff -s H --description 'size of input image file header in bytes (0 by default).'
complete -c raw2tiff -s w --description 'width of input image in pixels (can be guessed, see .'
complete -c raw2tiff -s l --description 'length of input image in lines (can be guessed, see .'
complete -c raw2tiff -s b --description 'number of bands in input image (1 by default).'
complete -c raw2tiff -s d --description 'type of samples in input image, where  data_type may be: . ta \\w\'double  \'u .'
complete -c raw2tiff -s i --description 'type of samples interleaving in input image, where  config may be: .'
complete -c raw2tiff -s p --description 'photometric interpretation (color space) of the input image, where  photo may…'
complete -c raw2tiff -s s --description 'swap bytes fetched from the input file.'
complete -c raw2tiff -s L --description 'input data has LSB2MSB bit order (default).'
complete -c raw2tiff -s M --description 'input data has MSB2LSB bit order.'
complete -c raw2tiff -s c --description 'Specify a compression scheme to use when writing image data:  "-c none" for n…'
complete -c raw2tiff -s r --description 'Write data with a specified number of rows per strip; by default the number o…'

