# rdma-link
# Autogenerated from man page /usr/share/man/man8/rdma-link.8.gz
complete -c rdma-link -s V --description '.'
complete -c rdma-link -s d --description 'rdma link show [  DEV/PORT_INDEX  ] rdma link help.'

