# rdma
# Autogenerated from man page /usr/share/man/man8/rdma.8.gz
complete -c rdma -s V -o Version --description 'Print the version of the  rdma tool and exit.'
complete -c rdma -s b -o batch --description 'Read commands from provided file or standard input and invoke them.'
complete -c rdma -o force --description 'Don\'t terminate rdma on errors in batch mode.'
complete -c rdma -s d -l details --description 'Output detailed information.'
complete -c rdma -s p -l pretty --description 'When combined with -j generate a pretty JSON output.'
complete -c rdma -s j -l json --description 'Generate JSON output. SS  OBJECT.'

