# rdma-resource
# Autogenerated from man page /usr/share/man/man8/rdma-resource.8.gz
complete -c rdma-resource -s j --description '.'
complete -c rdma-resource -s d --description 'rdma resource show [  DEV/PORT_INDEX  ] rdma resource help.'

