# readprofile
# Autogenerated from man page /usr/share/man/man8/readprofile.8.gz
complete -c readprofile -s a -l all --description 'Print all symbols in the mapfile.'
complete -c readprofile -s b -l histbin --description 'Print individual histogram-bin counts.'
complete -c readprofile -s i -l info --description 'Info.'
complete -c readprofile -s m -l mapfile --description 'Specify a mapfile, which by default is R /usr/src/linux/System. map .'
complete -c readprofile -s M -l multiplier --description 'On some architectures it is possible to alter the frequency at which the kern…'
complete -c readprofile -s p -l profile --description 'Specify a different profiling buffer, which by default is R /proc/profile .'
complete -c readprofile -s r -l reset --description 'Reset the profiling buffer.'
complete -c readprofile -s s -l counters --description 'Print individual counters within functions.'
complete -c readprofile -s v -l verbose --description 'Verbose.   The output is organized in four columns and filled with blanks.'
complete -c readprofile -s V -l version --description 'Display version information and exit.'
complete -c readprofile -s t --description '(terse) switch is used together with.'
complete -c readprofile -s h -l help --description 'Display help text and exit.'

