# repo-add
# Autogenerated from man page /usr/share/man/man8/repo-add.8.gz
complete -c repo-add -s q -l quiet --description '.'
complete -c repo-add -s s -l sign --description '.'
complete -c repo-add -s k -l key --description '.'
complete -c repo-add -s v -l verify --description '.'
complete -c repo-add -l nocolor --description '.'
complete -c repo-add -s d -l delta --description '.'
complete -c repo-add -s n -l new --description '.'
complete -c repo-add -s R -l remove --description '.'

