# resize2fs
# Autogenerated from man page /usr/share/man/man8/resize2fs.8.gz
complete -c resize2fs -s b --description 'Turns on the 64bit feature, resizes the group descriptors as necessary, and m…'
complete -c resize2fs -s d --description 'Turns on various resize2fs debugging features, if they have been compiled int…'
complete -c resize2fs -s f --description 'Forces resize2fs to proceed with the filesystem resize operation, overriding …'
complete -c resize2fs -s F --description 'Flush the filesystem device\'s buffer caches before beginning.'
complete -c resize2fs -s M --description 'Shrink the file system to minimize its size as much as possible, given the fi…'
complete -c resize2fs -s p --description 'Prints out a percentage completion bars for each  resize2fs operation during …'
complete -c resize2fs -s P --description 'Print an estimate of the number of file system blocks in the file system if i…'
complete -c resize2fs -s s --description 'Turns off the 64bit feature and frees blocks that are no longer in use.'
complete -c resize2fs -s S --description 'The  resize2fs program will heuristically determine the RAID stride that was …'
complete -c resize2fs -s z --description 'Before overwriting a file system block, write the old contents of the block t…'

