# resize_reiserfs
# Autogenerated from man page /usr/share/man/man8/resize_reiserfs.8.gz
complete -c resize_reiserfs -o 's[+' -o ']size' --description 'Set the new size in bytes.'
complete -c resize_reiserfs -o jdev --description 'Set the journal device name.'
complete -c resize_reiserfs -s f --description 'Force, do not perform checks.'
complete -c resize_reiserfs -s q --description 'Do not print anything but error messages.'
complete -c resize_reiserfs -s s --description 'option is not specified, the filesystem will be resized to fill the given dev…'
complete -c resize_reiserfs -s j --description 'Set the journal device name.'
complete -c resize_reiserfs -s v --description 'Turn on extra progress status messages (default).'
complete -c resize_reiserfs -o '1	Resizing' --description '.'

