# rev
# Autogenerated from man page /usr/share/man/man1/rev.1.gz
complete -c rev -s V -l version --description 'Display version information and exit.'
complete -c rev -s h -l help --description 'Display help text and exit.'

