# rifle
# Autogenerated from man page /usr/share/man/man1/rifle.1.gz
complete -c rifle -s f --description 'Specify flags for opening the files.'
complete -c rifle -s l --description 'List all possible ways to open the specified files.'
complete -c rifle -s p --description 'Pick a method to open the files.'
complete -c rifle -s w --description 'Open the files with the program \\s-1PROGRAM\\s0.'
complete -c rifle -s c --description 'Read configuration from \\s-1CONFIG_FILE\\s0, instead of the default.'

