# rlogind
# Autogenerated from man page /usr/share/man/man8/rlogind.8.gz
complete -c rlogind -s 4 -l ipv4 --description 'daemon mode only accepts IPv4.'
complete -c rlogind -s 6 -l ipv6 --description 'only IPv6 in daemon mode.'
complete -c rlogind -s a -l verify-hostname --description 'ask hostname for verification.'
complete -c rlogind -s d -l daemon --description 'daemon mode, with instance limit.'
complete -c rlogind -s D -l debug --description 'set debug level.'
complete -c rlogind -s l -l no-rhosts --description 'ignore . rhosts file.'
complete -c rlogind -s L -l local-domain --description 'set local domain name.'
complete -c rlogind -s n -l no-keepalive --description 'do not set SO_KEEPALIVE.'
complete -c rlogind -s o -l allow-root --description 'allow uid 0 to login, disabled by default.'
complete -c rlogind -s p -l port --description 'listen on given port (valid only in daemon mode).'
complete -c rlogind -s r -l reverse-required --description 'require reverse resolving of a remote host IP.'
complete -c rlogind -s '?' -l help --description 'give this help list.'
complete -c rlogind -l usage --description 'give a short usage message.'
complete -c rlogind -s V -l version --description 'print program version.'

