# rlogin
# Autogenerated from man page /usr/share/man/man1/rlogin.1.gz
complete -c rlogin -s 4 -l ipv4 --description 'use only IPv4.'
complete -c rlogin -s 6 -l ipv6 --description 'use only IPv6.'
complete -c rlogin -s 8 -l 8-bit --description 'allows an eight-bit input data path at all times.'
complete -c rlogin -s d -l debug --description 'set the SO_DEBUG option.'
complete -c rlogin -s e -l escape --description 'allows user specification of the escape character, which is ``~\'\' by default.'
complete -c rlogin -s E -l no-escape --description 'stops any character from being recognized as an escape character.'
complete -c rlogin -s l -l user --description 'run as USER on the remote system.'
complete -c rlogin -s '?' -l help --description 'give this help list.'
complete -c rlogin -l usage --description 'give a short usage message.'
complete -c rlogin -s V -l version --description 'print program version.'

