# rshd
# Autogenerated from man page /usr/share/man/man8/rshd.8.gz
complete -c rshd -s a -l verify-hostname --description 'ask hostname for verification.'
complete -c rshd -s l -l no-rhosts --description 'ignore . rhosts file.'
complete -c rshd -s L -l log-sessions --description 'log successful logins.'
complete -c rshd -s n -l no-keepalive --description 'do not set SO_KEEPALIVE.'
complete -c rshd -s r -l reverse-required --description 'require reverse resolving of remote host IP.'
complete -c rshd -s '?' -l help --description 'give this help list.'
complete -c rshd -l usage --description 'give a short usage message.'
complete -c rshd -s V -l version --description 'print program version AUTHOR Written by many authors.'

