# rtcwake
# Autogenerated from man page /usr/share/man/man8/rtcwake.8.gz
complete -c rtcwake -s A -l adjfile --description 'Specify an alternative path to the adjust file.'
complete -c rtcwake -s a -l auto --description 'Read the clock mode (whether the hardware clock is set to UTC or local time) …'
complete -c rtcwake -l date --description 'Set the wakeup time to the value of the timestamp.'
complete -c rtcwake -s d -l device --description 'Use the specified device instead of rtc0 as realtime clock.'
complete -c rtcwake -s l -l local --description 'Assume that the hardware clock is set to local time, regardless of the conten…'
complete -c rtcwake -l list-modes --description 'List available --mode option arguments.'
complete -c rtcwake -s m -l mode --description 'Go into the given standby state.   Valid values for mode are: . RS.'
complete -c rtcwake -s n -l dry-run --description 'This option does everything apart from actually setting up the alarm, suspend…'
complete -c rtcwake -s s -l seconds --description 'Set the wakeup time to seconds in the future from now.'
complete -c rtcwake -s t -l time --description 'Set the wakeup time to the absolute time time_t.'
complete -c rtcwake -s u -l utc --description 'Assume that the hardware clock is set to UTC (Universal Time Coordinated), re…'
complete -c rtcwake -s v -l verbose --description 'Be verbose.'
complete -c rtcwake -s V -l version --description 'Display version information and exit.'
complete -c rtcwake -s h -l help --description 'Display help text and exit.'

