# rtkitctl
# Autogenerated from man page /usr/share/man/man8/rtkitctl.8.gz
complete -c rtkitctl -s h -l help --description 'Show a summary of options.'
complete -c rtkitctl -l version --description 'Show version.'
complete -c rtkitctl -l reset-known --description 'Reset real-time status of known threads.'
complete -c rtkitctl -l reset-all --description 'Reset real-time status of all threads.'
complete -c rtkitctl -l start --description 'Start RealtimeKit if it is not running already.'
complete -c rtkitctl -s k -l exit --description 'Terminate running RealtimeKit daemon.'

