# rtmon
# Autogenerated from man page /usr/share/man/man8/rtmon.8.gz
complete -c rtmon -o Version --description 'Print version and exit.'
complete -c rtmon -o family --description 'Specify protocol family.'
complete -c rtmon -s 4 --description 'Use IPv4.  Shortcut for -family inet.'
complete -c rtmon -s 6 --description 'Use IPv6.  Shortcut for -family inet6.'
complete -c rtmon -s 0 --description 'Use a special family identifier meaning that no networking protocol is involv…'

