# runcon
# Autogenerated from man page /usr/share/man/man1/runcon.1.gz
complete -c runcon -s c -l compute --description 'compute process transition context before modifying.'
complete -c runcon -s t -l type --description 'type (for same role as parent).'
complete -c runcon -s u -l user --description 'user identity.'
complete -c runcon -s r -l role --description 'role.'
complete -c runcon -s l -l range --description 'levelrange.'
complete -c runcon -l help --description 'display this help and exit.'
complete -c runcon -l version --description 'output version information and exit AUTHOR Written by Russell Coker.'

