# runuser
# Autogenerated from man page /usr/share/man/man1/runuser.1.gz
complete -c runuser -s c -l command --description 'Pass  command to the shell with the  -c option.'
complete -c runuser -s f -l fast --description 'Pass  -f to the shell, which may or may not be useful depending on the shell.'
complete -c runuser -s g -l group --description 'The primary group to be used.   This option is allowed for the root user only.'
complete -c runuser -s G -l supp-group --description 'Specify a supplemental group.'
complete -c runuser -s l -l login --description 'Start the shell as a login shell with an environment similar to a real login:…'
complete -c runuser -s m -s p -l preserve-environment --description 'Preserve the entire environment, i. e.'
complete -c runuser -s s -l shell --description 'Run the specified shell instead of the default.'
complete -c runuser -l session-command --description 'Same as  -c , but do not create a new session.   (Discouraged. ).'
complete -c runuser -s V -l version --description 'Display version information and exit.'
complete -c runuser -s h -l help --description 'Display help text and exit.'

