# s_time
# Autogenerated from man page /usr/share/man/man1/s_time.1ssl.gz
complete -c s_time -o help --description 'Print out a usage message.'
complete -c s_time -o connect --description 'This specifies the host and optional port to connect to.'
complete -c s_time -o www --description 'This specifies the page to \\s-1GET\\s0 from the server.'
complete -c s_time -o cert --description 'The certificate to use, if one is requested by the server.'
complete -c s_time -o key --description 'The private key to use.'
complete -c s_time -o verify --description 'The verify depth to use.'
complete -c s_time -o CApath --description 'The directory to use for server certificate verification.'
complete -c s_time -o CAfile --description 'A file containing trusted certificates to use during server authentication an…'
complete -c s_time -o no-CAfile --description 'Do not load the trusted \\s-1CA\\s0 certificates from the default file location.'
complete -c s_time -o no-CApath --description 'Do not load the trusted \\s-1CA\\s0 certificates from the default directory loc…'
complete -c s_time -o new --description 'performs the timing test using a new session \\s-1ID\\s0 for each connection.'
complete -c s_time -o reuse --description 'performs the timing test using the same session \\s-1ID\\s0; this can be used a…'
complete -c s_time -o nbio --description 'turns on non-blocking I/O.'
complete -c s_time -o ssl3 --description 'these options disable the use of certain \\s-1SSL\\s0 or \\s-1TLS\\s0 protocols.'
complete -c s_time -o bugs --description 'there are several known bug in \\s-1SSL\\s0 and \\s-1TLS\\s0 implementations.'
complete -c s_time -o cipher --description 'this allows the cipher list sent by the client to be modified.'

