# saslpasswd2
# Autogenerated from man page /usr/share/man/man8/saslpasswd2.8.gz
complete -c saslpasswd2 -s p --description 'Pipe mode - saslpasswd2 will neither prompt for the password nor verify that …'
complete -c saslpasswd2 -s c --description 'Creates an entry for the user if the user doesn\'t already exist.'
complete -c saslpasswd2 -s d --description 'Deletes the entry for the user.'
complete -c saslpasswd2 -s n --description 'Don\'t set the plaintext userPassword property for the user.'
complete -c saslpasswd2 -s u --description 'use  domain for user domain (realm).'
complete -c saslpasswd2 -s f --description 'use  file for sasldb.'
complete -c saslpasswd2 -s a --description 'use  appname as application name.'
complete -c saslpasswd2 -s v --description 'Print libsasl2 version number and exit.  SEE ALSO sasldblistusers2(8).'

