# script
# Autogenerated from man page /usr/share/man/man1/script.1.gz
complete -c script -s a -l append --description 'Append the output to  file or to  typescript , retaining the prior contents.'
complete -c script -s c -l command --description 'Run the  command rather than an interactive shell.'
complete -c script -s e -l return --description 'Return the exit code of the child process.'
complete -c script -s f -l flush --description 'Flush output after each write.'
complete -c script -l force --description 'Allow the default output destination, i. e.'
complete -c script -s q -l quiet --description 'Be quiet (do not write start and done messages to standard output).'
complete -c script -s t -l timing --description 'Output timing data to standard error, or to  file when given.'
complete -c script -s V -l version --description 'Display version information and exit.'
complete -c script -s h -l help --description 'Display help text and exit.'

