# sensors
# Autogenerated from man page /usr/share/man/man1/sensors.1.gz
complete -c sensors -s c -l config-file --description 'Specify a configuration file.'
complete -c sensors -s h -l help --description 'Print a help text and exit.'
complete -c sensors -s s -l set --description 'Evaluate all `set\' statements in the configuration file and exit.'
complete -c sensors -s A -l no-adapter --description 'Do not show the adapter for each chip.'
complete -c sensors -s u --description 'Raw output.'
complete -c sensors -s v -l version --description 'Print the program version and exit.'
complete -c sensors -s f -l fahrenheit --description 'Print the temperatures in degrees Fahrenheit instead of Celsius.'
complete -c sensors -l bus-list --description 'Generate bus statements suitable for using in sensors. conf.'

