# sess_id
# Autogenerated from man page /usr/share/man/man1/sess_id.1ssl.gz
complete -c sess_id -o help --description 'Print out a usage message.'
complete -c sess_id -o inform --description 'This specifies the input format.'
complete -c sess_id -o outform --description 'This specifies the output format.'
complete -c sess_id -o in --description 'This specifies the input filename to read session information from or standar…'
complete -c sess_id -o out --description 'This specifies the output filename to write session information to or standar…'
complete -c sess_id -o text --description 'prints out the various public or private key components in plain text in addi…'
complete -c sess_id -o cert --description 'if a certificate is present in the session it will be output using this optio…'
complete -c sess_id -o noout --description 'this option prevents output of the encoded version of the session.'

