# setfont
# Autogenerated from man page /usr/share/man/man8/setfont.8.gz
complete -c setfont -s h --description 'Override font height.'
complete -c setfont -s m --description 'Load console map or Unicode console map from R file .'
complete -c setfont -s o --description 'Save previous font in R file .'
complete -c setfont -s O --description 'Save previous font and Unicode map in R file .'
complete -c setfont -o om --description 'Store console map in R file .'
complete -c setfont -o ou --description 'Save previous Unicode map in R file .'
complete -c setfont -s u --description 'Load Unicode table describing the font from R file .'
complete -c setfont -s C --description 'Set the font for the indicated console.  (May require root permissions. ).'
complete -c setfont -s v --description 'Be verbose.'
complete -c setfont -s V --description 'Print version and exit.'

