# setleds
# Autogenerated from man page /usr/share/man/man1/setleds.1.gz
complete -c setleds -o num --description 'Clear or set NumLock.'
complete -c setleds -o caps --description 'Clear or set CapsLock.'
complete -c setleds -o scroll --description 'Clear or set ScrollLock.'

