# setsid
# Autogenerated from man page /usr/share/man/man1/setsid.1.gz
complete -c setsid -s c -l ctty --description 'Set the controlling terminal to the current one.'
complete -c setsid -s f -l fork --description 'Always create a new process.'
complete -c setsid -s w -l wait --description 'Wait for the execution of the program to end, and return the exit value of th…'
complete -c setsid -s V -l version --description 'Display version information and exit.'
complete -c setsid -s h -l help --description 'Display help text and exit.'

