# sh
# Autogenerated from man page /usr/share/man/man1/sh.1p.gz
complete -c sh -s a --description '.'
complete -c sh -s b --description '.'
complete -c sh -s C --description '.'
complete -c sh -s e --description '.'
complete -c sh -s f --description '.'
complete -c sh -s m --description '.'
complete -c sh -s n --description '.'
complete -c sh -s o --description 'option ,.'
complete -c sh -s u --description '.'
complete -c sh -s v --description 'and.'
complete -c sh -s x --description 'options are described as part of the set utility in Section 2.'
complete -c sh -s c --description 'Read commands from the command_string operand.'
complete -c sh -s i --description 'Specify that the shell is interactive ; see below.'
complete -c sh -s s --description 'Read commands from the standard input.'
complete -c sh -s r --description 'option) were excluded because the standard developers considered that the imp…'

