# sha256sum
# Autogenerated from man page /usr/share/man/man1/sha256sum.1.gz
complete -c sha256sum -s b -l binary --description 'read in binary mode.'
complete -c sha256sum -s c -l check --description 'read SHA256 sums from the FILEs and check them.'
complete -c sha256sum -l tag --description 'create a BSD-style checksum.'
complete -c sha256sum -s t -l text --description 'read in text mode (default) .'
complete -c sha256sum -l ignore-missing --description 'don\'t fail or report status for missing files.'
complete -c sha256sum -l quiet --description 'don\'t print OK for each successfully verified file.'
complete -c sha256sum -l status --description 'don\'t output anything, status code shows success.'
complete -c sha256sum -l strict --description 'exit non-zero for improperly formatted checksum lines.'
complete -c sha256sum -s w -l warn --description 'warn about improperly formatted checksum lines.'
complete -c sha256sum -l help --description 'display this help and exit.'
complete -c sha256sum -l version --description 'output version information and exit.'

