# showkey
# Autogenerated from man page /usr/share/man/man1/showkey.1.gz
complete -c showkey -s h -l help --description 'showkey prints to the standard error output its version number, a compile opt…'
complete -c showkey -s s -l scancodes --description 'Starts  showkey in scan code dump mode.'
complete -c showkey -s k -l keycodes --description 'Starts  showkey in keycode dump mode.'
complete -c showkey -s a -l ascii --description 'Starts  showkey in `ascii\' dump mode.'
complete -c showkey -s V -l version --description 'showkey prints version number and exits.  2. 6 KERNELS In 2.'

