# shuf
# Autogenerated from man page /usr/share/man/man1/shuf.1.gz
complete -c shuf -s e -l echo --description 'treat each ARG as an input line.'
complete -c shuf -s i -l input-range --description 'treat each number LO through HI as an input line.'
complete -c shuf -s n -l head-count --description 'output at most COUNT lines.'
complete -c shuf -s o -l output --description 'write result to FILE instead of standard output.'
complete -c shuf -l random-source --description 'get random bytes from FILE.'
complete -c shuf -s r -l repeat --description 'output lines can be repeated.'
complete -c shuf -s z -l zero-terminated --description 'line delimiter is NUL, not newline.'
complete -c shuf -l help --description 'display this help and exit.'
complete -c shuf -l version --description 'output version information and exit AUTHOR Written by Paul Eggert.'

