# shutdown
# Autogenerated from man page /usr/share/man/man8/shutdown.8.gz
complete -c shutdown -l help --description 'Print a short help text and exit.'
complete -c shutdown -s H -l halt --description 'Halt the machine.'
complete -c shutdown -s P -l poweroff --description 'Power-off the machine (the default).'
complete -c shutdown -s r -l reboot --description 'Reboot the machine.'
complete -c shutdown -s h --description 'Equivalent to --poweroff, unless --halt is specified.'
complete -c shutdown -s k --description 'Do not halt, power-off, reboot, just write wall message.'
complete -c shutdown -l no-wall --description 'Do not send wall message before halt, power-off, reboot.'
complete -c shutdown -s c --description 'Cancel a pending shutdown.'

