# signver
# Autogenerated from man page /usr/share/man/man1/signver.1.gz
complete -c signver -s A --description 'Displays all of the information in the PKCS#7 signature.'
complete -c signver -s V --description 'Verifies the digital signature.'
complete -c signver -s d --description 'Specify the database directory which contains the certificates and keys.'
complete -c signver -s a --description 'Sets that the given signature file is in ASCII format.'
complete -c signver -s i --description 'Gives the input file for the object with signed data.'
complete -c signver -s o --description 'Gives the output file to which to write the results.'
complete -c signver -s s --description 'Gives the input file for the digital signature.'
complete -c signver -s v --description 'Enables verbose output.'

