# slabtop
# Autogenerated from man page /usr/share/man/man1/slabtop.1.gz
complete -c slabtop -s d -l delay --description 'Refresh the display every  n in seconds.'
complete -c slabtop -s s -l sort --description 'Sort by S, where S is one of the sort criteria.'
complete -c slabtop -s o -l once --description 'Display the output once and then exit.'
complete -c slabtop -s V -l version --description 'Display version information and exit.'
complete -c slabtop -s h -l help --description 'Display usage information and exit.'

