# sleep
# Autogenerated from man page /usr/share/man/man1/sleep.1.gz
complete -c sleep -l help --description 'display this help and exit.'
complete -c sleep -l version --description 'output version information and exit AUTHOR Written by Jim Meyering and Paul E…'

