# smproxy
# Autogenerated from man page /usr/share/man/man1/smproxy.1.gz
complete -c smproxy -o clientId --description 'Specifies the session ID used by smproxy in the previous session.'
complete -c smproxy -o restore --description 'Specifies the file used by smproxy to save state in the previous session.'
complete -c smproxy -o version --description 'Prints the program version and exits.  DESCRIPTION.'

