# soelim
# Autogenerated from man page /usr/share/man/man1/soelim.1.gz
complete -c soelim -s C --description 'Recognize  . so even when followed by a character other than space or newline.'
complete -c soelim -s I --description 'This option may be used to add a directory to the search path for files (both…'
complete -c soelim -s r --description 'Do not add  . lf requests (for general use, with non-groff files).'
complete -c soelim -s t --description 'Don\\[aq]t emit  .'
complete -c soelim -s s --description 'option of groff .'
complete -c soelim -s v --description 'Print the version number.'

