# sort
# Autogenerated from man page /usr/share/man/man1/sort.1p.gz
complete -c sort -o um --description 'with one input file keep the first in each set of lines with equal keys.'
complete -c sort -s y --description 'option was omitted because of non-portability.  The.'

