# spkac
# Autogenerated from man page /usr/share/man/man1/spkac.1ssl.gz
complete -c spkac -o help --description 'Print out a usage message.'
complete -c spkac -o in --description 'This specifies the input filename to read from or standard input if this opti…'
complete -c spkac -o out --description 'specifies the output filename to write to or standard output by default.'
complete -c spkac -o key --description 'create an \\s-1SPKAC\\s0 file using the private key in keyfile.'
complete -c spkac -o passin --description 'the input file password source.'
complete -c spkac -o challenge --description 'specifies the challenge string if an \\s-1SPKAC\\s0 is being created.'
complete -c spkac -o spkac --description 'allows an alternative name form the variable containing the \\s-1SPKAC.'
complete -c spkac -o spksect --description 'allows an alternative name form the section containing the \\s-1SPKAC.'
complete -c spkac -o noout --description 'don\'t output the text version of the \\s-1SPKAC\\s0 (not used if an \\s-1SPKAC\\s…'
complete -c spkac -o pubkey --description 'output the public key of an \\s-1SPKAC\\s0 (not used if an \\s-1SPKAC\\s0 is bein…'
complete -c spkac -o verify --description 'verifies the digital signature on the supplied \\s-1SPKAC. \\s0.'

