# stdbuf
# Autogenerated from man page /usr/share/man/man1/stdbuf.1.gz
complete -c stdbuf -s i -l input --description 'adjust standard input stream buffering.'
complete -c stdbuf -s o -l output --description 'adjust standard output stream buffering.'
complete -c stdbuf -s e -l error --description 'adjust standard error stream buffering.'
complete -c stdbuf -l help --description 'display this help and exit.'
complete -c stdbuf -l version --description 'output version information and exit.'

