# su
# Autogenerated from man page /usr/share/man/man1/su.1.gz
complete -c su -s c -l command --description 'Pass  command to the shell with the  -c option.'
complete -c su -s f -l fast --description 'Pass  -f to the shell, which may or may not be useful, depending on the shell.'
complete -c su -s g -l group --description 'Specify the primary group.   This option is available to the root user only.'
complete -c su -s G -l supp-group --description 'Specify a supplemental group.'
complete -c su -s l -l login --description 'Start the shell as a login shell with an environment similar to a real login:…'
complete -c su -s m -s p -l preserve-environment --description 'Preserve the entire environment, i. e.'
complete -c su -s P -l pty --description 'Create pseudo-terminal for the session.'
complete -c su -s s -l shell --description 'Run the specified shell instead of the default.'
complete -c su -l session-command --description 'Same as  -c but do not create a new session.   (Discouraged. ).'
complete -c su -s V -l version --description 'Display version information and exit.'
complete -c su -s h -l help --description 'Display help text and exit.'

