# sudoreplay
# Autogenerated from man page /usr/share/man/man8/sudoreplay.8.gz
complete -c sudoreplay -s d --description 'Store session logs in dir instead of the default, /var/log/sudo-io.'
complete -c sudoreplay -s f --description 'Select which I/O type(s) to display.'
complete -c sudoreplay -s h --description 'Display a short help message to the standard output and exit.'
complete -c sudoreplay -s l --description 'Enable list mode.'
complete -c sudoreplay -s m --description 'Specify an upper bound on how long to wait between key presses or output data.'
complete -c sudoreplay -s n --description 'Do not prompt for user input or attempt to re-size the terminal.'
complete -c sudoreplay -s R --description 'Do not attempt to re-size the terminal to match the terminal size of the sess…'
complete -c sudoreplay -s s --description 'This option causes sudoreplay to adjust the number of seconds it will wait be…'
complete -c sudoreplay -s V --description 'Print the sudoreplay versions version number and exit.'

