# sum
# Autogenerated from man page /usr/share/man/man1/sum.1.gz
complete -c sum -s r --description 'use BSD sum algorithm, use 1K blocks.'
complete -c sum -s s -l sysv --description 'use System V sum algorithm, use 512 bytes blocks.'
complete -c sum -l help --description 'display this help and exit.'
complete -c sum -l version --description 'output version information and exit AUTHOR Written by Kayvan Aghaiepour and D…'

