# swaplabel
# Autogenerated from man page /usr/share/man/man8/swaplabel.8.gz
complete -c swaplabel -s h -l help --description 'Display help text and exit.'
complete -c swaplabel -s L -l label --description 'Specify a new label for the device.'
complete -c swaplabel -s U --description 'are not given, swaplabel will simply display the current swap-area label and …'
complete -c swaplabel -l uuid --description 'Specify a new UUID for the device.'

