# switch_root
# Autogenerated from man page /usr/share/man/man8/switch_root.8.gz
complete -c switch_root -s h -l help --description 'Display help text and exit.'
complete -c switch_root -s V -l version --description 'Display version information and exit.'

