# sync
# Autogenerated from man page /usr/share/man/man1/sync.1.gz
complete -c sync -s d -l data --description 'sync only file data, no unneeded metadata.'
complete -c sync -s f -l file-system --description 'sync the file systems that contain the files.'
complete -c sync -l help --description 'display this help and exit.'
complete -c sync -l version --description 'output version information and exit.'

