# systemd-delta
# Autogenerated from man page /usr/share/man/man1/systemd-delta.1.gz
complete -c systemd-delta -l diff --description 'When showing modified files, when a file is overridden show a diff as well.'
complete -c systemd-delta -s h -l help --description 'Print a short help text and exit.'
complete -c systemd-delta -l version --description 'Print a short version string and exit.'
complete -c systemd-delta -l no-pager --description 'Do not pipe output into a pager.'
complete -c systemd-delta -s t -l type --description '.'

