# systemd-ask-password-console
# Autogenerated from man page /usr/share/man/man8/systemd-ask-password-console.service.8.gz
complete -c systemd-ask-password-console -l watch -l console --description 'or.'
complete -c systemd-ask-password-console -l wall --description 'command line parameters.  SEE ALSO.'

