# systemd-tmpfiles
# Autogenerated from man page /usr/share/man/man8/systemd-tmpfiles.8.gz
complete -c systemd-tmpfiles -l create --description 'If this option is passed, all files and directories marked with f, F, w, d, D…'
complete -c systemd-tmpfiles -l clean --description 'If this option is passed, all files and directories with an age parameter con…'
complete -c systemd-tmpfiles -l remove --description 'If this option is passed, the contents of directories marked with D or R, and…'
complete -c systemd-tmpfiles -l user --description 'Execute "user" configuration, i. e.  tmpfiles.'
complete -c systemd-tmpfiles -l boot --description 'Also execute lines with an exclamation mark.'
complete -c systemd-tmpfiles -l prefix --description 'Only apply rules with paths that start with the specified prefix.'
complete -c systemd-tmpfiles -l exclude-prefix --description 'Ignore rules with paths that start with the specified prefix.'
complete -c systemd-tmpfiles -l root --description 'Takes a directory path as an argument.'
complete -c systemd-tmpfiles -l replace --description 'When this option is given, one ore more positional arguments must be specifie…'
complete -c systemd-tmpfiles -s h -l help --description 'Print a short help text and exit.'
complete -c systemd-tmpfiles -l version --description 'Print a short version string and exit.'

