# systemd-cat
# Autogenerated from man page /usr/share/man/man1/systemd-cat.1.gz
complete -c systemd-cat -s h -l help --description 'Print a short help text and exit.'
complete -c systemd-cat -l version --description 'Print a short version string and exit.'
complete -c systemd-cat -s t -l identifier --description 'Specify a short string that is used to identify the logging tool.'
complete -c systemd-cat -s p -l priority --description 'Specify the default priority level for the logged messages.'
complete -c systemd-cat -l level-prefix --description 'Controls whether lines read are parsed for syslog priority level prefixes.'

