# systemd-machine-id-setup
# Autogenerated from man page /usr/share/man/man1/systemd-machine-id-setup.1.gz
complete -c systemd-machine-id-setup -l root --description 'Takes a directory path as argument.'
complete -c systemd-machine-id-setup -l commit --description 'Commit a transient machine ID to disk.'
complete -c systemd-machine-id-setup -l print --description 'Print the machine ID generated or committed after the operation is complete.'
complete -c systemd-machine-id-setup -s h -l help --description 'Print a short help text and exit.'
complete -c systemd-machine-id-setup -l version --description 'Print a short version string and exit.'
complete -c systemd-machine-id-setup -o uuid --description 'option), this UUID is used to initialize the machine ID.'

