# systemd-sysusers
# Autogenerated from man page /usr/share/man/man8/systemd-sysusers.8.gz
complete -c systemd-sysusers -l root --description 'Takes a directory path as an argument.'
complete -c systemd-sysusers -l inline --description 'Treat each positional argument as a separate configuration line instead of a …'
complete -c systemd-sysusers -s h -l help --description 'Print a short help text and exit.'
complete -c systemd-sysusers -l version --description 'Print a short version string and exit.'
complete -c systemd-sysusers -l replace --description 'is specified, arguments specified on the command line are used instead of the…'

