# systemd-journal-gatewayd
# Autogenerated from man page /usr/share/man/man8/systemd-journal-gatewayd.service.8.gz
complete -c systemd-journal-gatewayd -l cert --description 'Specify the path to a file containing a server certificate in PEM format.'
complete -c systemd-journal-gatewayd -l key --description 'Specify the path to a file containing a server key in PEM format correspondin…'
complete -c systemd-journal-gatewayd -l trust --description 'Specify the path to a file containing a CA certificate in PEM format.'
complete -c systemd-journal-gatewayd -s D -l directory --description 'Takes a directory path as argument.'
complete -c systemd-journal-gatewayd -s h -l help --description 'Print a short help text and exit.'
complete -c systemd-journal-gatewayd -l version --description 'Print a short version string and exit.'

