# systemd-tty-ask-password-agent
# Autogenerated from man page /usr/share/man/man1/systemd-tty-ask-password-agent.1.gz
complete -c systemd-tty-ask-password-agent -l list --description 'Lists all currently pending system password requests.'
complete -c systemd-tty-ask-password-agent -l query --description 'Process all currently pending system password requests by querying the user o…'
complete -c systemd-tty-ask-password-agent -l watch --description 'Continuously process password requests.'
complete -c systemd-tty-ask-password-agent -l wall --description 'Forward password requests to wall(1) instead of querying the user on the call…'
complete -c systemd-tty-ask-password-agent -l plymouth --description 'Ask question with plymouth(8) instead of querying the user on the calling TTY.'
complete -c systemd-tty-ask-password-agent -l console --description 'Ask question on /dev/console instead of querying the user on the calling TTY.'
complete -c systemd-tty-ask-password-agent -s h -l help --description 'Print a short help text and exit.'
complete -c systemd-tty-ask-password-agent -l version --description 'Print a short version string and exit.'

