# systool
# Autogenerated from man page /usr/share/man/man1/systool.1.gz
complete -c systool -s a --description 'Show attributes of the requested resource.'
complete -c systool -s b --description 'Show information for a specific bus.'
complete -c systool -s c --description 'Show information for a specific class.'
complete -c systool -s d --description 'Show only devices.'
complete -c systool -s h --description 'Show usage.'
complete -c systool -s m --description 'Show information for a specific module.'
complete -c systool -s p --description 'Show absolute sysfs path to the resource.'
complete -c systool -s v --description 'Show all attributes with values.'
complete -c systool -s A --description 'Show attribute value for the requested resource.'
complete -c systool -s D --description 'Show only drivers.'
complete -c systool -s P --description 'Show device\'s parent.'

