# systemd-networkd-wait-online
# Autogenerated from man page /usr/share/man/man8/systemd-networkd-wait-online.service.8.gz
complete -c systemd-networkd-wait-online -s i -l interface --description 'Network interface to wait for before deciding if the system is online.'
complete -c systemd-networkd-wait-online -l ignore --description 'Network interfaces to be ignored when deciding if the system is online.'
complete -c systemd-networkd-wait-online -l timeout --description 'Fail the service if the network is not online by the time the timeout elapses.'

