# systemd-detect-virt
# Autogenerated from man page /usr/share/man/man1/systemd-detect-virt.1.gz
complete -c systemd-detect-virt -s c -l container --description 'Only detects container virtualization (i. e.  shared kernel virtualization).'
complete -c systemd-detect-virt -s v -l vm --description 'Only detects hardware virtualization).'
complete -c systemd-detect-virt -s r -l chroot --description 'Detect whether invoked in a chroot(2) environment.'
complete -c systemd-detect-virt -l private-users --description 'Detect whether invoked in a user namespace.'
complete -c systemd-detect-virt -s q -l quiet --description 'Suppress output of the virtualization technology identifier.'
complete -c systemd-detect-virt -s h -l help --description 'Print a short help text and exit.'
complete -c systemd-detect-virt -l version --description 'Print a short version string and exit.'

