# systemd-inhibit
# Autogenerated from man page /usr/share/man/man1/systemd-inhibit.1.gz
complete -c systemd-inhibit -l what --description 'Takes a colon-separated list of one or more operations to inhibit: "shutdown"…'
complete -c systemd-inhibit -l who --description 'Takes a short, human-readable descriptive string for the program taking the l…'
complete -c systemd-inhibit -l why --description 'Takes a short, human-readable descriptive string for the reason for taking th…'
complete -c systemd-inhibit -l mode --description 'Takes either "block" or "delay" and describes how the lock is applied.'
complete -c systemd-inhibit -l list --description 'Lists all active inhibition locks instead of acquiring one.'
complete -c systemd-inhibit -s h -l help --description 'Print a short help text and exit.'
complete -c systemd-inhibit -l version --description 'Print a short version string and exit.'

