# systemd-analyze
# Autogenerated from man page /usr/share/man/man1/systemd-analyze.1.gz
complete -c systemd-analyze -l system --description 'Operates on the system systemd instance.  This is the implied default.'
complete -c systemd-analyze -l user --description 'Operates on the user systemd instance.'
complete -c systemd-analyze -l global --description 'Operates on the system-wide configuration for user systemd instance.'
complete -c systemd-analyze -l order -l require --description 'When used in conjunction with the dot command (see above), selects which depe…'
complete -c systemd-analyze -l from-pattern -l to-pattern --description 'When used in conjunction with the dot command (see above), this selects which…'
complete -c systemd-analyze -l fuzz --description 'When used in conjunction with the critical-chain command (see above), also sh…'
complete -c systemd-analyze -l man --description 'Do not invoke man to verify the existence of man pages listed in Documentatio…'
complete -c systemd-analyze -l generators --description 'Invoke unit generators, see systemd. generator(7).'
complete -c systemd-analyze -s H -l host --description 'Execute the operation remotely.'
complete -c systemd-analyze -s M -l machine --description 'Execute operation on a local container.'
complete -c systemd-analyze -s h -l help --description 'Print a short help text and exit.'
complete -c systemd-analyze -l version --description 'Print a short version string and exit.'
complete -c systemd-analyze -l no-pager --description 'Do not pipe output into a pager.'
complete -c systemd-analyze -l log-level --description 'described in systemd(1)).'
complete -c systemd-analyze -l log-target --description 'systemd(1)).'

