# systemd-cgls
# Autogenerated from man page /usr/share/man/man1/systemd-cgls.1.gz
complete -c systemd-cgls -l all --description 'Do not hide empty control groups in the output.'
complete -c systemd-cgls -s l -l full --description 'Do not ellipsize process tree members.'
complete -c systemd-cgls -s u -l unit --description 'Show cgroup subtrees for the specified units.'
complete -c systemd-cgls -l user-unit --description 'Show cgroup subtrees for the specified user units.'
complete -c systemd-cgls -s k --description 'Include kernel threads in output.'
complete -c systemd-cgls -s M -l machine --description 'Limit control groups shown to the part corresponding to the container MACHINE.'
complete -c systemd-cgls -s h -l help --description 'Print a short help text and exit.'
complete -c systemd-cgls -l version --description 'Print a short version string and exit.'
complete -c systemd-cgls -l no-pager --description 'Do not pipe output into a pager.'

