# systemd-path
# Autogenerated from man page /usr/share/man/man1/systemd-path.1.gz
complete -c systemd-path -l suffix --description 'The printed paths are suffixed by the specified string.'
complete -c systemd-path -s h -l help --description 'Print a short help text and exit.'
complete -c systemd-path -l version --description 'Print a short version string and exit.'

