# tail
# Autogenerated from man page /usr/share/man/man1/tail.1p.gz
complete -c tail -o @Relative --description 'none@Relative to the end of the file.'
complete -c tail -s 1 --description '.'
complete -c tail -s b --description 'option was omitted because of the general non-portability of block-sized unit…'

