# taskset
# Autogenerated from man page /usr/share/man/man1/taskset.1.gz
complete -c taskset -s a -l all-tasks --description 'Set or retrieve the CPU affinity of all the tasks (threads) for a given PID.'
complete -c taskset -s c -l cpu-list --description 'Interpret mask as numerical list of processors instead of a bitmask.'
complete -c taskset -s p -l pid --description 'Operate on an existing PID and do not launch a new task.'
complete -c taskset -s V -l version --description 'Display version information and exit.'
complete -c taskset -s h -l help --description 'Display help text and exit.  USAGE.'

