# tbl
# Autogenerated from man page /usr/share/man/man1/tbl.1.gz
complete -c tbl -s C --description 'Enable compatibility mode to recognize  . TS and  .'
complete -c tbl -s t --description 'option of groff.'
complete -c tbl -s v --description 'Print the version number.'
complete -c tbl -o ms --description 'macros which provide this functionality if a table starts with .'

