# tdbbackup
# Autogenerated from man page /usr/share/man/man8/tdbbackup.8.gz
complete -c tdbbackup -s h --description 'Get help information.'
complete -c tdbbackup -s s --description 'The -s option allows the administrator to specify a file backup extension.'
complete -c tdbbackup -s v --description 'The -v will check the database for damages (corrupt data) which if detected c…'
complete -c tdbbackup -s n --description 'The -n option sets the hash size for the new backup tdb.'
complete -c tdbbackup -s l --description 'This options disables any locking, by passing TDB_NOLOCK to tdb_open_ex().'

