# tdbdump
# Autogenerated from man page /usr/share/man/man8/tdbdump.8.gz
complete -c tdbdump -s h --description 'Get help information.'
complete -c tdbdump -s k --description 'The -k option restricts dumping to a single key, if found.'
complete -c tdbdump -s e --description 'The -e tries to dump out from a corrupt database.'

