# tee
# Autogenerated from man page /usr/share/man/man1/tee.1.gz
complete -c tee -s a -l append --description 'append to the given FILEs, do not overwrite.'
complete -c tee -s i -l ignore-interrupts --description 'ignore interrupt signals.'
complete -c tee -s p --description 'diagnose errors writing to non pipes.'
complete -c tee -l output-error --description 'set behavior on write error.   See MODE below.'
complete -c tee -l help --description 'display this help and exit.'
complete -c tee -l version --description 'output version information and exit .'

