# telnet
# Autogenerated from man page /usr/share/man/man1/telnet.1.gz
complete -c telnet -s 4 -l ipv4 --description 'use only IPv4.'
complete -c telnet -s 6 -l ipv6 --description 'use only IPv6.'
complete -c telnet -s 8 -l binary --description 'use an 8-bit data transmission.'
complete -c telnet -s a -l login --description 'attempt automatic login.'
complete -c telnet -s c -l no-rc --description 'do not read the user\'s . telnetrc file.'
complete -c telnet -s d -l debug --description 'turn on debugging.'
complete -c telnet -s e -l escape --description 'use CHAR as an escape character.'
complete -c telnet -s E -l no-escape --description 'use no escape character.'
complete -c telnet -s K -l no-login --description 'do not automatically login to the remote system.'
complete -c telnet -s l -l user --description 'attempt automatic login as USER.'
complete -c telnet -s L -l binary-output --description 'use an 8-bit data transmission for output only.'
complete -c telnet -s n -l trace --description 'record trace information into FILE.'
complete -c telnet -s r -l rlogin --description 'use a user-interface similar to rlogin.'
complete -c telnet -s '?' -l help --description 'give this help list.'
complete -c telnet -l usage --description 'give a short usage message.'
complete -c telnet -s V -l version --description 'print program version.'

