# telnetd
# Autogenerated from man page /usr/share/man/man8/telnetd.8.gz
complete -c telnetd -s D -l debug --description 'set debugging level.'
complete -c telnetd -s E -l exec-login --description 'set program to be executed instead of \\,/usr/bin/login\\/.'
complete -c telnetd -s h -l no-hostinfo --description 'do not print host information before login has been completed.'
complete -c telnetd -s l -l linemode --description 'set line mode.'
complete -c telnetd -s n -l no-keepalive --description 'disable TCP keep-alives.'
complete -c telnetd -s U -l reverse-lookup --description 'refuse connections from addresses that cannot be mapped back into a symbolic …'
complete -c telnetd -s '?' -l help --description 'give this help list.'
complete -c telnetd -l usage --description 'give a short usage message.'
complete -c telnetd -s V -l version --description 'print program version.'

