# tfmtodit
# Autogenerated from man page /usr/share/man/man1/tfmtodit.1.gz
complete -c tfmtodit -s v --description 'Print the version number.'
complete -c tfmtodit -s s --description 'The font is special.'
complete -c tfmtodit -s k --description 'The skewchar of this font is at position R n .'
complete -c tfmtodit -s g --description 'option.'

