# thin_ls
# Autogenerated from man page /usr/share/man/man8/thin_ls.8.gz
complete -c thin_ls -s h -l help --description 'Print help and exit.'
complete -c thin_ls -s V -l version --description 'Print version information and exit.'
complete -c thin_ls -s o -l format --description 'Give a comma separated list of fields to be output. PP . nf .'
complete -c thin_ls -l no-headers --description 'Don\'t output headers.'
complete -c thin_ls -s m -l metadata-snap --description 'Use metadata snapshot.'

