# thin_delta
# Autogenerated from man page /usr/share/man/man8/thin_delta.8.gz
complete -c thin_delta -l thin1 -l snap1 --description 'The numeric identifier for the first thin volume to diff.'
complete -c thin_delta -l thin2 -l snap2 --description 'The numeric identifier for the second thin volume to diff.'
complete -c thin_delta -l metadata-snap --description 'Use a metadata snapshot. PP . nf .'
complete -c thin_delta -l verbose --description 'Provide extra information on the mappings.'
complete -c thin_delta -s h -l help --description 'Print help and exit.'
complete -c thin_delta -s V -l version --description 'Output version information and exit.'

