# thin_restore
# Autogenerated from man page /usr/share/man/man8/thin_restore.8.gz
complete -c thin_restore -s h -l help --description 'Print help and exit.'
complete -c thin_restore -s V -l version --description 'Print version information and exit.'
complete -c thin_restore -s q -l quiet --description 'Suppress output messages, return only exit code.'
complete -c thin_restore -s i -l input --description 'Input file containing XML metadata.'
complete -c thin_restore -s o -l output --description 'Output file or device for restored binary metadata.'

