# thin_trim
# Autogenerated from man page /usr/share/man/man8/thin_trim.8.gz
complete -c thin_trim -s h -l help --description 'Print help and exit.'
complete -c thin_trim -s V -l version --description 'Print version information and exit.'
complete -c thin_trim -l pool-inactive --description 'Indicates you are aware the pool should be inactive.'

