# tiffcmp
# Autogenerated from man page /usr/share/man/man1/tiffcmp.1.gz
complete -c tiffcmp -s l --description 'List each byte of image data that differs between the files.'
complete -c tiffcmp -s z --description 'List specified number of image data bytes that differs between the files.'
complete -c tiffcmp -s t --description 'Ignore any differences in directory tags.'

