# tiff2bw
# Autogenerated from man page /usr/share/man/man1/tiff2bw.1.gz
complete -c tiff2bw -s c --description 'Specify a compression scheme to use when writing image data:  "-c none" for n…'
complete -c tiff2bw -s r --description 'Write data with a specified number of rows per strip; by default the number o…'
complete -c tiff2bw -s R --description 'Specify the percentage of the red channel to use (default 28).'
complete -c tiff2bw -s G --description 'Specify the percentage of the green channel to use (default 59).'
complete -c tiff2bw -s B --description 'options may be used.  OPTIONS.'

