# tiffset
# Autogenerated from man page /usr/share/man/man1/tiffset.1.gz
complete -c tiffset -s d --description 'change the current directory (starting at 0).'
complete -c tiffset -s s --description 'Set the value of the named tag to the value or values specified.'
complete -c tiffset -o sd --description 'change the current directory by offset.'
complete -c tiffset -o sf --description 'Set the value of the tag to the contents of filename.'
complete -c tiffset -s u --description 'Unset the tag.'

