# tload
# Autogenerated from man page /usr/share/man/man1/tload.1.gz
complete -c tload -s s -l scale --description 'The scale option allows a vertical scale to be specified for the display (in …'
complete -c tload -s d -l delay --description 'The delay sets the delay between graph updates in R seconds .'
complete -c tload -s h -l help --description 'Display this help text.'
complete -c tload -s V -l version --description 'Display version information and exit.'

