# toast
# Autogenerated from man page /usr/share/man/man1/toast.1.gz
complete -c toast -s c --description '(cat) Write to the standard output; no files are changed.'
complete -c toast -s d --description '(decode) Decode, rather than encode, the files.'
complete -c toast -s f --description '(force) Force replacement of output files if they exist.'
complete -c toast -s p --description '(precious) Do not delete the source files.'
complete -c toast -s C --description '(LTP cut-off) Ignore most sample values when calculating the GSM long-term co…'
complete -c toast -s F --description '(fast) On systems with a floating point processor, but without a multiplicati…'
complete -c toast -s v --description '(version) outputs the version of toast (or untoast or tcat) to stdout and exi…'
complete -c toast -s h --description '(help) prints a short overview of the options.'
complete -c toast -s u --description '(\\(*mU-law) 8 kHz, 8 bit \\(*mU-law encoding (file suffix . u).'
complete -c toast -s a --description '(A-law) 8 kHz, 8 bit A-law encoding (file suffix . A).'
complete -c toast -s s --description '(Sun audio) 8 kHz, 8 bit \\(*mU-law encoding with audio header (file suffix .'
complete -c toast -s l --description '(linear) 8 kHz, 16 bit signed linear encoding in host byte order with 13 sign…'

