# toe
# Autogenerated from man page /usr/share/man/man1/toe.1m.gz
complete -c toe -s a --description 'report on all of the terminal databases which ncurses would search, rather th…'
complete -c toe -s s --description 'sort the output by the entry names.'
complete -c toe -s u --description 'says to write a report to the standard output, listing dependencies in the gi…'
complete -c toe -s U --description 'says to write a report to the standard output, listing reverse dependencies i…'
complete -c toe -o vn --description 'specifies that (verbose) output be written to standard error, showing toe\'s p…'
complete -c toe -s V --description 'reports the version of ncurses which was used in this program, and exits.'

