# top
# Autogenerated from man page /usr/share/man/man1/top.1.gz
complete -c top -s h -s v --description 'Show library version and the usage prompt, then quit.'
complete -c top -s b --description 'Starts topfrom topIn this mode, toplimit you\'ve set with the `-n\'  or until k…'
complete -c top -s c --description 'Starts topThus, if topnames, and vice versa.'
complete -c top -s d -s d --description 'Specifies the delay between screen updates, and overrides the corresponding v…'
complete -c top -s E -s E --description 'Instructs top    k - kibibytes    m - mebibytes    g - gibibytes    t - tebib…'
complete -c top -s H --description 'Instructs topWithout this  a summation of all threads in each process is show…'
complete -c top -s i --description 'Starts topWhen this toggle is Offlast update will not be displayed.'
complete -c top -s n -s n --description 'Specifies the maximum number of iterations, or frames, topproduce before endi…'
complete -c top -s o -s o --description 'Specifies the name of the field on which tasks will be sorted, independent of…'
complete -c top -s O --description 'This option acts as a form of help for the above -o option.'
complete -c top -s p -o pN1 -o pN2 -o pN1 --description 'Monitor only processes with specified process IDs.'
complete -c top -s s --description 'Starts topThis mode is far better controlled through a system  ( 6.  FILES).'
complete -c top -s S --description 'Starts topWhen Cumulative time mode is Ontime that it and its dead children h…'
complete -c top -s u -s U -s u -s U --description 'Display only processes with a user id or user name matching that given.'
complete -c top -s w -s w --description 'In Batch mode, when used without an argument topoutput using the COLUMNS= and…'
complete -c top -s 1 --description 'Starts topEither all cpueach cpu (\'2\').'

