# trietool-0
# Autogenerated from man page /usr/share/man/man1/trietool-0.2.1.gz
complete -c trietool-0 -s p -l path --description 'Set trie directory to dir [default=`. \'].'
complete -c trietool-0 -s h -l help --description 'Show summary of options.'
complete -c trietool-0 -s e -l encoding --description 'Specify character encoding of the list-file contents, such as `UTF-8\'.'
complete -c trietool-0 -s V -l version --description 'Show version of program.'

