# trietool
# Autogenerated from man page /usr/share/man/man1/trietool.1.gz
complete -c trietool -s p -l path --description 'Set trie directory to dir [default=`. \'].'
complete -c trietool -s h -l help --description 'Show summary of options.'
complete -c trietool -s e -l encoding --description 'Specify character encoding of the list-file contents, such as `UTF-8\'.'
complete -c trietool -s V -l version --description 'Show version of program.'

