# true
# Autogenerated from man page /usr/share/man/man1/true.1.gz
complete -c true -l help --description 'display this help and exit.'
complete -c true -l version --description 'output version information and exit.'

