# truncate
# Autogenerated from man page /usr/share/man/man1/truncate.1.gz
complete -c truncate -s c -l no-create --description 'do not create any files.'
complete -c truncate -s o -l io-blocks --description 'treat SIZE as number of IO blocks instead of bytes.'
complete -c truncate -s r -l reference --description 'base size on RFILE.'
complete -c truncate -s s -l size --description 'set or adjust the file size by SIZE bytes.'
complete -c truncate -l help --description 'display this help and exit.'
complete -c truncate -l version --description 'output version information and exit.'

