# trust
# Autogenerated from man page /usr/share/man/man1/trust.1.gz
complete -c trust -s v -l verbose --description '.'
complete -c trust -s q -l quiet --description '.'
complete -c trust -l filter --description '.'
complete -c trust -l purpose --description '.'
complete -c trust -l store --description 'or.'
complete -c trust -l remove --description 'operations.  If no operation is specified then.'
complete -c trust -l format --description 'arguments should be specified.'
complete -c trust -l comment --description '.'
complete -c trust -l overwrite --description '.'

