# tset
# Autogenerated from man page /usr/share/man/man1/tset.1.gz
complete -c tset -s c --description 'Set control characters and modes.'
complete -c tset -s e --description 'Set the erase character to ch.'
complete -c tset -s I --description 'Do not send the terminal or tab initialization strings to the terminal.'
complete -c tset -s i --description 'Set the interrupt character to ch.'
complete -c tset -s k --description 'Set the line kill character to ch.'
complete -c tset -s m --description 'Specify a mapping from a port type to a terminal.'
complete -c tset -s Q --description 'Do not display any values for the erase, interrupt and line kill characters.'
complete -c tset -s q --description 'The terminal type is displayed to the standard output, and the terminal is no…'
complete -c tset -s r --description 'Print the terminal type to the standard error output.'
complete -c tset -s s --description 'Print the sequence of shell commands to initialize the environment variable T…'
complete -c tset -s V --description 'reports the version of ncurses which was used in this program, and exits.'
complete -c tset -s w --description 'Resize the window to match the size deduced via setupterm(3X).'
complete -c tset -s n --description 'This implementation does not provide that choice.'

