# tsort
# Autogenerated from man page /usr/share/man/man1/tsort.1.gz
complete -c tsort -l help --description 'display this help and exit.'
complete -c tsort -l version --description 'output version information and exit AUTHOR Written by Mark Kettenis.'

