# tty
# Autogenerated from man page /usr/share/man/man1/tty.1.gz
complete -c tty -s s -l silent -l quiet --description 'print nothing, only return an exit status.'
complete -c tty -l help --description 'display this help and exit.'
complete -c tty -l version --description 'output version information and exit AUTHOR Written by David MacKenzie.'

