# umount
# Autogenerated from man page /usr/share/man/man8/umount.8.gz
complete -c umount -s a -l all --description 'All of the filesystems described in  /proc/self/mountinfo (or in deprecated /…'
complete -c umount -s A -l all-targets --description 'Unmount all mountpoints in the current namespace for the specified filesystem.'
complete -c umount -s c -l no-canonicalize --description 'Do not canonicalize paths.'
complete -c umount -s d -l detach-loop --description 'When the unmounted device was a loop device, also free this loop device.'
complete -c umount -l fake --description 'Causes everything to be done except for the actual system call or umount help…'
complete -c umount -s f -l force --description 'Force an unmount (in case of an unreachable NFS system).'
complete -c umount -s i -l internal-only --description 'Do not call the /sbin/umount. filesystem helper even if it exists.'
complete -c umount -s l -l lazy --description 'Lazy unmount.'
complete -c umount -s n -l no-mtab --description 'Unmount without writing in R /etc/mtab .'
complete -c umount -s O -l test-opts --description 'Unmount only the filesystems that have the specified option set in R /etc/fst…'
complete -c umount -s R -l recursive --description 'Recursively unmount each specified directory.'
complete -c umount -s r -l read-only --description 'When an unmount fails, try to remount the filesystem read-only.'
complete -c umount -s t -l types --description 'Indicate that the actions should only be taken on filesystems of the specifie…'
complete -c umount -s v -l verbose --description 'Verbose mode.'
complete -c umount -s V -l version --description 'Display version information and exit.'
complete -c umount -s h -l help --description 'Display help text and exit.'

