# uncompress
# Autogenerated from man page /usr/share/man/man1/uncompress.1p.gz
complete -c uncompress -s b --description 'it is implementation-defined whether values of.'
complete -c uncompress -s c --description 'Write to standard output; no files are changed.'
complete -c uncompress -s f --description 'Do not prompt for overwriting files.  Except when run in the background, if.'
complete -c uncompress -s v --description 'Write messages to standard error concerning the expansion of each file.'

