# unexpand
# Autogenerated from man page /usr/share/man/man1/unexpand.1.gz
complete -c unexpand -s a -l all --description 'convert all blanks, instead of just initial blanks.'
complete -c unexpand -l first-only --description 'convert only leading sequences of blanks (overrides -a).'
complete -c unexpand -s t -l tabs --description 'have tabs N characters apart instead of 8 (enables -a).'
complete -c unexpand -l help --description 'display this help and exit.'
complete -c unexpand -l version --description 'output version information and exit AUTHOR Written by David MacKenzie.'

