# uniq
# Autogenerated from man page /usr/share/man/man1/uniq.1.gz
complete -c uniq -s c -l count --description 'prefix lines by the number of occurrences.'
complete -c uniq -s d -l repeated --description 'only print duplicate lines, one for each group.'
complete -c uniq -s D --description 'print all duplicate lines.'
complete -c uniq -l all-repeated --description 'like -D, but allow separating groups with an empty line; METHOD={none(default…'
complete -c uniq -s f -l skip-fields --description 'avoid comparing the first N fields.'
complete -c uniq -l group --description 'show all items, separating groups with an empty line; METHOD={separate(defaul…'
complete -c uniq -s i -l ignore-case --description 'ignore differences in case when comparing.'
complete -c uniq -s s -l skip-chars --description 'avoid comparing the first N characters.'
complete -c uniq -s u -l unique --description 'only print unique lines.'
complete -c uniq -s z -l zero-terminated --description 'line delimiter is NUL, not newline.'
complete -c uniq -s w -l check-chars --description 'compare no more than N characters in lines.'
complete -c uniq -l help --description 'display this help and exit.'
complete -c uniq -l version --description 'output version information and exit.'

