# urxvtd
# Autogenerated from man page /usr/share/man/man1/urxvtd.1.gz
complete -c urxvtd -s q -l quiet --description 'Normally, urxvtd outputs the message \\f(CW\\*(C`rxvt-unicode daemon listening …'
complete -c urxvtd -s o -l opendisplay --description 'This forces urxvtd to open a connection to the current \\f(CW$DISPLAY and keep…'
complete -c urxvtd -s f -l fork --description 'This makes urxvtd fork after it has bound itself to its control socket.'
complete -c urxvtd -s m -l mlock --description 'This makes urxvtd call mlockall\\|(2) on itself.'

