# users
# Autogenerated from man page /usr/share/man/man1/users.1.gz
complete -c users -l help --description 'display this help and exit.'
complete -c users -l version --description 'output version information and exit AUTHOR Written by Joseph Arceneaux and Da…'

