# userdel
# Autogenerated from man page /usr/share/man/man8/userdel.8.gz
complete -c userdel -s f -l force --description 'This option forces the removal of the user account, even if the user is still…'
complete -c userdel -s h -l help --description 'Display help message and exit.'
complete -c userdel -s r -l remove --description 'Files in the user\\*(Aqs home directory will be removed along with the home di…'
complete -c userdel -s R -l rootCHROOT_DIR --description 'Apply changes in the CHROOT_DIR directory and use the configuration files fro…'
complete -c userdel -s Z -l selinux-user --description 'Remove any SELinux user mapping for the user\\*(Aqs login.'
complete -c userdel -l root --description '.'

