# uuencode
# Autogenerated from man page /usr/share/man/man1/uuencode.1p.gz
complete -c uuencode -s m --description 'Encode the output using the MIME Base64 algorithm described in STDOUT.  If.'
complete -c uuencode -s b --description '(for Base64), but it was renamed to reflect its relationship to the RFC 2045.'
complete -c uuencode -s u --description 'was also present to invoke the default algorithm, but since this was not hist…'

