# uuidgen
# Autogenerated from man page /usr/share/man/man1/uuidgen.1.gz
complete -c uuidgen -s r -l random --description 'Generate a random-based UUID.'
complete -c uuidgen -s t -l time --description 'Generate a time-based UUID.'
complete -c uuidgen -s h -l help --description 'Display help text and exit.'
complete -c uuidgen -s V -l version --description 'Display version information and exit.'
complete -c uuidgen -s m -l md5 --description 'Use MD5 as the hash algorithm.'
complete -c uuidgen -s s -l sha1 --description 'Use SHA1 as the hash algorithm.'
complete -c uuidgen -s n -l namespace --description 'Generate the hash with the namespace prefix.'
complete -c uuidgen -s N -l name --description 'Generate the hash of the name.'
complete -c uuidgen -s x -l hex --description 'Interpret name name as a hexadecimal string.  CONFORMING TO OSF DCE 1.'

