# uuidparse
# Autogenerated from man page /usr/share/man/man1/uuidparse.1.gz
complete -c uuidparse -s J -l json --description 'Use JSON output format.'
complete -c uuidparse -s n -l noheadings --description 'Do not print a header line.'
complete -c uuidparse -s o -l output --description 'Specify which output columns to print.'
complete -c uuidparse -s r -l raw --description 'Use the raw output format.'
complete -c uuidparse -s V -l version --description 'Display version information and exit.'
complete -c uuidparse -s h -l help --description 'Display help text and exit.  AUTHORS.'

