# uux
# Autogenerated from man page /usr/share/man/man1/uux.1p.gz
complete -c uux -s n --description 'option.'
complete -c uux -s j --description 'Write the job identification string to standard output.'
complete -c uux -s p --description 'Make the standard input to uux the standard input to the command-string .'

