# version
# Autogenerated from man page /usr/share/man/man1/version.1ssl.gz
complete -c version -o help --description 'Print out a usage message.'
complete -c version -s a --description 'all information, this is the same as setting all the other flags.'
complete -c version -s v --description 'the current OpenSSL version.'
complete -c version -s b --description 'the date the current version of OpenSSL was built.'
complete -c version -s o --description 'option information: various options set when the library was built.'
complete -c version -s f --description 'compilation flags.'
complete -c version -s p --description 'platform setting.'
complete -c version -s d --description '\\s-1OPENSSLDIR\\s0 setting.'

