# vgexport
# Autogenerated from man page /usr/share/man/man8/vgexport.8.gz
complete -c vgexport -s a -l all --description '.'
complete -c vgexport -l commandprofile --description '.'
complete -c vgexport -l config --description '.'
complete -c vgexport -s d -l debug --description '.'
complete -c vgexport -l driverloaded --description '.'
complete -c vgexport -s h -l help --description '.'
complete -c vgexport -l longhelp --description '.'
complete -c vgexport -l profile --description '.'
complete -c vgexport -s q -l quiet --description '.'
complete -c vgexport -l reportformat --description '.'
complete -c vgexport -s S -l select --description '.'
complete -c vgexport -s t -l test --description '.'
complete -c vgexport -s v -l verbose --description '.'
complete -c vgexport -l version --description '.'
complete -c vgexport -s y -l yes --description '.'

