# vgimport
# Autogenerated from man page /usr/share/man/man8/vgimport.8.gz
complete -c vgimport -s a -l all --description '.'
complete -c vgimport -l commandprofile --description '.'
complete -c vgimport -l config --description '.'
complete -c vgimport -s d -l debug --description '.'
complete -c vgimport -l driverloaded --description '.'
complete -c vgimport -s f -l force --description '.'
complete -c vgimport -s h -l help --description '.'
complete -c vgimport -l longhelp --description '.'
complete -c vgimport -l profile --description '.'
complete -c vgimport -s q -l quiet --description '.'
complete -c vgimport -l reportformat --description '.'
complete -c vgimport -s S -l select --description '.'
complete -c vgimport -s t -l test --description '.'
complete -c vgimport -s v -l verbose --description '.'
complete -c vgimport -l version --description '.'
complete -c vgimport -s y -l yes --description '.'

