# vgmerge
# Autogenerated from man page /usr/share/man/man8/vgmerge.8.gz
complete -c vgmerge -s A -l autobackup --description '.'
complete -c vgmerge -l commandprofile --description '.'
complete -c vgmerge -l config --description '.'
complete -c vgmerge -s d -l debug --description '.'
complete -c vgmerge -l driverloaded --description '.'
complete -c vgmerge -s h -l help --description '.'
complete -c vgmerge -s l -l list --description '.'
complete -c vgmerge -l longhelp --description '.'
complete -c vgmerge -l profile --description '.'
complete -c vgmerge -s q -l quiet --description '.'
complete -c vgmerge -s t -l test --description '.'
complete -c vgmerge -s v -l verbose --description '.'
complete -c vgmerge -l version --description '.'
complete -c vgmerge -s y -l yes --description '.'

