# vgmknodes
# Autogenerated from man page /usr/share/man/man8/vgmknodes.8.gz
complete -c vgmknodes -l commandprofile --description '.'
complete -c vgmknodes -l config --description '.'
complete -c vgmknodes -s d -l debug --description '.'
complete -c vgmknodes -l driverloaded --description '.'
complete -c vgmknodes -s h -l help --description '.'
complete -c vgmknodes -l ignorelockingfailure --description '.'
complete -c vgmknodes -l longhelp --description '.'
complete -c vgmknodes -l profile --description '.'
complete -c vgmknodes -s q -l quiet --description '.'
complete -c vgmknodes -l refresh --description '.'
complete -c vgmknodes -l reportformat --description '.'
complete -c vgmknodes -s t -l test --description '.'
complete -c vgmknodes -s v -l verbose --description '.'
complete -c vgmknodes -l version --description '.'
complete -c vgmknodes -s y -l yes --description '.'

