# vgremove
# Autogenerated from man page /usr/share/man/man8/vgremove.8.gz
complete -c vgremove -l commandprofile --description '.'
complete -c vgremove -l config --description '.'
complete -c vgremove -s d -l debug --description '.'
complete -c vgremove -l driverloaded --description '.'
complete -c vgremove -s f -l force --description '.'
complete -c vgremove -s h -l help --description '.'
complete -c vgremove -l longhelp --description '.'
complete -c vgremove -l noudevsync --description '.'
complete -c vgremove -l profile --description '.'
complete -c vgremove -s q -l quiet --description '.'
complete -c vgremove -l reportformat --description '.'
complete -c vgremove -s S -l select --description '.'
complete -c vgremove -s t -l test --description '.'
complete -c vgremove -s v -l verbose --description '.'
complete -c vgremove -l version --description '.'
complete -c vgremove -s y -l yes --description '.'

