# vgrename
# Autogenerated from man page /usr/share/man/man8/vgrename.8.gz
complete -c vgrename -s A -l autobackup --description '.'
complete -c vgrename -l commandprofile --description '.'
complete -c vgrename -l config --description '.'
complete -c vgrename -s d -l debug --description '.'
complete -c vgrename -l driverloaded --description '.'
complete -c vgrename -s f -l force --description '.'
complete -c vgrename -s h -l help --description '.'
complete -c vgrename -l longhelp --description '.'
complete -c vgrename -l profile --description '.'
complete -c vgrename -s q -l quiet --description '.'
complete -c vgrename -l reportformat --description '.'
complete -c vgrename -s t -l test --description '.'
complete -c vgrename -s v -l verbose --description '.'
complete -c vgrename -l version --description '.'
complete -c vgrename -s y -l yes --description '.'

