# vi
# Autogenerated from man page /usr/share/man/man1/vi.1p.gz
complete -c vi -s 1 --description 'error.   b.'
complete -c vi -s 2 --description 'follows, and the window edit option shall not be affected.'
complete -c vi -s D --description 'can result in a completely changed screen, without any overlap.'

