# visudo
# Autogenerated from man page /usr/share/man/man8/visudo.8.gz
complete -c visudo -s c --description 'Enable check-only mode.'
complete -c visudo -s f --description 'Specify an alternate sudoers file location.'
complete -c visudo -s h --description 'Display a short help message to the standard output and exit.'
complete -c visudo -s q --description 'Enable quiet mode.  In this mode details about syntax errors are not printed.'
complete -c visudo -s s --description 'Enable strict checking of the sudoers file.'
complete -c visudo -s V --description 'Print the visudo and sudoers grammar versions and exit.'

