# voikkospell
# Autogenerated from man page /usr/share/man/man1/voikkospell.1.gz
complete -c voikkospell -s m --description 'In addition to spelling result, prints morphological analysis info (A:) for r…'
complete -c voikkospell -s M --description 'Prints morphological analysis info (A:) for recognized words without displayi…'
complete -c voikkospell -s t --description 'Prints only "C" or "W" instead of typical full output.'
complete -c voikkospell -o tt --description 'Prints only misspelled words.'
complete -c voikkospell -s s --description 'Prints suggestions (S:) for incorrectly spelled words.'
complete -c voikkospell -s c --description 'Set cache size parameter to R n .  -1 disables the cache and 0 is the default.'
complete -c voikkospell -s j --description 'Use  n threads for spell checking.'
complete -c voikkospell -s x --description 'Like  voikkospell -s but output is printed on one line separated by character…'
complete -c voikkospell -s l --description 'Prints a list of available dictionary variants and exits.'
complete -c voikkospell -s L --description 'Prints a list of capabilities and languages for which these capabilities are …'
complete -c voikkospell -s 1 --description 'For checking large amounts of unsorted text you may want to set n to 5 to get…'
complete -c voikkospell -s p --description '(voikkospell, voikkohyphenate, voikkogc) Look from directory before the stand…'
complete -c voikkospell -s d --description '(voikkospell, voikkohyphenate, voikkogc) Use dictionary variant variant inste…'
complete -c voikkospell -s h -l help --description 'Print a help message and exit.'
complete -c voikkospell -l version --description 'Print version numbers for libvoikko and the test tool.'

