# voikkovfstc
# Autogenerated from man page /usr/share/man/man1/voikkovfstc.1.gz
complete -c voikkovfstc -s o --description 'Specify name for output file.'
complete -c voikkovfstc -s f --description 'Specify format for output file.'
complete -c voikkovfstc -s w --description 'Produce weighted transducers instead of unweighted transducers.'

