# w
# Autogenerated from man page /usr/share/man/man1/w.1.gz
complete -c w -s h -l no-header --description 'Don\'t print the header.'
complete -c w -s u -l no-current --description 'Ignores the username while figuring out the current process and cpu times.'
complete -c w -s s -l short --description 'Use the short format.   Don\'t print the login time, JCPU or PCPU times.'
complete -c w -s f -l from --description 'Toggle printing the from (remote hostname) field.'
complete -c w -l help --description 'Display help text and exit.'
complete -c w -s i -l ip-addr --description 'Display IP address instead of hostname for from field.'
complete -c w -s V -l version --description 'Display version information.'
complete -c w -s o -l old-style --description 'Old style output.   Prints blank space for idle times less than one minute.'

