# w3mman
# Autogenerated from man page /usr/share/man/man1/w3mman.1.gz
complete -c w3mman -s M --description 'Specify    path as alternative MANPATH to use.'
complete -c w3mman -s k --description 'Specify keyword.'
complete -c w3mman -s l --description 'Specify a file.  ENVIRONMENT Two variables are available for debugging.'

