# wall
# Autogenerated from man page /usr/share/man/man1/wall.1.gz
complete -c wall -s n -l nobanner --description 'Suppress the banner.'
complete -c wall -s t -l timeout --description 'Abandon the write attempt to the terminals after timeout seconds.'
complete -c wall -s g -l group --description 'Limit printing message to members of group defined as a  group argument.'
complete -c wall -s V -l version --description 'Display version information and exit.'
complete -c wall -s h -l help --description 'Display help text and exit.'

