# watchgnupg
# Autogenerated from man page /usr/share/man/man1/watchgnupg.1.gz
complete -c watchgnupg -l force --description 'Delete an already existing socket file.'
complete -c watchgnupg -l tcp --description 'Instead of reading from a local socket, listen for connects on TCP port n.'
complete -c watchgnupg -l time-only --description 'Do not print the date part of the timestamp.'
complete -c watchgnupg -l verbose --description 'Enable extra informational output.'
complete -c watchgnupg -l version --description 'Print version of the program and exit.'
complete -c watchgnupg -l help --description 'Display a brief help page and exit.'
complete -c watchgnupg -l list-dirs --description 'can be specified, for example `socket:///home/foo/bar/mysocket\'.'

