# watch
# Autogenerated from man page /usr/share/man/man1/watch.1.gz
complete -c watch -s d -l differences --description 'Highlight the differences between successive updates.'
complete -c watch -s n -l interval --description 'Specify update interval.   The command will not allow quicker than 0.'
complete -c watch -s p -l precise --description 'Make  watch attempt to run  command every  interval seconds.'
complete -c watch -s t -l no-title --description 'Turn off the header showing the interval, command, and current time at the to…'
complete -c watch -s b -l beep --description 'Beep if command has a non-zero exit.'
complete -c watch -s e -l errexit --description 'Freeze updates on command error, and exit after a key press.'
complete -c watch -s g -l chgexit --description 'Exit when the output of  command changes.'
complete -c watch -s c -l color --description 'Interpret ANSI color and style sequences.'
complete -c watch -s x -l exec --description 'Pass  command to  exec (2) instead of  sh -c which reduces the need to use ex…'
complete -c watch -s h -l help --description 'Display help text and exit.'
complete -c watch -s v -l version --description 'Display version information and exit.  EXIT STATUS 0 Success.'

