# wc
# Autogenerated from man page /usr/share/man/man1/wc.1.gz
complete -c wc -s c -l bytes --description 'print the byte counts.'
complete -c wc -s m -l chars --description 'print the character counts.'
complete -c wc -s l -l lines --description 'print the newline counts.'
complete -c wc -l files0-from --description 'read input from the files specified by NUL-terminated names in file F; If F i…'
complete -c wc -s L -l max-line-length --description 'print the maximum display width.'
complete -c wc -s w -l words --description 'print the word counts.'
complete -c wc -l help --description 'display this help and exit.'
complete -c wc -l version --description 'output version information and exit AUTHOR Written by Paul Rubin and David Ma…'

