# word-list-compress
# Autogenerated from man page /usr/share/man/man1/word-list-compress.1.gz
complete -c word-list-compress -s c --description 'compress the plain text word list read from standard input.'
complete -c word-list-compress -s d --description 'decompress the compressed word list read from standard input.'

