# wrjpgcom
# Autogenerated from man page /usr/share/man/man1/wrjpgcom.1.gz
complete -c wrjpgcom -o replace --description 'Delete any existing COM blocks from the file.'
complete -c wrjpgcom -o comment --description 'Supply text for new COM block on command line.'
complete -c wrjpgcom -o cfile --description 'Read text for new COM block from named file.'

