# xargs
# Autogenerated from man page /usr/share/man/man1/xargs.1p.gz
complete -c xargs -o print --description 'or ls into commands to be executed, unexpected results are likely if any file…'
complete -c xargs -o exec --description 'with a \'+\'  terminator instead of \';\' .'

