# xcmsdb
# Autogenerated from man page /usr/share/man/man1/xcmsdb.1.gz
complete -c xcmsdb -o query --description 'This option attempts to read the XDCCC properties off the screen\'s root windo…'
complete -c xcmsdb -o remove --description 'This option attempts to remove the XDCCC properties on the screen\'s root wind…'
complete -c xcmsdb -o 'format\\032' --description 'Specifies the property format (32, 16, or 8 bits per entry) for the XDCCC_LIN…'
complete -c xcmsdb -o help --description 'This option prints a summary of the available options and exits.'

