# xcursorgen
# Autogenerated from man page /usr/share/man/man1/xcursorgen.1.gz
complete -c xcursorgen -s V -l version --description 'Display the version number and exit.'
complete -c xcursorgen -s '?' -l help --description 'Display the usage message and exit.'
complete -c xcursorgen -s p -l prefix --description 'Find cursor images in the directory specified by dir.'

