# xdg-open
# Autogenerated from man page /usr/share/man/man1/xdg-open.1.gz
complete -c xdg-open -l help --description 'Show command synopsis.'
complete -c xdg-open -l manual --description 'Show this manual page.'
complete -c xdg-open -l version --description 'Show the xdg-utils version information.'

