# xdg-email
# Autogenerated from man page /usr/share/man/man1/xdg-email.1.gz
complete -c xdg-email -l utf8 --description 'Indicates that all command line options that follow are in utf8.'
complete -c xdg-email -l cc --description 'Specify a recipient to be copied on the e-mail.'
complete -c xdg-email -l bcc --description 'Specify a recipient to be blindly copied on the e-mail.'
complete -c xdg-email -l subject --description 'Specify a subject for the e-mail.'
complete -c xdg-email -l body --description 'Specify a body for the e-mail.'
complete -c xdg-email -l attach --description 'Specify an attachment for the e-mail.  file must point to an existing file.'
complete -c xdg-email -l help --description 'Show command synopsis.'
complete -c xdg-email -l manual --description 'Show this manual page.'
complete -c xdg-email -l version --description 'Show the xdg-utils version information.'

