# xdg-screensaver
# Autogenerated from man page /usr/share/man/man1/xdg-screensaver.1.gz
complete -c xdg-screensaver -l help --description 'Show command synopsis.'
complete -c xdg-screensaver -l manual --description 'Show this manual page.'
complete -c xdg-screensaver -l version --description 'Show the xdg-utils version information.'

