# xdg-settings
# Autogenerated from man page /usr/share/man/man1/xdg-settings.1.gz
complete -c xdg-settings -l help --description 'Show command synopsis.'
complete -c xdg-settings -l list --description 'List all properties xdg-settings knows about.'
complete -c xdg-settings -l manual --description 'Show this manual page.'
complete -c xdg-settings -l version --description 'Show the xdg-utils version information.'

