# xdg-desktop-menu
# Autogenerated from man page /usr/share/man/man1/xdg-desktop-menu.1.gz
complete -c xdg-desktop-menu -l noupdate --description 'Postpone updating the menu system.'
complete -c xdg-desktop-menu -l novendor --description 'Normally, xdg-desktop-menu checks to ensure that any *. directory and *.'
complete -c xdg-desktop-menu -l mode --description 'mode can be user or system.'
complete -c xdg-desktop-menu -l help --description 'Show command synopsis.'
complete -c xdg-desktop-menu -l manual --description 'Show this manual page.'
complete -c xdg-desktop-menu -l version --description 'Show the xdg-utils version information.'

