# xfs_rtcp
# Autogenerated from man page /usr/share/man/man8/xfs_rtcp.8.gz
complete -c xfs_rtcp -s e --description 'Sets the extent size of the destination realtime file.'
complete -c xfs_rtcp -s p --description 'Use if the size of the source file is not an even multiple of the block size …'
complete -c xfs_rtcp -s V --description 'Prints the version number and exits.  SEE ALSO xfs (5), mkfs.'

