# xfs_freeze
# Autogenerated from man page /usr/share/man/man8/xfs_freeze.8.gz
complete -c xfs_freeze -s f --description 'flag requests the specified XFS filesystem to be frozen from new modification…'
complete -c xfs_freeze -s u --description 'flag is used to un-freeze the filesystem and allow operations to continue.'
complete -c xfs_freeze -s V --description 'flag prints the version number and exits.'

