# xfs_growfs
# Autogenerated from man page /usr/share/man/man8/xfs_growfs.8.gz
complete -c xfs_growfs -s d -s D --description 'Specifies that the data section of the filesystem should be grown.'
complete -c xfs_growfs -s e --description 'Allows the real-time extent size to be specified.  In  mkfs.'
complete -c xfs_growfs -s i --description 'The new log is an internal log (inside the data section).'
complete -c xfs_growfs -s l -s L --description 'Specifies that the log section of the filesystem should be grown, shrunk, or …'
complete -c xfs_growfs -s m --description 'Specify a new value for the maximum percentage of space in the filesystem tha…'
complete -c xfs_growfs -s n --description 'Specifies that no change to the filesystem is to be made.'
complete -c xfs_growfs -s r -s R --description 'Specifies that the real-time section of the filesystem should be grown.'
complete -c xfs_growfs -s t --description 'Specifies an alternate mount table file (default is  /proc/mounts if it exist…'
complete -c xfs_growfs -s x --description 'is given with.'
complete -c xfs_growfs -s V --description 'Prints the version number and exits.'

