# xfs_mkfile
# Autogenerated from man page /usr/share/man/man8/xfs_mkfile.8.gz
complete -c xfs_mkfile -s v --description 'Verbose.  Report the names and sizes of created files.'
complete -c xfs_mkfile -s n --description 'No bytes.'
complete -c xfs_mkfile -s p --description 'Preallocate.'
complete -c xfs_mkfile -s V --description 'Prints the version number and exits.'

