# xfs_estimate
# Autogenerated from man page /usr/share/man/man8/xfs_estimate.8.gz
complete -c xfs_estimate -s v --description 'Display more information, formatted.'
complete -c xfs_estimate -s h --description 'Display usage message.'
complete -c xfs_estimate -s e --description 'Use  logsize instead of the default log size of 1000 blocks.'
complete -c xfs_estimate -s b --description 'Use blocksize instead of the default blocksize of 4096 bytes.'
complete -c xfs_estimate -s i --description 'Use logsize instead of the default log size of 1000 blocks.'
complete -c xfs_estimate -s V --description 'Print the version number and exits.'

