# xfs_admin
# Autogenerated from man page /usr/share/man/man8/xfs_admin.8.gz
complete -c xfs_admin -s e --description 'Enables unwritten extent support on a filesystem that does not already have t…'
complete -c xfs_admin -s f --description 'Specifies that the filesystem image to be processed is stored in a regular fi…'
complete -c xfs_admin -s j --description 'Enables version 2 log format (journal format supporting larger log buffers).'
complete -c xfs_admin -s l --description 'Print the current filesystem label.'
complete -c xfs_admin -s p --description 'Enable 32bit project identifier support (PROJID32BIT feature).'
complete -c xfs_admin -s u --description 'Print the current filesystem UUID (Universally Unique IDentifier).'
complete -c xfs_admin -s c --description 'Enable (1) or disable (0) lazy-counters in the filesystem.'
complete -c xfs_admin -s L --description 'Set the filesystem label to R label .'
complete -c xfs_admin -s U --description 'Set the UUID of the filesystem to R uuid .'
complete -c xfs_admin -l c --description '" value for label .'
complete -c xfs_admin -s V --description 'Prints the version number and exits.'

