# xfs_bmap
# Autogenerated from man page /usr/share/man/man8/xfs_bmap.8.gz
complete -c xfs_bmap -s a --description 'If this option is specified, information about the file\'s attribute fork is p…'
complete -c xfs_bmap -s c --description 'If this option is specified, information about the file\'s copy on write fork …'
complete -c xfs_bmap -s d --description 'If portions of the file have been migrated offline by a DMAPI application, a …'
complete -c xfs_bmap -s e --description 'If this option is used,  xfs_bmap obtains all delayed allocation extents, and…'
complete -c xfs_bmap -s l --description 'If this option is used, then.'
complete -c xfs_bmap -s n --description 'If this option is given,  xfs_bmap will display at most  num_extents extents.'
complete -c xfs_bmap -s p --description 'If this option is used,  xfs_bmap obtains all unwritten (preallocated) extent…'
complete -c xfs_bmap -s v --description 'Shows verbose information.'
complete -c xfs_bmap -s V --description 'Prints the version number and exits.  SEE ALSO xfs_fsr (8), xfs (5).'

