# xfs_spaceman
# Autogenerated from man page /usr/share/man/man8/xfs_spaceman.8.gz
complete -c xfs_spaceman -s c --description 'xfs_spaceman commands may be run interactively (the default) or as arguments …'
complete -c xfs_spaceman -s a --description 'Collect free space information from this allocation group.'
complete -c xfs_spaceman -s b --description 'This argument establishes that the histogram bin sizes are successive powers …'
complete -c xfs_spaceman -s e -s h -s m --description '.'
complete -c xfs_spaceman -s d --description 'Print debugging information such as the raw free space extent information.'
complete -c xfs_spaceman -s g --description 'Print the free space block and extent counts for each AG.'
complete -c xfs_spaceman -s r --description 'Query the realtime device for free space information.'
complete -c xfs_spaceman -s s --description 'Display a summary of the free space information found.'
complete -c xfs_spaceman -s u -s p --description 'options are given, this command acts on all files.'
complete -c xfs_spaceman -s f --description 'offset / length pair are required. ).'

