# xfs_copy
# Autogenerated from man page /usr/share/man/man8/xfs_copy.8.gz
complete -c xfs_copy -s d --description 'Create a duplicate (true clone) filesystem.'
complete -c xfs_copy -s b --description 'The buffered option can be used to ensure direct IO is not attempted to any o…'
complete -c xfs_copy -s L --description 'Specifies the location of the  log if the default location of  /var/tmp/xfs_c…'
complete -c xfs_copy -s V --description 'Prints the version number and exits.'

