# xkbevd
# Autogenerated from man page /usr/share/man/man1/xkbevd.1.gz
complete -c xkbevd -o help --description 'Prints a usage message that is far more up-to-date than anything in this man …'
complete -c xkbevd -o cfg --description 'Specifies the configuration file to read.'
complete -c xkbevd -o sccmd --description 'Specifies the command used to play sounds.'
complete -c xkbevd -o sddirectory --description 'Specifies a top-level directory for sound files.'
complete -c xkbevd -o displaydisplay --description 'Specifies the display to use.   If not present, xkbevd uses $DISPLAY.'
complete -c xkbevd -o bg --description 'Tells xkbevd to fork itself (and run in the background).'
complete -c xkbevd -o synch --description 'Forces synchronization of all X requests.   Slow.'
complete -c xkbevd -s v --description 'Print more information, including debugging messages.'
complete -c xkbevd -o sc --description 'Specifies the command used to play sounds.'
complete -c xkbevd -o sd --description 'Specifies a top-level directory for sound files.'
complete -c xkbevd -o display --description 'Specifies the display to use.   If not present, xkbevd uses $DISPLAY.'
complete -c xkbevd -o version --description 'Prints the program version and exits.  SEE ALSO xev (1), xkbwatch (1), X (7).'

