# xkbvleds
# Autogenerated from man page /usr/share/man/man1/xkbvleds.1.gz
complete -c xkbvleds -o indpy --description 'Mask of LEDs to watch.'
complete -c xkbvleds -o watch --description 'turn on synchronization . PP.'
complete -c xkbvleds -o intersection --description 'Watch only LEDs in all desired sets . PP.'
complete -c xkbvleds -o union --description 'Watch LEDs in any desired sets . PP.'
complete -c xkbvleds -o help --description 'print list of options and exit . PP.'
complete -c xkbvleds -o version --description 'print program version and exit.'

