# xmlcatalog
# Autogenerated from man page /usr/share/man/man1/xmlcatalog.1.gz
complete -c xmlcatalog -l add --description 'Add an entry to CATALOGFILE.  TYPE indicates the type of entry.'
complete -c xmlcatalog -l create --description 'Create a new XML catalog.'
complete -c xmlcatalog -l del --description 'Remove entries from CATALOGFILE matching VALUE(S).'
complete -c xmlcatalog -l noout --description 'Save output to the named file rather than outputting to stdout.'
complete -c xmlcatalog -l no-super-update --description 'Do not update the SGML super catalog.'
complete -c xmlcatalog -l shell --description 'Run a shell allowing interactive queries on catalog file CATALOGFILE.'
complete -c xmlcatalog -l sgml --description 'Uses SGML super catalogs for --add and --del options.'
complete -c xmlcatalog -s v -l verbose --description 'Output debugging information.'

