# xrefresh
# Autogenerated from man page /usr/share/man/man1/xrefresh.1.gz
complete -c xrefresh -o white --description 'Use a white background.'
complete -c xrefresh -o black --description 'Use a black background (in effect, turning off all of the electron guns to th…'
complete -c xrefresh -o solid --description 'Use a solid background of the specified color.   Try green.'
complete -c xrefresh -o root --description 'Use the root window background.'
complete -c xrefresh -o none --description 'This is the default.   All of the windows simply repaint.'
complete -c xrefresh -o geometry --description 'Specifies the portion of the screen to be repainted; see X(7).'
complete -c xrefresh -o display --description 'This  argument  allows  you  to  specify the server and screen to refresh; se…'
complete -c xrefresh -o version --description 'This argument prints the program version and exits.'

