# xsetroot
# Autogenerated from man page /usr/share/man/man1/xsetroot.1.gz
complete -c xsetroot -o help --description 'Print a usage message and exit.'
complete -c xsetroot -o version --description 'Print a version message and exit.'
complete -c xsetroot -o def -o default --description 'Reset unspecified attributes to the default values.'
complete -c xsetroot -o cursor --description 'This lets you change the pointer cursor to whatever you want when the pointer…'
complete -c xsetroot -o cursor_name --description 'This lets you change the pointer cursor to one of the standard cursors from t…'
complete -c xsetroot -o xcf --description 'This lets you change the pointer cursor to one loaded from an Xcursor file as…'
complete -c xsetroot -o bitmap --description 'Use the bitmap specified in the file to set the window pattern.'
complete -c xsetroot -o mod --description 'This is used if you want a plaid-like grid pattern on your screen.'
complete -c xsetroot -o gray -o grey --description 'Make the entire background gray (Easier on the eyes).'
complete -c xsetroot -o bg -o background --description 'Use ``color\'\' as the background color.'
complete -c xsetroot -o fg -o foreground --description 'Use ``color\'\' as the foreground color.'
complete -c xsetroot -o rv -o reverse --description 'This exchanges the foreground and background colors.'
complete -c xsetroot -o solid --description 'This sets the background of the root window to the specified color.'
complete -c xsetroot -o name --description 'Set the name of the root window to ``string\'\'.   There is no default value.'
complete -c xsetroot -s d -o display --description 'Specifies the server to connect to; see X(7).'

