# xtotroff
# Autogenerated from man page /usr/share/man/man1/xtotroff.1.gz
complete -c xtotroff -s r --description 'Set the resolution for all font patterns in R FontMap .'
complete -c xtotroff -s s --description 'Set the point size for all font patterns in R FontMap .'
complete -c xtotroff -s v --description 'Print the version number.'

