# zic
# Autogenerated from man page /usr/share/man/man8/zic.8.gz
complete -c zic -s d --description 'Create time conversion information files in the named directory rather than i…'
complete -c zic -s l --description 'Use the given timezone as local time.'
complete -c zic -s p --description 'Use the given timezone\'s rules when handling POSIX-format timezone environmen…'
complete -c zic -s L --description 'Read leap second information from the file with the given name.'
complete -c zic -s v --description 'Complain if a year that appears in a data file is outside the range of years …'
complete -c zic -s s --description 'Limit time values stored in output files to values that are the same whether …'
complete -c zic -s y --description 'Use the given  command rather than  yearistype when checking year types (see …'
complete -c zic -o '	equivalent' --description 'where hour 0 is midnight at the start of the day, and hour 24 is midnight at …'

