# zipcloak
# Autogenerated from man page /usr/share/man/man1/zipcloak.1.gz
complete -c zipcloak -s b --description '.'
complete -c zipcloak -l temp-path --description 'Use the directory given by path for the temporary zip file.'
complete -c zipcloak -s d --description '.'
complete -c zipcloak -l decrypt --description 'Decrypt encrypted entries (copy if given wrong password).'
complete -c zipcloak -s h --description '.'
complete -c zipcloak -l help --description 'Show a short help.'
complete -c zipcloak -s L --description '.'
complete -c zipcloak -l license --description 'Show software license.'
complete -c zipcloak -s O --description '.'
complete -c zipcloak -l output-file --description 'Write output to new archive zipfile, leaving original archive as is.'
complete -c zipcloak -s q --description '.'
complete -c zipcloak -l quiet --description 'Quiet operation.   Suppresses some informational messages.'
complete -c zipcloak -s v --description '.'
complete -c zipcloak -l version --description 'Show version information.'

