# zipnote
# Autogenerated from man page /usr/share/man/man1/zipnote.1.gz
complete -c zipnote -s w --description 'Write comments to a zipfile from stdin (see below).'
complete -c zipnote -o bpath --description 'Use path for the temporary zip file.'
complete -c zipnote -s h --description 'Show a short help.'
complete -c zipnote -s v --description 'Show version information.'
complete -c zipnote -s b --description 'Use path for the temporary zip file.'
complete -c zipnote -s L --description 'Show software license.'

