# zipsplit
# Autogenerated from man page /usr/share/man/man1/zipsplit.1.gz
complete -c zipsplit -s t --description 'Report how many files it will take, but don\'t make them.'
complete -c zipsplit -s i --description 'Make index (zipsplit. idx) and count its size against first zip file.'
complete -c zipsplit -o nsize --description 'Make zip files no larger than "size" (default = 36000).'
complete -c zipsplit -o rroom --description 'Leave room for "room" bytes on the first disk (default = 0).'
complete -c zipsplit -o bpath --description 'Use path for the output zip files.'
complete -c zipsplit -s p --description 'Pause between output zip files.'
complete -c zipsplit -s s --description 'Do a sequential split even if it takes more zip files.'
complete -c zipsplit -s h --description 'Show a short help.'
complete -c zipsplit -s v --description 'Show version information.'
complete -c zipsplit -s n --description 'Make zip files no larger than "size" (default = 36000).'
complete -c zipsplit -s r --description 'Leave room for "room" bytes on the first disk (default = 0).'
complete -c zipsplit -s b --description 'Use path for the output zip files.'
complete -c zipsplit -s L --description 'Show software license.'

