# znew
# Autogenerated from man page /usr/share/man/man1/znew.1.gz
complete -c znew -s f --description 'Force recompression from . Z to . gz format even if a .'
complete -c znew -s t --description 'Tests the new files before deleting originals.'
complete -c znew -s v --description 'Verbose.  Display the name and percentage reduction for each file compressed.'
complete -c znew -s 9 --description 'Use the slowest compression method (optimal compression).'
complete -c znew -s P --description 'Use pipes for the conversion to reduce disk space usage.'
complete -c znew -s K --description 'Keep a . Z file when it is smaller than the . gz file; implies.'

