# zramctl
# Autogenerated from man page /usr/share/man/man8/zramctl.8.gz
complete -c zramctl -s a -l algorithm --description 'Set the compression algorithm to be used for compressing data in the zram dev…'
complete -c zramctl -s f -l find --description 'Find the first unused zram device.'
complete -c zramctl -s n -l noheadings --description 'Do not print a header line in status output.'
complete -c zramctl -s o -l output --description 'Define the status output columns to be used.'
complete -c zramctl -l raw --description 'Use the raw format for status output.'
complete -c zramctl -s r -l reset --description 'Reset the options of the specified zram device(s).'
complete -c zramctl -s s -l size --description 'Create a zram device of the specified size.'
complete -c zramctl -s t -l streams --description 'Set the maximum number of compression streams that can be used for the device.'
complete -c zramctl -s V -l version --description 'Display version information and exit.'
complete -c zramctl -s h -l help --description 'Display help text and exit.'

