# zsoelim
# Autogenerated from man page /usr/share/man/man1/zsoelim.1.gz
complete -c zsoelim -s C -l compatible --description 'This flag is available for compatibility with other   soelim programs.'
complete -c zsoelim -s h -l help --description 'Print a help message and exit.'
complete -c zsoelim -s V -l version --description 'Display version information.'

