# Shell variables
# Generated by 'wal'
wallpaper='/home/alex/Documents/wallpapers/Favourites/wallhaven-717496.png'

# Special
background='#1f1b17'
foreground='#c7c6c5'
cursor='#c7c6c5'

# Colors
color0='#1f1b17'
color1='#aa9288'
color2='#aa8369'
color3='#aa7146'
color4='#c6793c'
color5='#748aaa'
color6='#a39da5'
color7='#c7c6c5'
color8='#575451'
color9='#aa9288'
color10='#aa8369'
color11='#aa7146'
color12='#c6793c'
color13='#748aaa'
color14='#a39da5'
color15='#c7c6c5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
