# Shell variables
# Generated by 'wal'
wallpaper='/home/alex/Documents/wallpapers/Favourites/wallhaven-641710.jpg'

# Special
background='#14141f'
foreground='#c4c4c7'
cursor='#c4c4c7'

# Colors
color0='#14141f'
color1='#2b50aa'
color2='#4f4eaa'
color3='#6d61ad'
color4='#9f6fab'
color5='#aa5c86'
color6='#ab4f60'
color7='#c4c4c7'
color8='#4e4e57'
color9='#2b50aa'
color10='#4f4eaa'
color11='#6d61ad'
color12='#9f6fab'
color13='#aa5c86'
color14='#ab4f60'
color15='#c4c4c7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
