# Shell variables
# Generated by 'wal'
wallpaper='/home/alex/Documents/wallpapers/Favourites/Comfy 32.jpg'

# Special
background='#1f1e1d'
foreground='#c7c6c6'
cursor='#c7c6c6'

# Colors
color0='#1f1e1d'
color1='#bdbbba'
color2='#a9a298'
color3='#a8996a'
color4='#a9a185'
color5='#a5a6a6'
color6='#3497ad'
color7='#c7c6c6'
color8='#575655'
color9='#bdbbba'
color10='#a9a298'
color11='#a8996a'
color12='#a9a185'
color13='#a5a6a6'
color14='#3497ad'
color15='#c7c6c6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
