#! /bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         4
bspc config window_gap           12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Screenkey manage=off

# --------------------------------
# ------- Non-BSPWM related ------
# --------------------------------
# Set wallpaper
feh --bg-fill ~/Wallpapers/gruvbox.png
# Reload .Xresources
xrdb -load ~/.Xresources
# Launch polybar
#polybar -r example
~/.config/polybar/launch.sh
# Change from ugly 'X' cursor when hovering over background
xsetroot -cursor_name left_ptr
# Make betterlockscreen generate and cache a background image for locking
betterlockscreen -u ~/Wallpapers/gruvbox.png
