#! /bin/sh

sxhkd &

# If HDMI-1 connected, split workspaces to both monitors
if [ "$(xrandr | grep "HDMI-1 connected")" ]
then
    bspc monitor HDMI-1 -d 1 2 3 4 5
    bspc monitor eDP-1 -d 6 7 8 9 10

else
    bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10
fi

# Used to make polybar maintain proper workspaces per monitor when going from 2
# to 1 monitor again.. This may include some monitor re-ordering issues
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true


# Sometimes when using an external monitor that is larger than the base laptop
# screen size, padding would be applied to make the nodes the size of the
# laptop resolution - we don't want that, as the nodes should fill out the
# entire height/width of the monitor, so we set all padding to 0.
bspc config top_padding 0
bspc config right_padding 0
bspc config bottom_padding 0
bspc config left_padding 0

bspc rule -a URxvt:scratchy sticky=on state=floating rectangle=widthxheight+Xoffset+Yoffset

bspc config border_width         4
bspc config border_radius         12
bspc config window_gap           12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# --------------------------------
# ------- Non-BSPWM related ------
# --------------------------------
# Set wallpaper
feh --bg-fill ~/Documents/Wallpapers/gruvbox.png
# Reload .Xresources
xrdb -load ~/.Xresources
# Launch polybar
~/.config/polybar/launch.sh
# Change from ugly 'X' cursor when hovering over background
xsetroot -cursor_name left_ptr
# Make betterlockscreen generate and cache a background image for locking
betterlockscreen -u ~/Documents/Wallpapers/gruvbox.png
# ------- Autostart apps ------
# Picom
picom --xrender-sync-fence &
# Dunst
dunst &
# Dropbox
dropbox &
# Cmst (connman front-end)
# cmst &
# network-manager-applet
nm-applet &

# ------- Mouse/Touchpad fixes ------
# Start libinput gestures
libinput-gestures-setup start
# Xinput configs (touchpad)
xinput set-prop "DLL07BE:01 06CB:7A13 Touchpad" "libinput Natural Scrolling Enabled" 1
xinput set-prop "DLL07BE:01 06CB:7A13 Touchpad" "libinput Click Method Enabled" 0 1
xinput set-prop "DLL07BE:01 06CB:7A13 Touchpad" "libinput Disable While Typing Enabled" 0
# ------- Keyboard fixes ------
# Remap Caps-lock key to Escape, for using VIM
setxkbmap -option caps:escape
# Make US and DK keyboard layout togglable with Shift+Alt
setxkbmap -layout us,dk -option grp:alt_shift_toggle

export _JAVA_AWT_WM_NONREPARENTING=1

